import {randomUUID} from 'node:crypto';
import {it,expect} from 'vitest';
import {fixtureCommand} from '../helpers/commands';
import {FacebookMessengerAdapter} from '../../packages/adapters/src/facebook-messenger';
const account=randomUUID(),command=fixtureCommand({account_id:account,capability_key:'facebook.messenger.reply.api',adapter_version:'facebook-messenger-v1',platform_api_version:'v99.0',mode:'CONTROLLED_PILOT',is_synthetic:false,message:{conversation_id:randomUUID(),trigger_message_id:randomUUID(),trigger_sequence:1,control_version:1,actor_kind:'AI',actor_id:randomUUID(),connection_version:1,contact:{account_id:account,channel:'facebook_messenger',remote_id:'123456789',target_id:randomUUID(),permission_id:randomUUID(),purpose:'customer_service',target_version:1,policy_hash:'b'.repeat(64)},stop_epochs:{organization:0,brand:0,account:0,agent:0},referral:null}});
function adapter(responses:unknown[]){const calls:{url:URL;init?:RequestInit}[]=[];const mock:typeof fetch=async(input,init)=>{calls.push({url:new URL(String(input)),init});const value=responses[calls.length-1];if(value instanceof Error)throw value;return Response.json(value);};return {client:new FacebookMessengerAdapter({version:'v99.0',pageToken:'contract-only',fetch:mock}),calls};}
it('verifies Page, sends to the exact recipient once and returns acceptance evidence',async()=>{const {client,calls}=adapter([{id:command.snapshot.external_account_id},{recipient_id:'123456789',message_id:'m:123_ABC'}]);let grants=0;expect(await client.execute(command.snapshot,async()=>{grants++;},command.action_id)).toMatchObject({recipient_id:'123456789',remote_id:'m:123_ABC',evidence_kind:'graph_message'});expect(grants).toBe(1);expect(calls.map(row=>row.init?.method)).toEqual(['GET','POST']);expect(calls[1].url.pathname).toBe('/v99.0/'+command.snapshot.external_account_id+'/messages');const body=new URLSearchParams(calls[1].init?.body as string);expect(body.get('messaging_type')).toBe('RESPONSE');expect(JSON.parse(body.get('recipient')!)).toEqual({id:'123456789'});expect(JSON.parse(body.get('message')!).metadata).toBe('kff:'+command.action_id);});
it('never reaches the send boundary when the Page identity is wrong',async()=>{const {client,calls}=adapter([{id:'999'}]);await expect(client.execute(command.snapshot,async()=>{throw new Error('must not grant');},command.action_id)).rejects.toMatchObject({code:'ACCOUNT_MISMATCH'});expect(calls).toHaveLength(1);});
it('a stop at the final submission gate prevents all HTTP writes',async()=>{const {client,calls}=adapter([{id:command.snapshot.external_account_id}]);await expect(client.execute(command.snapshot,async()=>{throw new Error('stopped');},command.action_id)).rejects.toThrow('stopped');expect(calls).toHaveLength(1);});
it.each([{recipient_id:'other',message_id:'m_1'},{message_id:'m_1'},new Error('connection lost')])('does not retry or turn uncertain send responses into success',async response=>{const {client,calls}=adapter([{id:command.snapshot.external_account_id},response]);await expect(client.execute(command.snapshot,async()=>{},command.action_id)).rejects.toThrow();expect(calls.filter(row=>row.init?.method==='POST')).toHaveLength(1);});
