import {createHmac} from 'node:crypto';
import {describe,it,expect} from 'vitest';
import {facebookChallenge,normalizeFacebookEvents,verifyFacebookSignature} from '../../packages/adapters/src/facebook-events';
import {facebookEvent} from '../../packages/contracts/src/lead';
const secret='a-valid-fixture-secret-not-a-credential';
const message=(page='1001',person='2001')=>({sender:{id:person},recipient:{id:page},timestamp:Date.now(),message:{mid:'m_fixture',text:'Can I add your WhatsApp?'},referral:{ref:'ad_campaign',ad_id:'7001'}});
describe('Facebook Page event contract',()=>{
  it('verifies exact raw bytes before parsing and never accepts missing or changed signatures',()=>{const bytes=Buffer.from('{"object":"page","entry":[]}'),signature='sha256='+createHmac('sha256',secret).update(bytes).digest('hex');expect(()=>verifyFacebookSignature(bytes,signature,secret)).not.toThrow();for(const supplied of [null,'sha1=abc','sha256='+'0'.repeat(64)])expect(()=>verifyFacebookSignature(bytes,supplied,secret)).toThrow();expect(()=>verifyFacebookSignature(Buffer.from('{}'),signature,secret)).toThrow();expect(()=>verifyFacebookSignature(bytes,signature,undefined)).toThrow();});
  it('returns only a matching verification challenge',()=>{const query=new URLSearchParams({'hub.mode':'subscribe','hub.verify_token':secret,'hub.challenge':'verify-123'});expect(facebookChallenge(query,secret)).toBe('verify-123');query.set('hub.verify_token','incorrect');expect(()=>facebookChallenge(query,secret)).toThrow();});
  it('normalizes multiple pages, stable long IDs, attachments and native echo without losing account attribution',()=>{const a=message('123456789012345678901','222222222222222222222');const echo={...message('1002','2002'),sender:{id:'1002'},recipient:{id:'2002'},message:{mid:'echo1',is_echo:true,text:'Human reply'}};const result=normalizeFacebookEvents({object:'page',entry:[{id:a.recipient.id,messaging:[a,{...a,message:{mid:'attachment1',attachments:[{type:'image'}]}}]},{id:'1002',messaging:[echo]}]});expect(result.events).toHaveLength(3);expect(result.events[0]).toMatchObject({page_id:a.recipient.id,sender_id:a.sender.id,source:{ref:'ad_campaign',ad_id:'7001'}});expect(result.events[1].has_attachment).toBe(true);expect(result.events[2]).toMatchObject({kind:'ECHO',sender_id:'2002',page_id:'1002'});});
  it('keeps comments and interactions distinct; missing identity and unsupported partial events are counted',()=>{const result=normalizeFacebookEvents({object:'page',entry:[{id:'1001',time:Date.now(),changes:[{field:'feed',value:{item:'comment',verb:'add',comment_id:'1001_7',post_id:'1001_5',from:{id:'2222',name:'Test'},message:'Interested'}},{field:'feed',value:{item:'reaction',verb:'add',post_id:'1001_5',from:{id:'3333'}}},{field:'feed',value:{item:'comment',verb:'add',comment_id:'c1'}},{field:'feed',value:{item:'comment',verb:'remove'}}],messaging:[{delivery:{mids:['unknown']}}]}]});expect(result.events.map(row=>row.kind)).toEqual(['COMMENT','INTERACTION']);expect(result.ignored).toEqual({UNSUPPORTED_MESSAGING_EVENT:1,MISSING_CUSTOMER_IDENTITY:1,UNSUPPORTED_FEED_EVENT:1});expect(normalizeFacebookEvents({object:'page',entry:[]}).events).toEqual([]);});
  it('rejects wrong Page, malformed timestamps, huge batches, and source-kind mismatch',()=>{const entry={id:'999',messaging:[message()]};expect(()=>normalizeFacebookEvents({object:'page',entry:[entry]})).toThrow();expect(()=>normalizeFacebookEvents({object:'page',entry:[{id:'1001',messaging:[{...message(),timestamp:'now'}]}]})).toThrow();expect(()=>normalizeFacebookEvents({object:'page',entry:[{id:'1001',messaging:Array(201).fill(message())}]})).toThrow();const event=normalizeFacebookEvents({object:'page',entry:[{id:'1001',messaging:[message()]}]}).events[0];expect(facebookEvent.safeParse({...event,source:{...event.source,kind:'COMMENT'}}).success).toBe(false);});
});
