import {randomUUID,randomBytes} from 'node:crypto';
import {createServer} from 'node:http';
import Stripe from 'stripe';
import {it,expect} from 'vitest';
import {stripeConnectionInput,checkoutInput,type StripeConnection} from '../../packages/contracts/src/payment';
import type {OrderSnapshot} from '../../packages/contracts/src/order';
import {stripeCheckoutRequest,validateStripeAmount,stripeSdkGateway,STRIPE_API_VERSION,stripeSecrets} from '../../packages/core/src/stripe-gateway';
import {StripeFixture,syntheticStripeCredentials} from '../helpers/stripe-fixture';
function snapshot(currency='USD',minor=2,amount='1250'):OrderSnapshot {return {schema_version:'kff.order.v1',customer_id:randomUUID(),customer_version:1,customer_display_name:'Synthetic',conversation_id:null,currency,minor_unit_exponent:minor,precision_source:'Synthetic documented precision',lines:[{product_id:randomUUID(),product_version_id:randomUUID(),product_version_number:1,product_state_version:1,sku:'SYN',name:'Synthetic service',unit_amount_minor:amount,quantity:1,line_total_minor:amount,delivery_scope:'Synthetic only',terms:'Synthetic only'}],total_minor:amount,price_scope:'EXPLICIT_LINE_TOTALS',created_at:new Date().toISOString()};}
it('requires confirmation and server-owned references, rejecting client price, tenant, keys and payment state',()=>{
 const value={request_id:randomUUID(),connection_id:randomUUID(),expected_version:1,snapshot_hash:'a'.repeat(64),confirmation:'CREATE_STRIPE_CHECKOUT'};expect(checkoutInput.safeParse(value).success).toBe(true);for(const extra of [{amount_minor:1},{currency:'usd'},{brand_id:randomUUID()},{payment_state:'PAID'},{url:'https://example.com'}])expect(checkoutInput.safeParse({...value,...extra}).success).toBe(false);
 const connection={request_id:randomUUID(),name:'Synthetic',stripe_account_id:'acct_synthetic',mode:'TEST',credential_ref:'KFF_STRIPE_TEST'};expect(stripeConnectionInput.safeParse(connection).success).toBe(true);expect(stripeConnectionInput.safeParse({...connection,api_key:'never accept keys in this API'}).success).toBe(false);expect(checkoutInput.safeParse({...value,confirmation:'YES'}).success).toBe(false);
});
it('uses Stripe charge precision and exact integer bounds, including zero-decimal and legacy whole-unit currencies',()=>{
 expect(()=>validateStripeAmount(snapshot('JPY',0,'1200'))).not.toThrow();expect(()=>validateStripeAmount(snapshot('JPY',2))).toThrow();expect(()=>validateStripeAmount(snapshot('USD',2,'0'))).toThrow();expect(()=>validateStripeAmount(snapshot('USD',2,'999999999999999999'))).toThrow();expect(()=>validateStripeAmount(snapshot('ISK',2,'500'))).not.toThrow();expect(()=>validateStripeAmount(snapshot('UGX',2,'501'))).toThrow();expect(()=>validateStripeAmount(snapshot('HUF',2,'501'))).not.toThrow();
});
it('keeps missing and wrong-mode credentials closed without echoing secret values',()=>{
 const ref='KFF_STRIPE_'+randomBytes(5).toString('hex').toUpperCase(),connection={credential_ref:ref,mode:'TEST' as const,organization_id:randomUUID(),brand_id:randomUUID(),stripe_account_id:'acct_synthetic'};expect(()=>stripeSecrets(connection)).toThrow('尚未配置');const keys=syntheticStripeCredentials(ref,connection);try{expect(()=>stripeSecrets({...connection,brand_id:randomUUID()})).toThrow('未授权');process.env[ref+'_API_KEY']='rk_live_'+randomBytes(24).toString('hex');expect(()=>stripeSecrets(connection)).toThrow('模式不匹配');process.env[ref+'_API_KEY']=keys.apiKey;expect(stripeSecrets(connection).api_key).toBe(keys.apiKey);}finally{for(const suffix of ['API_KEY','WEBHOOK_SECRETS','ORGANIZATION_ID','BRAND_ID','ACCOUNT_ID'])delete process.env[ref+'_'+suffix];}
});
it('exercises the installed Stripe SDK against a local HTTP fixture with pinned API, fixed metadata and idempotency',async()=>{
 const fixture=new StripeFixture(),orderId=randomUUID(),checkoutId=randomUUID(),brandId=randomUUID(),hash='a'.repeat(64),params=stripeCheckoutRequest(snapshot(),orderId,checkoutId,brandId,hash),observed:{method:string;url:string;version:string|undefined;key:string|undefined;body:string}[]=[];let sessionId='';
 const server=createServer(async(req,res)=>{try{let body='';for await(const chunk of req)body+=chunk.toString();observed.push({method:req.method!,url:req.url!,version:req.headers['stripe-version'] as string|undefined,key:req.headers['idempotency-key'] as string|undefined,body});res.setHeader('Content-Type','application/json');
  if(req.url==='/v1/account')res.end(JSON.stringify({id:fixture.accountId,object:'account',country:'US'}));else if(req.url==='/v1/country_specs/US')res.end(JSON.stringify({id:'US',object:'country_spec',supported_payment_currencies:fixture.currencies}));else if(req.method==='POST'){const session=await fixture.createSession(params,String(req.headers['idempotency-key']));sessionId=session.id;res.end(JSON.stringify(session));}else if(req.url?.includes('/checkout/sessions/'))res.end(JSON.stringify(await fixture.retrieveSession(sessionId)));else res.end(JSON.stringify(await fixture.retrieveIntent(fixture.sessions.get(sessionId)!.payment_intent as string)));
 }catch{res.statusCode=500;res.end('{}');}});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();if(!address||typeof address==='string')throw new Error('No fixture port');
 const client=new Stripe('rk_test_'+randomBytes(24).toString('hex'),{host:'127.0.0.1',port:address.port,protocol:'http',apiVersion:STRIPE_API_VERSION,maxNetworkRetries:0,telemetry:false,timeout:5000}),connection={stripe_account_id:fixture.accountId} as StripeConnection,gateway=stripeSdkGateway(connection,client,true);
 try{expect((await gateway.identity()).id).toBe(fixture.accountId);const session=await gateway.createSession(params,'kff-checkout-'+checkoutId);fixture.pay(session.id);expect((await gateway.retrieveSession(session.id)).payment_status).toBe('paid');expect((await gateway.retrieveIntent(fixture.sessions.get(session.id)!.payment_intent as string)).amount_received).toBe(1250);
  expect(observed.every(row=>row.version===STRIPE_API_VERSION)).toBe(true);const sent=observed.find(row=>row.method==='POST')!,form=new URLSearchParams(sent.body);expect(sent.url).toBe('/v1/checkout/sessions');expect(sent.key).toBe('kff-checkout-'+checkoutId);expect(form.get('line_items[0][price_data][unit_amount]')).toBe('1250');expect(form.get('metadata[kff_snapshot_hash]')).toBe(hash);expect(form.get('payment_intent_data[metadata][kff_order_id]')).toBe(orderId);expect(form.get('ui_mode')).toBe('hosted_page');expect(form.get('integration_identifier')).toMatch(/^kff-owned-checkout-[a-z]{8}$/);expect([...form.keys()].some(key=>key.includes('payment_method_types'))).toBe(false);
 }finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}
});
