import {randomUUID,randomBytes} from 'node:crypto';
import {createServer} from 'node:http';
import Stripe from 'stripe';
import {it,expect} from 'vitest';
import {refundInput,financialAdjustmentInput,reverseAdjustmentInput,parseRefundAmount} from '../../packages/contracts/src/refund';
import {stripeRefundSchema,stripeDisputeSchema} from '../../packages/core/src/stripe-financial-contract';
import {stripeFinancialSdkGateway} from '../../packages/core/src/stripe-financial-gateway';
import {STRIPE_API_VERSION} from '../../packages/core/src/stripe-gateway';
import {StripeFinancialFixture} from '../helpers/stripe-financial-fixture';
it('requires exact refund confirmation, version and available amount and rejects client identities and results',()=>{const value={request_id:randomUUID(),expected_version:1,amount_minor:'125',confirmed_available_minor:'2500',reason:'Customer request',provider_reason:'requested_by_customer',confirmation:'REFUND_CONFIRMED_AMOUNT'};expect(refundInput.safeParse(value).success).toBe(true);for(const patch of [{amount_minor:'0'},{amount_minor:'-1'},{amount_minor:1},{amount_minor:'1.00'},{provider_reason:'fraudulent'},{confirmation:'YES'},{expected_version:0},{brand_id:randomUUID()},{provider_refund_id:'re_fake'},{status:'succeeded'},{api_key:'fake'},{currency:'USD'}])expect(refundInput.safeParse({...value,...patch}).success).toBe(false);});
it('converts decimal amounts without floating point and respects zero and three decimal currencies',()=>{expect(parseRefundAmount('10.29',2)).toBe('1029');expect(parseRefundAmount('1250',0)).toBe('1250');expect(parseRefundAmount('0.001',3)).toBe('1');expect(parseRefundAmount('90071992547409.93',2)).toBe('9007199254740993');for(const value of ['0','-1','1e2','01.25','1,250','1.001','.25','NaN'])expect(()=>parseRefundAmount(value,2)).toThrow();expect(()=>parseRefundAmount('1.0',0)).toThrow();expect(()=>parseRefundAmount('9999999999999999999',0)).toThrow();});
it('requires explicit adjustment direction, evidence and separate reversal confirmation',()=>{const value={request_id:randomUUID(),expected_version:1,amount_minor:'500',direction:'DEBIT',currency:'USD',reason:'Confirmed adjustment',evidence_ref:'synthetic-evidence',dispute_id:null,confirmation:'RECORD_ACCOUNTING_ADJUSTMENT'};expect(financialAdjustmentInput.safeParse(value).success).toBe(true);for(const patch of [{evidence_ref:''},{direction:'REFUND'},{amount_minor:'-500'},{currency:'usd'},{reverses_id:randomUUID()},{confirmation:'YES'}])expect(financialAdjustmentInput.safeParse({...value,...patch}).success).toBe(false);expect(reverseAdjustmentInput.safeParse({request_id:randomUUID(),expected_version:2,reason:'Correction',evidence_ref:'reversal',confirmation:'REVERSE_THIS_ADJUSTMENT'}).success).toBe(true);});
it('minimizes refund and dispute provider objects and accepts expanded references and new refund statuses',()=>{const fixture=new StripeFinancialFixture('acct_synthetic',{id:'pi_synthetic',object:'payment_intent',amount:2500,amount_received:2500,currency:'usd',status:'succeeded',livemode:false,metadata:{}}),refund=fixture.addRefund(100);expect(stripeRefundSchema.parse({...refund,charge:{id:refund.charge},metadata:{...refund.metadata,customer_email:'never retain'},customer:'hidden',status:'new_future_status'})).toMatchObject({charge:refund.charge,status:'new_future_status',metadata:{}});expect(stripeRefundSchema.parse(refund)).not.toHaveProperty('livemode');expect(stripeRefundSchema.safeParse({...refund,amount:Number.MAX_SAFE_INTEGER+1}).success).toBe(false);expect(stripeDisputeSchema.parse({...fixture.addDispute(),evidence:{private:'remove'}})).not.toHaveProperty('evidence');});
it('uses the installed Stripe SDK for expanded original payment, refund POST and fully scoped financial lists',async()=>{
 const fixture=new StripeFinancialFixture('acct_synthetic',{id:'pi_synthetic',object:'payment_intent',amount:2500,amount_received:2500,currency:'usd',status:'succeeded',livemode:false,metadata:{}}),dispute=fixture.addDispute(),observed:{method:string;url:string;body:string;version:unknown;key:unknown}[]=[],input:Stripe.RefundCreateParams={payment_intent:'pi_synthetic',amount:125,reason:'requested_by_customer',metadata:{kff_refund_request_id:randomUUID()}};
 const server=createServer(async(req,res)=>{try{let body='';for await(const chunk of req)body+=String(chunk);observed.push({method:req.method!,url:req.url!,body,version:req.headers['stripe-version'],key:req.headers['idempotency-key']});const url=new URL(req.url!,'http://127.0.0.1');res.setHeader('content-type','application/json');let result:unknown;
  if(url.pathname==='/v1/account')result={id:fixture.accountId};else if(url.pathname.startsWith('/v1/payment_intents/'))result=await fixture.retrievePayment('pi_synthetic');else if(req.method==='POST')result=await fixture.createRefund(input,String(req.headers['idempotency-key']));else if(url.pathname==='/v1/refunds')result={object:'list',...(await fixture.listRefunds('pi_synthetic',url.searchParams.get('starting_after')??undefined))};else if(url.pathname==='/v1/disputes')result={object:'list',...(await fixture.listDisputes('pi_synthetic'))};else if(url.pathname.startsWith('/v1/refunds/'))result=await fixture.retrieveRefund(url.pathname.split('/').at(-1)!);else result=await fixture.retrieveDispute(dispute.id);res.end(JSON.stringify(result));
 }catch{res.statusCode=500;res.end('{}');}});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();if(!address||typeof address==='string')throw new Error('Missing local port');const gateway=stripeFinancialSdkGateway(new Stripe('rk_test_'+randomBytes(24).toString('hex'),{host:'127.0.0.1',port:address.port,protocol:'http',apiVersion:STRIPE_API_VERSION,maxNetworkRetries:0,telemetry:false,timeout:5000}),true);
 try{expect(await gateway.identity()).toEqual({id:fixture.accountId});expect((await gateway.retrievePayment('pi_synthetic')).latest_charge?.id).toBe('ch_synthetic');const refund=await gateway.createRefund(input,'kff-refund-synthetic');expect((await gateway.retrieveRefund(refund.id)).id).toBe(refund.id);expect((await gateway.listRefunds('pi_synthetic')).data).toHaveLength(1);await gateway.listRefunds('pi_synthetic',refund.id);expect((await gateway.retrieveDispute(dispute.id)).id).toBe(dispute.id);await gateway.listDisputes('pi_synthetic',dispute.id);
  expect(observed.every(row=>row.version===STRIPE_API_VERSION)).toBe(true);const post=observed.find(row=>row.method==='POST')!,form=new URLSearchParams(post.body);expect(post.url).toBe('/v1/refunds');expect(post.key).toBe('kff-refund-synthetic');expect(form.get('amount')).toBe('125');expect(form.get('payment_intent')).toBe('pi_synthetic');expect(form.get('metadata[kff_refund_request_id]')).toBe((input.metadata as Stripe.MetadataParam).kff_refund_request_id);expect(form.has('refund_application_fee')).toBe(false);const queries=observed.filter(row=>row.method==='GET').map(row=>new URL(row.url,'http://127.0.0.1'));expect(queries.find(url=>url.pathname.startsWith('/v1/payment_intents/'))!.searchParams.get('expand[0]')).toBe('latest_charge');for(const name of ['refunds','disputes']){const url=queries.find(url=>url.pathname==='/v1/'+name&&url.searchParams.has('starting_after'))!;expect(url.searchParams.get('payment_intent')).toBe('pi_synthetic');expect(url.searchParams.get('limit')).toBe('100');}
 }finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}
});
