import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';

test('the workbench sends bounded browser pages through Worker and Agent into the existing lead pool', async ({ page }) => {
  test.setTimeout(120000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', route => new URL(route.request().url()).origin === 'http://127.0.0.1:3000' ? route.continue() : route.abort());
  await page.goto('/acquisition');
  const config = JSON.parse(readFileSync('.kff/local-config.json', 'utf8'));
  await page.getByLabel('密码', { exact: true }).fill(config.operator_password); await page.getByRole('button', { name: '进入工作台' }).click();
  await expect(page.getByRole('heading', { name: '来源与接入状态', includeHidden: true })).toBeAttached();
  const workspace = await (await page.request.get('/api/workspace')).json();
  expect(workspace.live_enabled).toBe(false);
  const agent = workspace.agents.find((row: { is_online: boolean; status: string }) => row.is_online && row.status === 'ONLINE'); expect(agent).toBeTruthy();
  const headers = { Origin: 'http://127.0.0.1:3000' };
  const created = await page.request.post('/api/acquisition/fixtures', { headers, data: { request_id: randomUUID(), platform: 'facebook', agent_id: agent.id } }); expect(created.ok()).toBe(true);
  const fixture = await created.json(), afterCreate = await (await page.request.get('/api/workspace')).json();
  const account = afterCreate.accounts.find((row: { id: string }) => row.id === fixture.account_id);
  const configured = await page.request.post('/api/environments/' + fixture.environment_id + '/configuration', { headers, data: { expected_version: 1, configuration: { driver: 'native', provider_profile_id: null, login_account_id: '900010', operating_identity_id: account.external_id, locale: 'en-US', timezone_id: 'UTC', proxy_ref: null } } }); expect(configured.ok()).toBe(true);
  await page.reload();
  const outer = page.locator('details').filter({ has: page.locator(':scope > summary').filter({ hasText: '自有账号监控与合成验证' }) });
  if ((await outer.getAttribute('open')) === null) await outer.locator(':scope > summary').click();
  const form = page.getByRole('form', { name: '创建获客监控', includeHidden: true });
  const details = page.locator('details').filter({ has: form }).last();
  if ((await details.getAttribute('open')) === null) await details.locator(':scope > summary').click();
  const title = '浏览器采集验收 ' + randomUUID().slice(0, 8);
  await form.getByLabel('采集账号').selectOption(account.id);
  await form.getByLabel('来源类型').selectOption('LOCAL_BROWSER');
  await form.getByLabel('采集环境', { exact: false }).selectOption(fixture.environment_id);
  await form.getByLabel('监控名称').fill(title); await form.getByLabel('关键词（逗号或换行分隔）').fill('consultation');
  await form.locator('[name=target]').fill('owned-fixture-thread'); await form.getByLabel('来源使用依据').fill('本项目编写的合成评论，仅验证本地浏览器采集与入库链路。');
  await form.getByLabel('每页读取上限').fill('2'); await form.getByLabel('每次读取上限').fill('4');
  await form.getByRole('button', { name: '保存监控' }).click(); await expect(page.getByRole('status')).toContainText('监控已保存');
  const state = await (await page.request.get('/api/acquisition')).json(), monitor = state.monitors.find((row: { title: string }) => row.title === title); expect(monitor).toBeTruthy();
  expect(monitor.config.discovery.provider).toBe('LOCAL_BROWSER'); expect(monitor.config.page_size).toBe(2);
  await page.getByLabel('选择监控').selectOption(monitor.id); await page.getByRole('button', { name: '扫描一次', exact: true }).click();
  await expect.poll(async () => { const next = await (await page.request.get('/api/acquisition')).json(); return next.scans.find((row: { monitor_id: string }) => row.monitor_id === monitor.id)?.state; }, { timeout: 60000 }).toBe('COMPLETED');
  await expect.poll(async () => { const next = await (await page.request.get('/api/acquisition')).json(); return next.leads.filter((row: { monitor_id: string }) => row.monitor_id === monitor.id).length; }).toBe(3);
  const finished = await (await page.request.get('/api/acquisition')).json();
  expect(finished.scans.find((row: { monitor_id: string }) => row.monitor_id === monitor.id)).toMatchObject({ returned_count: 4, unique_count: 4 });
  await expect(page.getByRole('table', { name: '获客线索列表' }).getByRole('row')).toHaveCount(4);
  await expect(page.getByRole('table', { name: '获客线索列表' })).toContainText('合成验证');
  await expect.poll(async () => (await (await page.request.get('/api/browser-environments')).json()).find((row: { id: string }) => row.id === fixture.environment_id).browser_status).toBe('CLOSED');
  expect(errors).toEqual([]);
  await page.getByRole('heading', { name: '潜客线索池' }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'output/playwright/browser-collection-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: 'output/playwright/browser-collection-mobile.png' });
});
