import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';

test('configures a native environment, checks it through the Agent, then runs a task in the same managed profile', async ({ page }) => {
  test.setTimeout(90000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', route => new URL(route.request().url()).origin === 'http://127.0.0.1:3000' ? route.continue() : route.abort());
  await page.goto('/environments');
  const config = JSON.parse(readFileSync('.kff/local-config.json', 'utf8'));
  await page.getByLabel('密码', { exact: true }).fill(config.operator_password); await page.getByRole('button', { name: '进入工作台' }).click();
  await expect(page.getByRole('heading', { name: '环境中心', exact: true })).toBeVisible();
  const workspace = await (await page.request.get('/api/workspace')).json();
  expect(workspace.live_enabled).toBe(false);
  const account = workspace.accounts.find((item: { platform: string }) => item.platform === 'kff');
  const agent = workspace.agents.find((item: { is_online: boolean; status: string }) => item.is_online && item.status === 'ONLINE');
  expect(agent).toBeTruthy();
  const name = '矩阵环境验收 ' + randomUUID().slice(0, 8);
  const response = await page.request.post('/api/environments', { headers: { Origin: 'http://127.0.0.1:3000' }, data: { name, account_id: account.id, agent_id: agent.id } }); expect(response.ok()).toBe(true);
  const environment = await response.json();
  await page.reload();
  await page.getByLabel('搜索当前列表').fill(name);
  const details = page.locator('details').filter({ has: page.getByText('配置：' + name, { exact: true }) });
  await details.locator('summary').click(); await details.getByLabel('环境类型').selectOption('native');
  await details.getByRole('button', { name: '保存环境配置' }).click(); await expect(page.getByRole('status')).toContainText('配置已保存');
  const row = page.getByRole('table', { name: '浏览器环境列表' }).getByRole('row').filter({ has: page.getByText(name, { exact: true }) });
  await row.getByRole('button', { name: '检查浏览器' }).click();
  await expect(row).toContainText('环境检查', { timeout: 40000 });
  await expect(page.getByRole('status')).toContainText('环境检查完成，浏览器已确认关闭');
  await expect(row).toContainText('登录状态：尚未核验'); await expect(row).toContainText('已关闭');
  const capability = workspace.capabilities.find((item: { account_id: string; capability_key: string }) => item.account_id === account.id && item.capability_key === 'kff.fixture.page.read.browser');
  const created = await page.request.post('/api/tasks', { headers: { Origin: 'http://127.0.0.1:3000' }, data: { title: name + ' 同环境任务', account_id: account.id, environment_id: environment.id, capability_id: capability.id, mode: 'TEST_ONLY', body: '', fixture_scenario: 'normal', idempotency_key: randomUUID() } }); expect(created.ok()).toBe(true);
  const task = await created.json(); expect(task.snapshot.browser_environment.profile_key).toBe(environment.profile_key);
  const approved = await page.request.post('/api/tasks/' + task.id + '/approval-decisions', { headers: { Origin: 'http://127.0.0.1:3000' }, data: { snapshot_hash: task.snapshot_hash, decision: 'APPROVED' } }); expect(approved.ok()).toBe(true);
  const queued = await page.request.post('/api/tasks/' + task.id + '/runs', { headers: { Origin: 'http://127.0.0.1:3000' }, data: {} }); expect(queued.ok()).toBe(true);
  const run = await queued.json();
  await expect.poll(async () => (await (await page.request.get('/api/runs/' + run.id)).json()).run.action_state, { timeout: 30000 }).toBe('VERIFIED_SUCCEEDED');
  await expect.poll(async () => (await (await page.request.get('/api/browser-environments')).json()).find((item: { id: string }) => item.id === environment.id).browser_status).toBe('CLOSED');
  await expect(row).toContainText('已关闭');
  await expect(row.getByRole('button', { name: '检查浏览器' })).toBeEnabled();
  expect(errors).toEqual([]);
  await page.getByRole('heading', { name: '环境中心', exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: 'output/playwright/browser-environments-desktop.png' });
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: 'output/playwright/browser-environments-mobile.png' });
});
