import {test,expect,type Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {spawn} from 'node:child_process';
const origin='http://127.0.0.1:3000';
test.use({actionTimeout:10000});
async function login(page:Page){await page.context().route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());await page.goto('/inbox');const config=JSON.parse(readFileSync('.kff/local-config.json','utf8'));await page.getByLabel('密码',{exact:true}).fill(config.operator_password);await page.getByRole('button',{name:'进入工作台'}).click();await expect(page.getByRole('heading',{name:'客户收件箱',exact:true})).toBeVisible();}
async function post(page:Page,path:string,body:unknown){const response=await page.request.post('/api/'+path,{headers:{Origin:origin},data:body});expect(response.ok(),path+' HTTP '+response.status()).toBe(true);return response.json();}
async function fixture(page:Page,automatic:boolean,agent?:string){const workspace=await(await page.request.get('/api/workspace')).json(),pageId=BigInt('0x'+randomUUID().replaceAll('-','')).toString(),row=await post(page,'facebook/fixtures',{request_id:randomUUID(),name:'Lead browser '+pageId.slice(-6),page_id:pageId,agent_id:agent??workspace.agents.find((row:{name:string})=>row.name==='本机开发 Agent').id});await post(page,'facebook/connections',{request_id:randomUUID(),...row,expected_version:0,state:'ACTIVE',auto_reply:automatic,reply_window_hours:24,policy_ref:'kff.local.browser.service-window.v1'});return {...row,page:pageId};}
async function inbound(page:Page,account:{account_id:string;page:string},body:string,sender='987654321'){return post(page,'facebook/fixtures/'+account.account_id+'/events',{event_id:'browser_'+randomUUID(),page_id:account.page,sender_id:sender,body,kind:'MESSAGE',display_name:'Facebook 浏览器客户',occurred_at:new Date().toISOString(),has_attachment:false,source:{kind:'MESSENGER',page_id:account.page,source_id:'browser_source',ref:'browser_campaign',ad_id:null}});}
test('Facebook settings, automatic reception, WhatsApp confirmation, customer tags and metrics persist in the real browser',async({page})=>{
  test.setTimeout(90000);await login(page);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.getByText('Facebook 账号与接待',{exact:false}).first().click();await page.getByText('添加本地合成 Facebook 账号',{exact:true}).click();const create=page.getByRole('form',{name:'新增合成 Facebook 账号'}),name='UI Page '+randomUUID().slice(0,6),pageId=BigInt('0x'+randomUUID().replaceAll('-','')).toString();await create.getByLabel('账号名称',{exact:true}).fill(name);await create.getByLabel('合成 Page ID',{exact:true}).fill(pageId);const response=page.waitForResponse(r=>r.url().endsWith('/api/facebook/fixtures')&&r.request().method()==='POST');await create.getByRole('button',{name:'创建合成账号'}).click();const account=await(await response).json();const config=page.getByRole('form',{name:'Facebook 接待配置'});await config.getByLabel('自动接待新私信').check();await config.getByRole('button',{name:'保存 Facebook 接待配置'}).click();await expect(page.getByRole('form',{name:'模拟 Facebook 客户'})).toBeVisible();
  await page.getByText('WhatsApp 号码与引流话术',{exact:true}).click();await page.getByLabel('号码适用范围').selectOption(account.account_id);const wa=page.getByRole('form',{name:'WhatsApp 引流配置'});await wa.getByLabel('WhatsApp 国际号码',{exact:true}).fill('15550009999');await wa.getByRole('button',{name:'保存 WhatsApp 配置'}).click();await expect(page.getByRole('status')).toContainText('WhatsApp 目的地和话术已保存');
  const simulated=page.getByRole('form',{name:'模拟 Facebook 客户'});const receipt=page.waitForResponse(r=>r.url().includes('/events')&&r.request().method()==='POST');await simulated.getByRole('button',{name:'提交模拟互动'}).click();const lead=await(await receipt).json();await page.goto('/inbox?conversation='+lead.conversation_id);const panel=page.getByRole('region',{name:'会话详情'});await expect(panel.getByRole('list',{name:'已保存的客户消息'})).toContainText('https://wa.me/15550009999',{timeout:30000});await expect(panel.getByLabel('接待控制')).toContainText('暂停接待');await expect(panel).toContainText('自动接待 · 已确认发送');
  const result=page.getByRole('form',{name:'记录 WhatsApp 客户结果'});await result.getByLabel('核实依据').fill('本地合成验证：销售确认收到此测试客户');await result.getByRole('button',{name:'保存引流结果'}).click();await expect(panel).toContainText('人工确认已联系');await page.reload();await expect(panel).toContainText('已交销售跟进');await panel.screenshot({path:'output/playwright/facebook-whatsapp-conversation.png'});
  await panel.getByRole('link',{name:'客户档案 →'}).click();const profile=page.getByRole('region',{name:'客户详情'});await expect(profile).toContainText('Facebook 私信');await expect(profile).toContainText('本地浏览器验证');const intent=page.getByRole('form',{name:'编辑客户意向'});await intent.getByLabel('客户标签（逗号分隔）').fill('重点客户, 浏览器验证');await intent.getByLabel('判断依据').fill('销售核实需求并记录跟进');await intent.getByRole('button',{name:'保存客户意向'}).click();await expect(intent.getByLabel('客户标签（逗号分隔）')).toHaveValue('重点客户, 浏览器验证');await page.reload();await expect(intent.getByLabel('客户标签（逗号分隔）')).toHaveValue('重点客户, 浏览器验证');
  await page.goto('/lead-analytics');await page.getByRole('combobox',{name:'Facebook 账号',exact:true}).selectOption(account.account_id);await page.getByRole('button',{name:'刷新引流统计'}).click();await expect(page.locator('.lead-conversion')).toContainText('100.0%');await expect(page.getByRole('region',{name:'引流操作日志'})).toContainText('whatsapp.result_recorded');await page.screenshot({path:'output/playwright/facebook-lead-analytics.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.goto('/inbox?conversation='+lead.conversation_id);await expect(panel).toContainText('已交销售跟进');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await panel.screenshot({path:'output/playwright/facebook-reception-mobile.png'});expect(errors).toEqual([]);
});
test('human reply remains one task when the acknowledgement is lost and the user retries after refresh',async({page})=>{await login(page);const account=await fixture(page,false),lead=await inbound(page,account,'Hello, I need a person');await page.goto('/inbox?conversation='+lead.conversation_id);const form=page.getByRole('form',{name:'人工回复'});await form.getByLabel('回复内容',{exact:true}).fill('Browser human reply '+randomUUID().slice(0,6));let aborted=false;await page.route('**/api/conversations/'+lead.conversation_id+'/replies',async route=>{if(!aborted){aborted=true;await route.fetch();await route.abort('failed');}else await route.continue();});await form.getByRole('button',{name:'接管并发送回复'}).click();await expect(page.getByLabel('接待控制').getByRole('alert')).toContainText('暂未收到保存确认');await expect(page.getByRole('list',{name:'已保存的客户消息'})).toContainText('Browser human reply',{timeout:30000});await form.getByRole('button',{name:'接管并发送回复'}).click();await expect(page.getByRole('status')).toContainText('人工回复已入队');const reception=await(await page.request.get('/api/conversations/'+lead.conversation_id+'/reception')).json();expect(reception.replies).toHaveLength(1);await page.reload();await expect(page.getByRole('list',{name:'已保存的客户消息'}).locator('li.outgoing')).toHaveCount(1);});
test('a second real local Agent process executes only its bound account using its own journal',async({page})=>{test.setTimeout(90000);await login(page);const paired=await post(page,'agents',{name:'Browser second Agent '+randomUUID().slice(0,6)});mkdirSync('.kff/browser-agents',{recursive:true});const file='.kff/browser-agents/'+paired.agent.id+'.json';writeFileSync(file,JSON.stringify(paired.configuration),{mode:0o600});const child=spawn(process.execPath,['--import','tsx','apps/agent/src/main.ts'],{cwd:process.cwd(),env:{...process.env,KFF_ROOT:process.cwd(),KFF_AGENT_CONFIG_FILE:file,KFF_APP_ORIGIN:origin},windowsHide:true,stdio:'ignore'});try{await expect.poll(async()=>{const data=await(await page.request.get('/api/workspace')).json();return data.agents.find((row:{id:string})=>row.id===paired.agent.id)?.is_online;}).toBe(true);const account=await fixture(page,false,paired.agent.id),lead=await inbound(page,account,'Please help');await post(page,'conversations/'+lead.conversation_id+'/replies',{request_id:randomUUID(),expected_version:1,body:'Bound second Agent message',refer_whatsapp:false,fixture_scenario:'normal'});await expect.poll(async()=>{const data=await(await page.request.get('/api/conversations/'+lead.conversation_id+'/reception')).json();return data.replies[0]?.state;},{timeout:30000}).toBe('VERIFIED_SUCCEEDED');const journal=JSON.parse(readFileSync('.kff/agent-instances/'+paired.agent.id+'/agent/journal.json','utf8'));expect(Object.keys(journal)).toHaveLength(1);const row=Object.values(journal)[0] as {quiesced:boolean};await expect.poll(()=>JSON.parse(readFileSync('.kff/agent-instances/'+paired.agent.id+'/agent/journal.json','utf8'))[Object.keys(journal)[0]].quiesced).toBe(true);expect(row).toBeTruthy();}finally{await post(page,'agents/'+paired.agent.id+'/control',{action:'DRAIN',reason:'Local multi-agent browser verification complete'});if(child.exitCode===null){const done=new Promise<void>(resolve=>child.once('exit',()=>resolve()));child.kill();await done;}}});
