import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
const origin='http://127.0.0.1:3000';
function fixture(...args:string[]){return JSON.parse(execFileSync(process.execPath,['--import','tsx','tests/helpers/payment-ui-fixture.ts',...args],{encoding:'utf8',windowsHide:true,env:{...process.env,KFF_LOCAL_PAYMENT_UI_FIXTURE:'1',KFF_ENABLE_LIVE:'false'}}).trim());}
test('creates and reviews a Stripe checkout, shows test receipts separately and keeps the return page private',async({page,context})=>{
 const prepared=fixture('prepare');await page.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());await page.goto('/orders?order='+prepared.order_id);const config=JSON.parse(readFileSync('.kff/local-config.json','utf8'));await page.getByLabel('密码',{exact:true}).fill(config.operator_password);await page.getByRole('button',{name:'进入工作台'}).click();
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});const panel=page.getByRole('region',{name:'Stripe 订单支付'}),form=page.getByRole('form',{name:'创建 Stripe 支付'});await form.getByLabel('收款连接',{exact:true}).selectOption(prepared.connection_id);await form.getByRole('checkbox').check();await form.getByRole('button',{name:'生成 Stripe 支付链接'}).click();await expect(panel).toContainText('等待创建');
 const paymentData=await (await page.request.get('/api/payments?order='+prepared.order_id)).json(),id=paymentData.checkouts[0].id;fixture('open',id);await panel.getByRole('button',{name:'刷新支付状态'}).click();await expect(panel).toContainText('等待客户付款');await expect(panel.getByRole('link',{name:'打开 Stripe 收银台'})).toHaveAttribute('href',/^https:\/\/checkout\.stripe\.com\/c\/pay\/cs_test_/);await expect(page.getByRole('form',{name:'取消订单',exact:true})).toHaveCount(0);
 fixture('paid',id);await panel.getByRole('button',{name:'刷新支付状态'}).click();await expect(panel).toContainText('测试支付已核实');await expect(panel).toContainText('测试记录，不计入真实收入');const detail=await (await page.request.get('/api/orders/'+prepared.order_id)).json();expect(detail.verified_revenue).toBe(false);expect(detail.order.snapshot.total_minor).toBe('2500');
  await page.screenshot({path:'output/playwright/stripe-test-payment.png',fullPage:true});await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'output/playwright/stripe-payment-mobile.png',fullPage:true});
  await page.goto('/customers?customer='+detail.order.customer_id);await expect(page.getByText('真实付款 0 笔 · 测试记录 1 笔')).toBeVisible();
 const anonymous=await context.browser()!.newContext();const returned=await anonymous.newPage();await returned.goto(origin+'/payment-return?session_id=cs_forged&order='+prepared.order_id);await expect(returned.getByRole('heading',{name:'支付进度正在核对'})).toBeVisible();await expect(returned.locator('body')).not.toContainText('支付界面合成客户');await anonymous.close();expect(errors).toEqual([]);
});
