import {test,expect} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {readFileSync} from 'node:fs';
const origin='http://127.0.0.1:3000';
function fixture(file:string,...args:string[]){return JSON.parse(execFileSync(process.execPath,['--import','tsx','tests/helpers/'+file+'-ui-fixture.ts',...args],{encoding:'utf8',windowsHide:true,env:{...process.env,KFF_LOCAL_PAYMENT_UI_FIXTURE:'1',KFF_LOCAL_REFUND_UI_FIXTURE:'1',KFF_ENABLE_LIVE:'false'}}).trim());}
test('reviews partial refunds, pending holds, cancellation and immutable accounting corrections on desktop and mobile',async({page})=>{
 const order=fixture('payment','prepare'),prepared=fixture('refund','prepare',order.order_id,order.connection_id);await page.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());await page.goto('/orders?order='+order.order_id);const config=JSON.parse(readFileSync('.kff/local-config.json','utf8'));await page.getByLabel('密码',{exact:true}).fill(config.operator_password);await page.getByRole('button',{name:'进入工作台'}).click();
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});const panel=page.getByRole('region',{name:'退款与调整'}),form=panel.getByRole('form',{name:'申请退款',exact:true});await expect(panel).toContainText('不计真实收退款');await expect(panel.locator('.refund-summary')).toContainText('USD 25.00');
 await form.getByLabel('USD 退款金额').fill('10.29');await form.getByLabel('处理依据',{exact:true}).fill('合成客户申请部分退款');await form.getByRole('checkbox').check();await form.getByRole('button',{name:'确认退款申请'}).click();await expect(panel).toContainText('等待提交 · USD 10.29');let data=await (await page.request.get('/api/payments/'+prepared.payment_id+'/financials')).json();expect(data.reserved_minor).toBe('1029');expect(data.available_minor).toBe('1471');
 fixture('refund','process',prepared.payment_id);await panel.getByRole('button',{name:'刷新退款记录'}).click();await expect(panel).toContainText('退款处理中 · USD 10.29');fixture('refund','succeeded',prepared.payment_id);await panel.getByRole('button',{name:'刷新退款记录'}).click();await expect(panel).toContainText('退款已核实 · USD 10.29');
 await form.getByLabel('USD 退款金额').fill('1.00');await form.getByLabel('处理依据',{exact:true}).fill('合成未提交撤销检查');await form.getByRole('checkbox').check();await form.getByRole('button',{name:'确认退款申请'}).click();const cancel=panel.getByRole('form',{name:'撤销未提交申请'});await cancel.getByLabel('处理原因',{exact:true}).fill('客户在提交前撤回');await cancel.getByRole('button',{name:'撤销未提交申请'}).click();await expect(panel).toContainText('已取消 · USD 1.00');
 await panel.getByText('人工账目调整（0）',{exact:true}).click();const adjustment=panel.getByRole('form',{name:'记录账目调整',exact:true});await adjustment.getByLabel('USD 调整金额').fill('1.50');await adjustment.getByLabel('调整原因',{exact:true}).fill('合成对账调整');await adjustment.getByLabel('唯一依据标识').fill('browser-evidence-'+prepared.payment_id);await adjustment.getByRole('checkbox').check();await adjustment.getByRole('button',{name:'保存账目调整'}).click();await expect(panel).toContainText('当前调整净额：USD -1.50');const reverse=panel.getByRole('form',{name:'冲销此调整'});await reverse.getByLabel('处理原因',{exact:true}).fill('合成依据更正');await reverse.getByLabel('冲销依据标识').fill('browser-reversal-'+prepared.payment_id);await reverse.getByRole('button',{name:'冲销此调整'}).click();await expect(panel).toContainText('已冲销，原记录保留');await expect(panel).toContainText('当前调整净额：USD 0.00');
 data=await (await page.request.get('/api/payments/'+prepared.payment_id+'/financials')).json();expect(data.refunded_minor).toBe('1029');expect(data.net_after_refunds_minor).toBe('1471');expect(data.adjustments).toHaveLength(2);expect(data.postings).toHaveLength(1);await page.screenshot({path:'output/playwright/stripe-refunds.png',fullPage:true});await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'output/playwright/stripe-refunds-mobile.png',fullPage:true});expect(errors).toEqual([]);fixture('refund','finish',prepared.payment_id);
});
