import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
const date=(offset:number)=>new Date(Date.now()+offset*86400000).toISOString().slice(0,10);
test('previews both repeated instants, revises a paused plan and prepares only bounded points before stopping the future',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.route('**/*',route=>new URL(route.request().url()).origin==='http://127.0.0.1:3000'?route.continue():route.abort());
  await page.goto('/schedules');const config=JSON.parse(readFileSync('.kff/local-config.json','utf8'));await page.getByLabel('密码',{exact:true}).fill(config.operator_password);await page.getByRole('button',{name:'进入工作台'}).click();await expect(page.getByRole('heading',{name:'计划与时区',exact:true})).toBeVisible();
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});const title='Schedule '+randomUUID().slice(0,8);await page.getByText('创建计划规则',{exact:true}).click();const form=page.getByRole('form',{name:'计划规则表单'});
  await form.getByLabel('计划名称',{exact:true}).fill(title);await form.getByLabel('IANA 时区',{exact:true}).fill('America/New_York');await form.getByLabel('开始日期',{exact:true}).fill('2024-11-03');await form.getByLabel('当地时刻',{exact:true}).fill('01:30');await form.getByLabel('夏令时重复时刻',{exact:true}).selectOption('BOTH');await form.getByLabel('错过时点策略',{exact:true}).selectOption('CATCH_UP');await form.getByLabel('最迟准备期限（秒）',{exact:true}).fill('604800');await form.getByLabel('正常延迟容限（秒）',{exact:true}).fill('0');await form.getByLabel('模拟恢复时间（UTC，可选）',{exact:true}).fill('2024-11-03T07:00');await form.getByRole('button',{name:'预览规则与 UTC 日历'}).click();
  const preview=page.getByRole('region',{name:'计划规则预览'});await expect(preview).toContainText('可准备 2 个，跳过 0 个');await expect(preview).toContainText('2024-11-03T05:30:00.000Z');await expect(preview).toContainText('2024-11-03T06:30:00.000Z');await preview.screenshot({path:'output/playwright/schedule-dst-preview.png'});
  await preview.getByLabel('已核对当地时间、UTC 时点及错过策略').check();await preview.getByRole('button',{name:'确认并保存暂停计划'}).click();const detail=page.getByRole('region',{name:'计划详情'});await expect(detail).toContainText(title);await expect(detail).toContainText('已暂停');
  await detail.getByRole('button',{name:'调整此计划规则'}).click();await form.getByLabel('IANA 时区',{exact:true}).fill('UTC');await form.getByLabel('重复规则',{exact:true}).selectOption('DAILY');await form.getByLabel('开始日期',{exact:true}).fill(date(-3));await form.getByLabel('结束日期',{exact:true}).fill(date(1));await form.getByLabel('当地时刻',{exact:true}).fill('00:00');await form.getByLabel('夏令时重复时刻',{exact:true}).selectOption('EARLIER');await form.getByRole('button',{name:'预览规则与 UTC 日历'}).click();await expect(preview).toContainText('可准备 2 个，跳过 2 个');await preview.getByLabel('调整规则原因',{exact:true}).fill('本地合成测试新规则版本');await preview.getByLabel('已核对当地时间、UTC 时点及错过策略').check();await preview.getByRole('button',{name:'确认并保存暂停计划'}).click();await expect(detail.getByLabel('查看规则版本',{exact:true}).locator('option')).toHaveCount(2);
  await detail.getByLabel('计划控制原因',{exact:true}).fill('合成计划验证限量补准备');await detail.getByRole('button',{name:'开始或恢复时点准备'}).click();await expect(detail).toContainText('待建任务 2 个，跳过 2 个，已取消 0 个。');
  await detail.getByLabel('计划控制原因',{exact:true}).fill('核对时点后暂停后续准备');await detail.getByRole('button',{name:'暂停时点准备'}).click();await expect(detail).toContainText('已暂停');
  const list=await (await page.request.get('/api/schedules')).json();const saved=list.find((row:{title:string})=>row.title===title);const persisted=await (await page.request.get('/api/schedules/'+saved.id)).json();expect(persisted.versions).toHaveLength(2);expect(persisted.versions[1].definition.slots).toHaveLength(2);expect(persisted.execution_authorized).toBe(false);
  await detail.screenshot({path:'output/playwright/schedule-paused.png'});await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'output/playwright/schedule-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});
  await detail.getByLabel('计划控制原因',{exact:true}).fill('结束合成测试并终止未来计划');await detail.getByRole('button',{name:'终止未来计划'}).click();await expect(detail).toContainText('已终止');await expect(detail).toContainText('待建任务 0 个，跳过 2 个，已取消 2 个。');expect(errors).toEqual([]);
});
