import {test,expect,type Page} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {parse} from 'csv-parse/sync';

async function post(page:Page,path:string,body:unknown){const response=await page.request.post('/api/'+path,{headers:{Origin:'http://127.0.0.1:3000'},data:body});expect(response.ok()).toBe(true);return response.json();}
test('freezes current-page, cross-page manual and all-filtered targets and exports the original selection after filters change',async({page})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.route('**/*',route=>new URL(route.request().url()).origin==='http://127.0.0.1:3000'?route.continue():route.abort());
  await page.goto('/collections');const config=JSON.parse(readFileSync('.kff/local-config.json','utf8'));await page.getByLabel('密码',{exact:true}).fill(config.operator_password);await page.getByRole('button',{name:'进入工作台'}).click();await expect(page.getByRole('heading',{name:'查询与结果',exact:true})).toBeVisible();
  const workspace=await (await page.request.get('/api/workspace')).json();const account=workspace.accounts.find((item:{is_synthetic:boolean})=>item.is_synthetic);const title='Target selection '+randomUUID().slice(0,8);
  const metadata={request_id:randomUUID(),account_id:account.id,title,filename:'targets.csv',format:'csv',encoding:'utf-8',source_namespace:'targets-'+randomUUID().slice(0,8),source_description:'Owned browser target fixture records',processing_basis:'Repository synthetic data for verification',purpose:'data_review',export_fields:['message'],original_access:'owner_admin',original_retention_days:7,retention_days:7,display_timezone:'UTC'};
  const upload=await page.request.post('/api/imports',{headers:{Origin:'http://127.0.0.1:3000','Content-Type':'application/octet-stream','x-kff-import-metadata':encodeURIComponent(JSON.stringify(metadata))},data:Buffer.from('source_object_id,message\n'+Array.from({length:32},(_,index)=>'000'+String(index+1).padStart(2,'0')+','+(index%2?'Other':'Match')).join('\n'))});expect(upload.ok()).toBe(true);const file=await upload.json();
  const mapped=await post(page,'imports/'+file.id+'/previews',{request_id:randomUUID(),sheet:0,header_row:1,source_object_id:0,fields:{message:1},kind_columns:{},text_encoding:'plain'});
  const imported=await post(page,'imports/'+file.id+'/confirmations',{request_id:randomUUID(),preview_id:mapped.id,preview_hash:mapped.preview_hash,excluded_error_rows:0,confirm_valid_rows:true});
  await page.getByRole('button',{name:title,exact:true}).click();const collection=page.getByRole('region',{name:'采集查询详情'});const targets=collection.getByRole('region',{name:'精确目标快照'});
  await expect(collection).toContainText('筛选匹配 32 个对象，本页显示 25 个');await targets.getByRole('button',{name:'预览目标范围'}).click();const preview=page.locator('[aria-label="目标范围预览"]');await expect(preview).toContainText('纳入 25 个，排除 0 个');
  async function save(name:string,count:number){await preview.getByLabel('目标快照名称',{exact:true}).fill(name);await preview.getByLabel('我已核对这 '+count+' 个对象及纳入、排除原因。',{exact:true}).check();await preview.getByRole('button',{name:'确认并保存目标快照'}).click();await expect(page.locator('[aria-label="已保存目标快照"]')).toContainText('固定 '+count+' 个纳入对象');}
  await save('Current page '+title,25);
  await collection.getByLabel('手选 00001',{exact:true}).check();await collection.getByRole('button',{name:'下一页结果',exact:true}).click();await expect(collection.getByLabel('手选 00032',{exact:true})).toBeVisible();await collection.getByLabel('手选 00032',{exact:true}).check();
  await targets.getByLabel('目标选择范围',{exact:true}).selectOption('MANUAL');await targets.getByRole('button',{name:'预览目标范围'}).click();await expect(preview).toContainText('纳入 2 个，排除 0 个');await expect(preview).toContainText('00001');await expect(preview).toContainText('00032');await save('Manual '+title,2);
  await collection.getByText('筛选查询结果',{exact:true}).click();await collection.getByLabel('正文包含',{exact:true}).fill('Match');await collection.getByRole('button',{name:'应用筛选',exact:true}).click();await expect(collection).toContainText('筛选匹配 16 个对象，本页显示 16 个');await expect(targets).toContainText('手选 0 个');
  await targets.getByLabel('目标选择范围',{exact:true}).selectOption('ALL_FILTERED');await targets.getByRole('button',{name:'预览目标范围'}).click();await expect(preview).toContainText('纳入 16 个，排除 0 个');await save('All filtered '+title,16);
  await collection.getByText('筛选查询结果',{exact:true}).click();await collection.getByLabel('对象 ID 前缀',{exact:true}).fill('00001');await collection.getByRole('button',{name:'应用筛选',exact:true}).click();await expect(collection).toContainText('筛选匹配 1 个对象，本页显示 1 个');
  await targets.getByRole('button',{name:new RegExp('All filtered '+title+' · 纳入')}).click();const detail=page.locator('[aria-label="已保存目标快照"]');await expect(detail).toContainText('固定 16 个纳入对象');
  const downloading=page.waitForEvent('download');await detail.getByRole('button',{name:'导出固定快照 CSV',exact:true}).click();const downloaded=await downloading;await downloaded.saveAs('.kff/browser-target-snapshot.csv');const records=parse(readFileSync('.kff/browser-target-snapshot.csv','utf8'),{bom:true,columns:true}) as {source_object_id:string}[];expect(records).toHaveLength(16);expect(records.map(row=>row.source_object_id)).toContain("'00031");
  await targets.screenshot({path:'output/playwright/target-snapshots.png'});await page.setViewportSize({width:390,height:844});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'output/playwright/target-snapshots-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});
  await detail.getByLabel('撤销快照原因',{exact:true}).fill('合成测试撤销固定目标范围');await detail.getByRole('button',{name:'撤销此目标快照'}).click();await expect(targets).toContainText('快照已撤销，后续使用已阻止。');await expect(detail.getByRole('button',{name:'导出固定快照 CSV',exact:true})).toBeDisabled();
  const snapshots=await (await page.request.get('/api/collections/'+imported.query_id+'/target-snapshots')).json();const frozen=snapshots.find((row:{title:string})=>row.title==='All filtered '+title);expect(frozen.state).toBe('REVOKED');const rejected=await page.request.post('/api/collections/'+imported.query_id+'/exports',{headers:{Origin:'http://127.0.0.1:3000'},data:{format:'csv',fields:['message'],target_snapshot_id:frozen.id}});expect(rejected.status()).toBe(409);
  await targets.getByLabel('目标选择范围',{exact:true}).selectOption('ALL_FILTERED');await targets.getByLabel('本次目标用途',{exact:true}).selectOption('marketing');await targets.getByRole('button',{name:'预览目标范围'}).click();await expect(preview).toContainText('纳入 0 个，排除 1 个');await expect(preview).toContainText('来源未允许此用途');
  expect(errors).toEqual([]);
});
