import { test, expect, type Page } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { execFileSync } from 'node:child_process';

test.describe.configure({ mode: 'serial' });
test.beforeEach(async ({ page }) => {
  await page.route('**/*', route => new URL(route.request().url()).origin === 'http://127.0.0.1:3000' ? route.continue() : route.abort());
  await page.goto('/tasks');
  const config = JSON.parse(readFileSync('.kff/local-config.json', 'utf8'));
  await page.getByLabel('密码', { exact: true }).fill(config.operator_password);
  await page.getByRole('button', { name: '进入工作台' }).click();
  await expect(page.getByRole('heading', { name: '任务工作台', exact: true })).toBeVisible();
  const workspace = await (await page.request.get('/api/workspace')).json();
  expect(workspace.live_enabled).toBe(false);
});
async function createAndRun(page: Page, scenario: string) {
  const title = 'E1 浏览器测试 ' + scenario + ' ' + randomUUID().slice(0, 8);
  await page.getByRole('button', { name: '创建任务', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: '创建任务', exact: true });
  await dialog.getByLabel('任务名称', { exact: true }).fill(title);
  await dialog.getByLabel('发布内容', { exact: false }).fill('合成内容\n此测试不向 Facebook 发送内容。');
  await dialog.getByText('本地故障验证场景', { exact: true }).click();
  await dialog.getByLabel('场景', { exact: true }).selectOption(scenario);
  await dialog.getByRole('button', { name: '保存草稿' }).click();
  const row = page.getByRole('row').filter({ has: page.getByRole('button', { name: title, exact: true }) });
  await row.getByRole('button', { name: '审核', exact: true }).click();
  await page.getByRole('dialog', { name: '核对任务', exact: true }).getByRole('button', { name: '审核通过', exact: true }).click();
  await row.getByRole('button', { name: '执行', exact: true }).click();
  return { title, row };
}
test('creates, approves and verifies one durable local publication', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const { title, row } = await createAndRun(page, 'normal');
  await expect(row.getByText('核实成功', { exact: true })).toBeVisible({ timeout: 30000 });
  await page.getByRole('link', { name: '运行记录', exact: true }).click();
  await page.getByRole('button', { name: title, exact: true }).click();
  const detail = page.getByRole('dialog', { name: '运行详情', exact: true });
  await expect(detail.getByText('已取得结果证据', { exact: true })).toBeVisible();
  const downloadEvent = page.waitForEvent('download');
  await detail.getByRole('button', { name: '下载', exact: true }).click();
  const download = await downloadEvent; expect(download.suggestedFilename()).toMatch(/^kff-diagnostic-/);
  const downloadedPath = await download.path(); const manifest = JSON.parse(readFileSync(downloadedPath!, 'utf8'));
  expect(manifest.schema_version).toBe('kff.diagnostic.v2'); expect(manifest.duration_ms).toBeGreaterThanOrEqual(0);
  expect(manifest.executor_version).toContain('kff-agent-'); expect(manifest.adapter_version).toBe('fixture-page-v1');
  expect(manifest.outcome).toBe('VERIFIED_SUCCEEDED');
  expect(errors).toEqual([]);
  await page.screenshot({ path: 'output/playwright/e1-verified-detail.png', fullPage: true });
});
test('records a wrong-account failure with a diagnostic and no publication', async ({ page }) => {
  const { title, row } = await createAndRun(page, 'wrong_account');
  await expect(row.getByText('执行失败', { exact: true })).toBeVisible({ timeout: 30000 });
  await page.getByRole('link', { name: '运行记录', exact: true }).click();
  await page.getByRole('button', { name: title, exact: true }).click();
  const detail = page.getByRole('dialog', { name: '运行详情', exact: true });
  await expect(detail.getByText('ACCOUNT_MISMATCH', { exact: true })).toBeVisible();
  await expect(detail.getByText('D1 · 脱敏诊断包', { exact: true })).toBeVisible();
  await expect(detail.getByText('已记录提交意图', { exact: true })).toHaveCount(0);
});
test('stops preparation before a publication and displays cancellation', async ({ page }) => {
  const { title } = await createAndRun(page, 'slow');
  await page.getByRole('link', { name: '运行记录', exact: true }).click();
  const row = page.getByRole('row').filter({ has: page.getByRole('button', { name: title, exact: true }) });
  await expect(row.getByText('准备中', { exact: true })).toBeVisible();
  await row.getByRole('button', { name: '停止', exact: true }).click();
  await expect(row.getByText('已取消', { exact: true })).toBeVisible({ timeout: 30000 });
});
test('reconciles an unknown publication and then releases the quarantined environment', async ({ page }) => {
  const { title, row } = await createAndRun(page, 'lost_after_submit');
  await expect(row.getByText('需人工处理', { exact: true })).toBeVisible({ timeout: 30000 });
  await page.getByRole('link', { name: '运行记录', exact: true }).click();
  await page.getByRole('button', { name: title, exact: true }).click();
  const detail = page.getByRole('dialog', { name: '运行详情', exact: true });
  await expect(detail.getByText('结果未知', { exact: true })).toBeVisible();
  await detail.getByRole('button', { name: '核验原提交', exact: true }).click();
  await expect(detail.getByText('核实成功', { exact: true }).first()).toBeVisible();
  await detail.getByRole('button', { name: '解除环境隔离', exact: true }).click();
  await expect(page.getByRole('status').getByText('已解除隔离', { exact: true })).toBeVisible();
  await expect(detail.getByText('执行尝试 1', { exact: true })).toBeVisible();
  await expect(detail.getByText('执行尝试 2', { exact: true })).toHaveCount(0);
  await page.screenshot({ path: 'output/playwright/e1-reconciled-detail.png', fullPage: true });
});
test('all six workspace pages stay usable at desktop and narrow widths', async ({ page }) => {
  for (const [section, title] of [['overview', '执行总览'], ['accounts', '账号中心'], ['environments', '环境中心'], ['tasks', '任务工作台'], ['runs', '运行记录'], ['capabilities', '能力与验证']]) {
    await page.goto('/' + section); await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible();
    expect(await page.locator('body').innerText()).not.toContain('Internal Server Error');
  }
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto('/tasks');
  await expect(page.getByRole('button', { name: '创建任务', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'output/playwright/workbench-mobile.png', fullPage: true });
});
test('organization, account and Agent pause controls reflect the stored state', async ({ page }) => {
  await page.getByRole('button', { name: '暂停整个组织', exact: true }).click();
  await expect(page.getByText('组织已暂停新动作，已提交的结果继续核实。', { exact: true })).toBeVisible();
  expect((await (await page.request.get('/api/workspace')).json()).organization.outbound_paused).toBe(true);
  await page.getByRole('button', { name: '恢复组织调度', exact: true }).click();
  await expect(page.getByRole('button', { name: '暂停整个组织', exact: true })).toBeVisible();
  await page.getByRole('link', { name: '账号中心', exact: true }).click();
  const account = page.getByRole('row').filter({ hasText: '本地验证主页' });
  await account.getByRole('button', { name: '暂停账号', exact: true }).click();
  await expect(account.getByText('已暂停新动作', { exact: true })).toBeVisible();
  await account.getByRole('button', { name: '恢复账号', exact: true }).click();
  await expect(account.getByText('已暂停新动作', { exact: true })).toHaveCount(0);
  await page.getByRole('link', { name: '环境中心', exact: true }).click();
  const agent = page.getByRole('row').filter({ hasText: '本机开发 Agent' }).filter({ has: page.getByRole('button', { name: '停止接单', exact: true }) });
  await agent.getByRole('button', { name: '停止接单', exact: true }).click();
  const stopped = page.getByRole('row').filter({ hasText: '本机开发 Agent' }).filter({ has: page.getByRole('button', { name: '恢复接单', exact: true }) });
  await stopped.getByRole('button', { name: '恢复接单', exact: true }).click();
  await expect(page.getByRole('region', { name: '执行端管理' }).getByText('在线', { exact: true })).toBeVisible();
});
test('registers an unused Agent, offers one scoped pairing file and revokes it', async ({ page }) => {
  await page.getByRole('link', { name: '环境中心', exact: true }).click();
  const name = 'E1 配对界面检查 ' + randomUUID().slice(0, 8);
  const controls = page.getByRole('region', { name: '执行端管理' });
  await controls.getByText('登记新的 Agent', { exact: true }).click();
  await controls.getByLabel('执行端名称', { exact: true }).fill(name);
  await controls.getByRole('button', { name: '生成配对文件', exact: true }).click();
  const downloadEvent = page.waitForEvent('download'); await controls.getByRole('button', { name: '保存配对文件', exact: true }).click();
  const download = await downloadEvent; const file = await download.path(); expect(file).not.toBeNull();
  const configuration = JSON.parse(readFileSync(file!, 'utf8'));
  expect(Object.keys(configuration).sort()).toEqual(['agent_id','brand_id','controller_origin','organization_id','token']);
  expect(configuration.controller_origin).toBe('http://127.0.0.1:3000');
  expect(configuration.token.length).toBe(64);
  await controls.getByRole('button', { name: '已保存，关闭此提示', exact: true }).click();
  const row = controls.getByRole('row').filter({ hasText: name });
  await expect(row.getByText('等待连接', { exact: true })).toBeVisible();
  await row.getByRole('button', { name: '撤销配对', exact: true }).click();
  await expect(row.getByText('已撤销', { exact: true })).toBeVisible();
  await expect(row.getByRole('button')).toHaveCount(0);
});

test('records a contact basis and prevents its use after opt-out in the account workbench', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.getByRole('link', { name: '账号中心', exact: true }).click();
  await page.getByLabel('联系依据所属账号', { exact: true }).selectOption('44444444-4444-4444-8444-444444444444');
  await page.getByRole('button', { name: '管理联系依据', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: '联系依据与退出', exact: true });
  await dialog.getByLabel('目标在此账号下的标识', { exact: true }).fill('synthetic-ui-' + randomUUID());
  await dialog.getByRole('button', { name: '登记联系目标', exact: true }).click();
  await expect(dialog.getByText('尚未记录退出', { exact: true })).toBeVisible();
  await dialog.getByLabel('联系依据类型', { exact: true }).selectOption('explicit_consent');
  await dialog.getByLabel('本次用途', { exact: true }).selectOption('marketing');
  await dialog.getByLabel('依据记录编号或出处', { exact: true }).fill('synthetic-ui-consent-' + randomUUID().slice(0, 8));
  const past = new Date(Date.now()-86400000).toISOString().slice(0, 16); const future = new Date(Date.now()+86400000).toISOString().slice(0, 16);
  await dialog.getByLabel('依据发生时间', { exact: true }).fill(past);
  await dialog.getByLabel('依据生效时间', { exact: true }).fill(past);
  await dialog.getByLabel('依据到期时间', { exact: true }).fill(future);
  await dialog.getByLabel('渠道规则出处或版本', { exact: true }).fill('synthetic-ui-policy-v1');
  await dialog.getByLabel('联系窗口规则', { exact: true }).selectOption('NOT_REQUIRED');
  await dialog.getByLabel('依据说明', { exact: true }).fill('本项目合成记录，仅验证联系依据管理，不产生真实发送授权。');
  await dialog.getByLabel('已核对来源用途与渠道规则', { exact: true }).check();
  await dialog.getByRole('button', { name: '保存联系依据', exact: true }).click();
  await expect(dialog.getByLabel('检查哪条联系依据', { exact: true })).not.toHaveValue('');
  await dialog.getByRole('button', { name: '检查选中依据', exact: true }).click();
  await expect(dialog.getByRole('status')).toContainText('检查时的联系依据满足要求');
  await dialog.getByLabel('退出或撤销原因', { exact: true }).fill('合成退出请求');
  await dialog.getByRole('button', { name: '记录退出', exact: true }).click();
  await expect(dialog.getByText('已退出联系', { exact: true })).toBeVisible();
  await dialog.getByRole('button', { name: '检查选中依据', exact: true }).click();
  await expect(dialog.getByRole('status')).toContainText('目标已退出联系');
  await page.screenshot({ path: 'output/playwright/contact-permission-exit.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('configures a currency budget and reconciles an unknown synthetic cost through the workbench', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.getByRole('link', { name: '能力与验证', exact: true }).click();
  const ledger = page.getByRole('region', { name: '费用与预算' });
  await ledger.getByText('登记或调整预算', { exact: true }).click();
  await ledger.getByLabel('预算币种代码', { exact: true }).fill('QAA');
  const exponent = ledger.getByLabel('币种小数位数', { exact: true });
  if (await exponent.isEditable()) await exponent.fill('0');
  await ledger.getByLabel('币种精度依据', { exact: true }).fill('合成费用测试规定为零位小数，不对应真实币种账单');
  await ledger.getByLabel('预算上限（最小单位）', { exact: true }).fill('100000');
  await ledger.getByLabel('预算设置原因', { exact: true }).fill('本地界面合成核账检查，不产生付款');
  await ledger.getByRole('button', { name: '保存预算', exact: true }).click();
  await expect(ledger.getByRole('status')).toHaveText('预算已保存');
  const budgetRow = ledger.getByRole('table', { name: '币种预算', exact: true }).getByRole('row').filter({ hasText: 'QAA' });
  await expect(budgetRow.getByText('小数位数 0', { exact: true })).toBeVisible();
  const fixture = JSON.parse(execFileSync(process.execPath, ['node_modules/tsx/dist/cli.mjs', 'tests/helpers/cost-ui-fixture.ts'], { encoding: 'utf8', windowsHide: true, env: { ...process.env, KFF_ROOT: process.cwd(), KFF_LOCAL_COST_UI_FIXTURE: '1', KFF_ENABLE_LIVE: 'false' } }));
  await ledger.getByRole('button', { name: '刷新费用记录', exact: true }).click();
  const row = ledger.getByRole('table', { name: '动作费用', exact: true }).getByRole('row').filter({ hasText: fixture.title });
  await expect(row.getByRole('cell').nth(2)).toHaveText('123');
  await expect(row.getByRole('cell').nth(3)).toHaveText('待核账');
  await ledger.getByLabel('选择核账动作', { exact: true }).selectOption(fixture.action_id);
  await ledger.getByLabel('核账处理', { exact: true }).selectOption('PENDING');
  await ledger.getByLabel('账单或核查依据', { exact: true }).fill('synthetic-ui/pending/' + fixture.action_id);
  await ledger.getByLabel('核账说明', { exact: true }).fill('合成账单尚待核查，继续保留全部预占费用。');
  await ledger.getByLabel('已核对本动作的费用依据与处理结果', { exact: true }).check();
  await ledger.getByRole('button', { name: '保存核账记录', exact: true }).click();
  await expect(ledger.getByRole('status')).toHaveText('核账记录已保存，试验次数保持不变');
  await expect(row.getByRole('cell').nth(3)).toHaveText('待核账');
  await ledger.getByLabel('选择核账动作', { exact: true }).selectOption(fixture.action_id);
  await ledger.getByLabel('核账处理', { exact: true }).selectOption('RELEASE');
  await ledger.getByLabel('账单或核查依据', { exact: true }).fill('synthetic-ui/zero-charge/' + fixture.action_id);
  await ledger.getByLabel('核账说明', { exact: true }).fill('合成执行端已提前撤销，没有命令和平台调用，核查为零费用。');
  await ledger.getByLabel('已核对本动作的费用依据与处理结果', { exact: true }).check();
  await ledger.getByRole('button', { name: '保存核账记录', exact: true }).click();
  await expect(row.getByRole('cell').nth(3)).toHaveText('0');
  await expect(row.getByRole('cell').nth(4)).toHaveText('零费用已释放');
  const detail = await (await page.request.get('/api/runs/' + fixture.run_id)).json();
  expect(detail.run.action_state).toBe('CANCELED');
  await ledger.getByText(/^费用事件 · 最近/).click();
  await expect(ledger.getByRole('table', { name: '费用事件', exact: true }).getByText('synthetic-ui/zero-charge/' + fixture.action_id)).toBeVisible();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'output/playwright/cost-ledger-reconciled.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await ledger.getByText('登记或调整预算', { exact: true }).click();
  await ledger.getByLabel('选择核账动作', { exact: true }).selectOption(fixture.action_id);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'output/playwright/cost-ledger-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('records inconclusive and confirmed human reviews of one original synthetic submission without retrying it', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const { title, row } = await createAndRun(page, 'lost_after_submit');
  await expect(row.getByText('需人工处理', { exact: true })).toBeVisible({ timeout: 30000 });
  const workspace = await (await page.request.get('/api/workspace')).json();
  const run = workspace.runs.find((value: { title: string }) => value.title === title);
  const postsResponse = await page.request.get('http://127.0.0.1:4311/posts?action_id=' + encodeURIComponent(run.action_id));
  expect(postsResponse.ok()).toBe(true); const posts = await postsResponse.json(); expect(posts).toHaveLength(1);
  await page.getByRole('link', { name: '运行记录', exact: true }).click();
  await page.getByRole('button', { name: title, exact: true }).click();
  const detail = page.getByRole('dialog', { name: '运行详情', exact: true });
  const review = detail.getByRole('region', { name: '人工复核与裁定' });
  await review.getByText('登记新的人工裁定', { exact: true }).click();
  await review.getByLabel('证据中实际账号的标识', { exact: true }).fill(posts[0].account_id);
  await review.getByLabel('结果证据出处或记录编号', { exact: true }).fill('synthetic-ui/pending-review/' + run.action_id);
  await review.getByLabel('人工裁定原因', { exact: true }).fill('本地合成场景：第一轮证据不足，保留待人工结果并禁止重发。');
  await review.getByLabel('我已核对以上证据，并确认本次人工裁定', { exact: true }).check();
  await review.getByRole('button', { name: '保存人工裁定', exact: true }).click();
  await expect(review.getByText('第 1 次裁定', { exact: true })).toBeVisible();
  await expect(detail.getByText('需人工处理', { exact: true }).first()).toBeVisible();
  await review.getByRole('button', { name: '载入最新裁定状态', exact: true }).click();
  await review.getByLabel('本次裁定', { exact: true }).selectOption('CONFIRMED_SUCCESS');
  await review.getByLabel('证据中实际账号的标识', { exact: true }).fill(posts[0].account_id);
  await review.getByLabel('证据中的远端对象 ID', { exact: true }).fill(posts[0].id);
  await review.getByLabel('结果证据出处或记录编号', { exact: true }).fill('synthetic-ui/matched-original/' + run.action_id);
  await review.getByLabel('人工裁定原因', { exact: true }).fill('本地合成页记录中的动作标识、账号、正文及原提交对象均已匹配。');
  await review.getByLabel('已核对账号、内容、时间和对象，证据确实属于原提交', { exact: true }).check();
  await review.getByLabel('我已核对以上证据，并确认本次人工裁定', { exact: true }).check();
  await review.getByRole('button', { name: '保存人工裁定', exact: true }).click();
  await expect(review.getByText('人工确认成功', { exact: true })).toBeVisible();
  await expect(detail.getByText('人工裁定成功', { exact: true })).toBeVisible();
  await expect(detail.getByText('结果来自人工裁定', { exact: true })).toBeVisible();
  await expect(review.getByText('第 2 次裁定', { exact: true })).toBeVisible();
  await review.scrollIntoViewIfNeeded();
  await detail.screenshot({ path: 'output/playwright/human-adjudication.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await review.scrollIntoViewIfNeeded();
  await detail.screenshot({ path: 'output/playwright/human-adjudication-mobile.png' });
  await detail.getByRole('button', { name: '解除环境隔离', exact: true }).click();
  await expect(page.getByRole('status').getByText('已解除隔离', { exact: true })).toBeVisible();
  const latest = await (await page.request.get('/api/runs/' + run.id)).json();
  expect(latest.attempts).toHaveLength(1); expect(latest.adjudications).toHaveLength(2);
  expect(latest.run.receipt.evidence_kind).toBe('human_review');
  expect(await (await page.request.get('http://127.0.0.1:4311/posts?action_id=' + encodeURIComponent(run.action_id))).json()).toHaveLength(1);
  expect(errors).toEqual([]);
});
