import {z} from 'zod';
const uuid=z.string().uuid(),positive=z.string().regex(/^[1-9][0-9]{0,17}$/),nonnegative=z.string().regex(/^(0|[1-9][0-9]{0,17})$/),reason=z.string().trim().min(1).max(500);
export const refundInput=z.object({request_id:uuid,expected_version:z.number().int().positive(),amount_minor:positive,confirmed_available_minor:nonnegative,reason,provider_reason:z.enum(['requested_by_customer','duplicate']).nullable(),confirmation:z.literal('REFUND_CONFIRMED_AMOUNT')}).strict();
export const refundControlInput=z.object({request_id:uuid,expected_version:z.number().int().positive(),reason}).strict();
export const financialRecheckInput=z.object({request_id:uuid,reason}).strict();
export const financialAdjustmentInput=z.object({request_id:uuid,expected_version:z.number().int().positive(),amount_minor:positive,direction:z.enum(['DEBIT','CREDIT']),currency:z.string().regex(/^[A-Z]{3}$/),reason,evidence_ref:z.string().trim().min(1).max(300),dispute_id:uuid.nullable(),confirmation:z.literal('RECORD_ACCOUNTING_ADJUSTMENT')}).strict();
export const reverseAdjustmentInput=z.object({request_id:uuid,expected_version:z.number().int().positive(),reason,evidence_ref:z.string().trim().min(1).max(300),confirmation:z.literal('REVERSE_THIS_ADJUSTMENT')}).strict();
export type RefundState='READY'|'SUBMITTING'|'PENDING'|'REQUIRES_ACTION'|'SUCCEEDED'|'FAILED'|'CANCELED'|'NEEDS_HUMAN';
export interface RefundLedger {payment_id:string;organization_id:string;brand_id:string;connection_id:string;version:number;provider_charge_id:string|null;remote_reserved_minor:string;refund_blocked:boolean;synced_at:string|null;snapshot_hash:string|null;error_code:string|null;next_check_at:string;lease_token:string|null;lease_until:string|null;checks:number}
export interface RefundRequest {id:string;organization_id:string;brand_id:string;payment_id:string;amount_minor:string;reason:string;provider_request:Record<string,unknown>;provider_refund_id:string|null;submitted_at:string|null;state:RefundState;error_code:string|null;request_id:string;request_hash:string;created_by:string;created_at:string}
export function parseRefundAmount(value:string,exponent:number){if(!Number.isInteger(exponent)||exponent<0||exponent>6)throw new Error('币种精度无效');const parts=/^(0|[1-9][0-9]*)(?:\.([0-9]+))?$/.exec(value.trim());if(!parts||(parts[2]?.length??0)>exponent)throw new Error('请按此币种的小数位填写金额');const amount=BigInt(parts[1]+(parts[2]??'').padEnd(exponent,'0'));if(amount<=0n||amount>999999999999999999n)throw new Error('请输入范围内的大于零金额');return amount.toString();}
