import { readFileSync } from 'node:fs';
import path from 'node:path';
import { digest } from './index';

export function adapterSourceHashes(root: string, adapter: 'facebook' | 'fixture') {
  const files = ['packages/adapters/src/' + adapter + '.ts', 'packages/adapters/src/templates.ts', 'packages/contracts/src/template.ts', 'packages/contracts/src/index.ts', 'packages/contracts/src/environment.ts', 'packages/adapters/src/browser-profile.ts', 'packages/core/src/index.ts', 'packages/contracts/src/collection.ts', 'packages/contracts/src/browser-collection.ts', 'packages/adapters/src/collection-fixture.ts', 'packages/adapters/src/browser-discovery.ts', 'packages/adapters/src/browser-discovery-fixture.ts',...(adapter==='facebook'?['apps/agent/src/guardian.ts','apps/agent/src/guardian-child.ts','packages/adapters/src/facebook-browser-comment.ts','packages/adapters/src/facebook-comment-reply-dom.ts','packages/adapters/src/facebook-browser-message.ts','packages/adapters/src/facebook-message-result-dom.ts','packages/adapters/src/facebook-browser-inbox.ts','packages/adapters/src/facebook-inbox-dom.ts','packages/contracts/src/browser-inbox.ts','packages/adapters/src/facebook-browser-identity.ts','packages/adapters/src/facebook-browser-discovery.ts','packages/adapters/src/facebook-search-dom.ts','packages/adapters/src/facebook-comments-dom.ts','packages/adapters/src/facebook-browser-comments.ts','packages/adapters/src/discovery.ts','packages/adapters/src/apify.ts','packages/adapters/src/apify-connection.ts','packages/adapters/src/source-http.ts','packages/adapters/src/social-outreach.ts','packages/contracts/src/acquisition.ts','packages/adapters/src/facebook-messenger.ts','packages/adapters/src/facebook-events.ts','packages/contracts/src/lead.ts']:[])];
  if (adapter === 'facebook') files.push('packages/adapters/src/facebook-browser-page.ts', 'packages/adapters/src/facebook-inbox-directory-dom.ts');
  return Object.fromEntries(files.map(file => [file, digest(readFileSync(path.join(/* turbopackIgnore: true */ root, file), 'utf8'))]));
}
export function adapterImplementationDigest(root: string, adapter: 'facebook' | 'fixture') { return digest(adapterSourceHashes(root, adapter)); }
