import {randomUUID} from 'node:crypto';
import type {PoolClient} from 'pg';
import type {z} from 'zod';
import {scoped} from '@kff/database';
import type {Scope} from '@kff/contracts';
import type {VerifiedPayment,StripeConnection} from '../../contracts/src/payment';
import {refundInput,refundControlInput,financialRecheckInput,financialAdjustmentInput,reverseAdjustmentInput,type RefundLedger,type RefundRequest} from '../../contracts/src/refund';
import {AppError,digest,requireCondition} from './index';
import {requireAdmin,requireWrite,audit} from './service';
import {paymentLock,paymentOutboundScope,assertPaymentOutbound} from './payments';

export async function lockRefundLedger(client:PoolClient,paymentId:string){const row=(await client.query<RefundLedger>('SELECT * FROM kff.refund_ledgers WHERE payment_id=$1 FOR UPDATE',[paymentId])).rows[0];requireCondition(row,'NOT_FOUND','已核实付款不存在',404);return row;}
export async function refundBalance(client:PoolClient,ledger:RefundLedger){
 const payment=(await client.query<VerifiedPayment>('SELECT * FROM kff.verified_payments WHERE id=$1',[ledger.payment_id])).rows[0];requireCondition(payment,'NOT_FOUND','付款凭据不存在',404);
 const reserved=(await client.query<{amount:string}>("SELECT coalesce(sum(amount_minor),0)::text AS amount FROM kff.refund_requests WHERE payment_id=$1 AND provider_refund_id IS NULL AND state NOT IN ('FAILED','CANCELED')",[payment.id])).rows[0].amount;
 const refunded=(await client.query<{amount:string}>('SELECT coalesce(-sum(amount_minor),0)::text AS amount FROM kff.refund_postings WHERE payment_id=$1',[payment.id])).rows[0].amount;
 const adjustments=(await client.query<{amount:string}>('SELECT coalesce(sum(amount_minor),0)::text AS amount FROM kff.financial_adjustments WHERE payment_id=$1',[payment.id])).rows[0].amount;
 const remaining=BigInt(payment.amount_minor)-BigInt(ledger.remote_reserved_minor)-BigInt(reserved),net=BigInt(payment.amount_minor)-BigInt(refunded);
 return {payment,reserved_minor:reserved,provider_reserved_minor:ledger.remote_reserved_minor,refunded_minor:refunded,available_minor:(remaining<0n?0n:remaining).toString(),net_after_refunds_minor:net.toString(),manual_adjustments_minor:adjustments,net_with_manual_adjustments_minor:(net+BigInt(adjustments)).toString()};
}
export async function assertRefundOutbound(client:PoolClient,connection:StripeConnection,actorId:string){await assertPaymentOutbound(client,connection,actorId);requireCondition((await client.query("SELECT 1 FROM kff.memberships WHERE user_id=$1 AND role='admin'",[actorId])).rowCount,'FORBIDDEN_SCOPE','退款授权人员已无此品牌管理员权限',403);}
export async function financialWorkspace(scope:Scope,paymentId:string){return scoped(scope,async client=>{
 const ledger=(await client.query<RefundLedger>('SELECT * FROM kff.refund_ledgers WHERE payment_id=$1',[paymentId])).rows[0];requireCondition(ledger,'NOT_FOUND','已核实付款不存在',404);const balance=await refundBalance(client,ledger);
 const requests=(await client.query<Pick<RefundRequest,'id'|'amount_minor'|'state'|'reason'|'provider_refund_id'|'submitted_at'|'error_code'|'created_at'>>('SELECT id,amount_minor::text,state,reason,provider_refund_id,submitted_at,error_code,created_at FROM kff.refund_requests WHERE payment_id=$1 ORDER BY created_at DESC,id LIMIT 100',[paymentId])).rows;
 const refunds=(await client.query<{id:string;provider_refund_id:string;amount_minor:string;currency:string;provider_status:string;failure_reason:string|null;request_id:string|null;observed_at:string}>('SELECT id,provider_refund_id,amount_minor::text,currency,provider_status,failure_reason,request_id,observed_at FROM kff.stripe_refunds WHERE payment_id=$1 ORDER BY observed_at DESC,id LIMIT 100',[paymentId])).rows;
 const disputes=(await client.query<{id:string;provider_dispute_id:string;amount_minor:string;currency:string;provider_status:string;reason:string;is_charge_refundable:boolean;observed_at:string}>('SELECT id,provider_dispute_id,amount_minor::text,currency,provider_status,reason,is_charge_refundable,observed_at FROM kff.stripe_disputes WHERE payment_id=$1 ORDER BY observed_at DESC,id LIMIT 100',[paymentId])).rows;
 const adjustments=(await client.query<{id:string;amount_minor:string;currency:string;minor_unit_exponent:number;reason:string;evidence_ref:string;reverses_id:string|null;dispute_id:string|null;created_at:string;reversed:boolean}>('SELECT a.id,a.amount_minor::text,a.currency,a.minor_unit_exponent,a.reason,a.evidence_ref,a.reverses_id,a.dispute_id,a.created_at,EXISTS(SELECT 1 FROM kff.financial_adjustments r WHERE r.reverses_id=a.id) AS reversed FROM kff.financial_adjustments a WHERE a.payment_id=$1 ORDER BY a.created_at DESC,a.id LIMIT 100',[paymentId])).rows;
 const postings=(await client.query('SELECT id,amount_minor::text,kind,refund_id,observation_id,created_at FROM kff.refund_postings WHERE payment_id=$1 ORDER BY created_at DESC,id LIMIT 100',[paymentId])).rows;
 const disputeBalances=(await client.query('SELECT provider_transaction_id,dispute_id,amount_minor::text,fee_minor::text,net_minor::text,currency,created_at FROM kff.dispute_balance_entries WHERE payment_id=$1 ORDER BY created_at DESC,id LIMIT 100',[paymentId])).rows;
 const observations=(await client.query('SELECT id,refund_id,dispute_id,object_version,source_event_id,observed_at FROM kff.financial_observations WHERE payment_id=$1 ORDER BY observed_at DESC,id LIMIT 100',[paymentId])).rows;
 const events=(await client.query('SELECT id,provider_event_id,event_type,state,error_code,received_at FROM kff.stripe_events WHERE connection_id=$1 AND payload->\'financial\'->\'object\'->>\'payment_intent\'=$2 ORDER BY received_at DESC,id LIMIT 100',[ledger.connection_id,balance.payment.provider_intent_id])).rows;
 const {id,order_id,checkout_id,connection_id,provider_intent_id,mode,is_synthetic,amount_minor,currency,minor_unit_exponent,verified_at}=balance.payment;
 const controls=(await client.query<{enabled:boolean;fresh:boolean}>("SELECT c.outbound_enabled AND NOT b.outbound_paused AND NOT o.outbound_paused AS enabled,l.synced_at>clock_timestamp()-interval '15 minutes' AS fresh FROM kff.refund_ledgers l JOIN kff.stripe_connections c ON c.id=l.connection_id JOIN kff.brands b ON b.id=l.brand_id JOIN kff.organizations o ON o.id=l.organization_id WHERE l.payment_id=$1",[paymentId])).rows[0];
 return {...balance,payment:{id,order_id,checkout_id,connection_id,provider_intent_id,mode,is_synthetic,amount_minor,currency,minor_unit_exponent,verified_at},new_refunds_enabled:controls.enabled&&(mode==='TEST'||process.env.KFF_ENABLE_LIVE==='true'),fresh:controls.fresh===true,ledger:{payment_id:paymentId,version:ledger.version,synced_at:ledger.synced_at,refund_blocked:ledger.refund_blocked,error_code:ledger.error_code},requests,refunds,disputes,adjustments,postings,dispute_balances:disputeBalances,observations,events};
});}
export async function queueRefund(scope:Scope,paymentId:string,input:z.infer<typeof refundInput>){
 requireAdmin(scope);const value=refundInput.parse(input),hash=digest({paymentId,input:value});return paymentOutboundScope(scope,async client=>{
  await paymentLock(client,scope.brand_id,'refund/'+value.request_id);const old=(await client.query<RefundRequest>('SELECT * FROM kff.refund_requests WHERE request_id=$1',[value.request_id])).rows[0];if(old){requireCondition(old.request_hash===hash,'IDEMPOTENCY_CONFLICT','此请求已用于不同退款',409);return {id:old.id,state:old.state};}
  const reference=(await client.query<{connection_id:string}>('SELECT connection_id FROM kff.refund_ledgers WHERE payment_id=$1',[paymentId])).rows[0];requireCondition(reference,'NOT_FOUND','已核实付款不存在',404);
  const connection=(await client.query<StripeConnection>('SELECT * FROM kff.stripe_connections WHERE id=$1 FOR SHARE',[reference.connection_id])).rows[0];await assertRefundOutbound(client,connection,scope.user_id);
  const ledger=await lockRefundLedger(client,paymentId),balance=await refundBalance(client,ledger);requireCondition(ledger.version===value.expected_version,'VERSION_CONFLICT','退款额度已经变化，请刷新核对',409);
  const fresh=(await client.query("SELECT synced_at>clock_timestamp()-interval '15 minutes' AS valid FROM kff.refund_ledgers WHERE payment_id=$1",[paymentId])).rows[0].valid;
  requireCondition(fresh&&!ledger.error_code&&!ledger.refund_blocked,'REFUND_RECONCILIATION_REQUIRED','先核对 Stripe 原付款、退款与争议状态',409);
  requireCondition(balance.available_minor===value.confirmed_available_minor&&BigInt(value.amount_minor)<=BigInt(balance.available_minor),'REFUND_AMOUNT_EXCEEDED','退款金额超过已核对的可退额度',409);
  requireCondition(BigInt(value.amount_minor)<=BigInt(Number.MAX_SAFE_INTEGER),'STRIPE_AMOUNT_UNSUPPORTED','退款金额超出 Stripe 整数精度',400);
  requireCondition(!['ISK','UGX'].includes(balance.payment.currency)||BigInt(value.amount_minor)%100n===0n,'STRIPE_FRACTION_UNSUPPORTED','此币种的 Stripe 退款必须为整主单位',400);
  const id=randomUUID(),providerRequest={payment_intent:balance.payment.provider_intent_id,amount:Number(value.amount_minor),...(value.provider_reason?{reason:value.provider_reason}:{}),metadata:{kff_refund_request_id:id,kff_payment_id:paymentId,kff_order_id:balance.payment.order_id,kff_brand_id:scope.brand_id}};
  await client.query('INSERT INTO kff.refund_requests(id,organization_id,brand_id,payment_id,amount_minor,reason,provider_request,request_id,request_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)',[id,scope.organization_id,scope.brand_id,paymentId,value.amount_minor,value.reason,providerRequest,value.request_id,hash,scope.user_id]);
  await client.query('UPDATE kff.refund_ledgers SET version=version+1,next_check_at=clock_timestamp(),checks=0 WHERE payment_id=$1',[paymentId]);await audit(client,scope,'stripe.refund_requested',id,{payment_id:paymentId,amount_minor:value.amount_minor,currency:balance.payment.currency,mode:balance.payment.mode,reason:value.reason});return {id,state:'READY' as const};
 });
}
async function replayControl(client:PoolClient,eventType:string,requestId:string,hash:string){const old=(await client.query('SELECT details FROM kff.audit_events WHERE event_type=$1 AND details->>\'request_id\'=$2',[eventType,requestId])).rows[0];if(old){requireCondition(old.details.request_hash===hash,'IDEMPOTENCY_CONFLICT','此请求已经用于不同处理',409);return true;}return false;}
export async function requestFinancialRecheck(scope:Scope,paymentId:string,input:z.infer<typeof financialRecheckInput>){requireWrite(scope);const value=financialRecheckInput.parse(input),hash=digest({paymentId,input:value});return scoped(scope,async client=>{
 await paymentLock(client,scope.brand_id,'financial-recheck/'+value.request_id);if(await replayControl(client,'stripe.financial_recheck_requested',value.request_id,hash))return {queued:true};await lockRefundLedger(client,paymentId);
 await client.query('UPDATE kff.refund_ledgers SET next_check_at=clock_timestamp(),checks=0,version=version+1 WHERE payment_id=$1',[paymentId]);await audit(client,scope,'stripe.financial_recheck_requested',paymentId,{request_id:value.request_id,request_hash:hash,reason:value.reason});return {queued:true};
});}
export async function cancelUnsubmittedRefund(scope:Scope,id:string,input:z.infer<typeof refundControlInput>){requireAdmin(scope);const value=refundControlInput.parse(input),hash=digest({id,input:value});return scoped(scope,async client=>{
 await paymentLock(client,scope.brand_id,'refund-cancel/'+value.request_id);if(await replayControl(client,'stripe.refund_canceled_locally',value.request_id,hash))return {canceled:true};const reference=(await client.query<RefundRequest>('SELECT * FROM kff.refund_requests WHERE id=$1',[id])).rows[0];requireCondition(reference,'NOT_FOUND','退款请求不存在',404);const ledger=await lockRefundLedger(client,reference.payment_id),request=(await client.query<RefundRequest>('SELECT * FROM kff.refund_requests WHERE id=$1 FOR UPDATE',[id])).rows[0];
 requireCondition(ledger.version===value.expected_version,'VERSION_CONFLICT','退款记录已经变化',409);requireCondition(!request.submitted_at&&!request.provider_refund_id&&['READY','NEEDS_HUMAN'].includes(request.state),'REFUND_ALREADY_SUBMITTED','此退款已提交或已有结果，不能按未提交请求撤销',409);
 await client.query("UPDATE kff.refund_requests SET state='CANCELED',error_code=NULL WHERE id=$1",[id]);await client.query('UPDATE kff.refund_ledgers SET version=version+1 WHERE payment_id=$1',[ledger.payment_id]);await audit(client,scope,'stripe.refund_canceled_locally',id,{request_id:value.request_id,request_hash:hash,reason:value.reason});return {canceled:true};
});}
async function insertAdjustment(scope:Scope,paymentId:string,value:{request_id:string;expected_version:number;amount_minor:string;reason:string;evidence_ref:string;dispute_id:string|null;reverses_id:string|null;currency?:string},hash:string){return scoped(scope,async client=>{
 await paymentLock(client,scope.brand_id,'adjustment/'+value.request_id);const prior=(await client.query('SELECT id,request_hash FROM kff.financial_adjustments WHERE request_id=$1',[value.request_id])).rows[0];if(prior){requireCondition(prior.request_hash===hash,'IDEMPOTENCY_CONFLICT','此请求已经用于不同调整',409);return {id:prior.id as string};}
 const ledger=await lockRefundLedger(client,paymentId),payment=(await refundBalance(client,ledger)).payment;requireCondition(ledger.version===value.expected_version,'VERSION_CONFLICT','账目已变化，请刷新核对',409);requireCondition(!value.currency||value.currency===payment.currency,'ADJUSTMENT_CURRENCY_MISMATCH','调整币种必须与此付款一致',400);
 requireCondition(!(await client.query('SELECT 1 FROM kff.financial_adjustments WHERE payment_id=$1 AND evidence_ref=$2',[paymentId,value.evidence_ref])).rowCount,'DUPLICATE_ADJUSTMENT_REFERENCE','此依据已记录调整',409);
 if(value.dispute_id)requireCondition((await client.query('SELECT 1 FROM kff.stripe_disputes WHERE id=$1 AND payment_id=$2',[value.dispute_id,paymentId])).rowCount,'NOT_FOUND','该付款的争议记录不存在',404);
 if(value.reverses_id)requireCondition(!(await client.query('SELECT 1 FROM kff.financial_adjustments WHERE reverses_id=$1',[value.reverses_id])).rowCount,'ADJUSTMENT_ALREADY_REVERSED','此调整已经冲销',409);
 const row=(await client.query('INSERT INTO kff.financial_adjustments(organization_id,brand_id,payment_id,amount_minor,currency,minor_unit_exponent,reason,evidence_ref,dispute_id,reverses_id,request_id,request_hash,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id',[scope.organization_id,scope.brand_id,paymentId,value.amount_minor,payment.currency,payment.minor_unit_exponent,value.reason,value.evidence_ref,value.dispute_id,value.reverses_id,value.request_id,hash,scope.user_id])).rows[0];
 await client.query('UPDATE kff.refund_ledgers SET version=version+1 WHERE payment_id=$1',[paymentId]);await audit(client,scope,'finance.adjustment_recorded',row.id,{payment_id:paymentId,amount_minor:value.amount_minor,currency:payment.currency,mode:payment.mode,reverses_id:value.reverses_id,evidence_ref:value.evidence_ref});return {id:row.id as string};
});}
export async function recordFinancialAdjustment(scope:Scope,paymentId:string,input:z.infer<typeof financialAdjustmentInput>){requireAdmin(scope);const value=financialAdjustmentInput.parse(input);return insertAdjustment(scope,paymentId,{...value,amount_minor:value.direction==='DEBIT'?'-'+value.amount_minor:value.amount_minor,reverses_id:null},digest({paymentId,input:value}));}
export async function reverseFinancialAdjustment(scope:Scope,id:string,input:z.infer<typeof reverseAdjustmentInput>){requireAdmin(scope);const value=reverseAdjustmentInput.parse(input),row=await scoped(scope,async client=>(await client.query<{payment_id:string;amount_minor:string;reverses_id:string|null;dispute_id:string|null}>('SELECT payment_id,amount_minor::text,reverses_id,dispute_id FROM kff.financial_adjustments WHERE id=$1',[id])).rows[0]);if(!row)throw new AppError('NOT_FOUND','调整记录不存在',404);requireCondition(!row.reverses_id,'ADJUSTMENT_REVERSAL_MISMATCH','请选择原始调整进行冲销',409);return insertAdjustment(scope,row.payment_id,{...value,amount_minor:(-BigInt(row.amount_minor)).toString(),dispute_id:row.dispute_id,reverses_id:id},digest({id,input:value}));}
