import type {PoolClient} from 'pg';
import {scoped} from '@kff/database';
import type {VerifiedPayment,StripeConnection} from '../../contracts/src/payment';
import type {RefundRequest} from '../../contracts/src/refund';
import {digest,requireCondition} from './index';
import {connectionScope} from './payments';
import {lockRefundLedger} from './refunds';
import {audit} from './service';
import type {StripeFinancialGateway} from './stripe-financial-gateway';
import type {StripeFinancialPayment,StripeRefund,StripeDispute,StripeFinancialObject} from './stripe-financial-contract';
export interface FinancialPayment extends VerifiedPayment {organization_id:string;brand_id:string;snapshot_hash:string}
export interface FinancialEvent {id:string;lease_token:string;financial:StripeFinancialObject}
export interface FinancialSnapshot {payment:StripeFinancialPayment;refunds:StripeRefund[];disputes:StripeDispute[]}
export function validateFinancialPayment(original:FinancialPayment,connection:StripeConnection,current:StripeFinancialPayment){
 const data=current.metadata,charge=current.latest_charge;
 requireCondition(current.id===original.provider_intent_id&&current.livemode===(connection.mode==='LIVE')&&current.status==='succeeded'&&String(current.amount)===original.amount_minor&&String(current.amount_received)===original.amount_minor&&current.currency===original.currency.toLowerCase(),'STRIPE_PAYMENT_OBJECT_MISMATCH','Stripe 原付款的身份、金额、币种或模式不匹配',409);
 requireCondition(data.kff_order_id===original.order_id&&data.kff_checkout_id===original.checkout_id&&data.kff_brand_id===original.brand_id&&data.kff_snapshot_hash===original.snapshot_hash,'STRIPE_PAYMENT_OBJECT_MISMATCH','原付款的 KFF 关联不匹配',409);
 requireCondition(charge&&charge.payment_intent===current.id&&charge.livemode===current.livemode&&charge.paid&&charge.captured&&charge.status==='succeeded'&&String(charge.amount)===original.amount_minor&&String(charge.amount_captured)===original.amount_minor&&charge.currency===current.currency&&charge.amount_refunded<=charge.amount,'STRIPE_CHARGE_OBJECT_MISMATCH','Stripe 原 Charge 核验失败',409);return charge;
}
export function validateRefundObject(original:FinancialPayment,chargeId:string,refund:StripeRefund){requireCondition(refund.payment_intent===original.provider_intent_id&&refund.charge===chargeId&&refund.currency===original.currency.toLowerCase()&&BigInt(refund.amount)<=BigInt(original.amount_minor),'STRIPE_REFUND_OBJECT_MISMATCH','退款对象、金额或币种不属于此原付款',409);}
export function validateRequestedRefund(original:FinancialPayment,request:RefundRequest,refund:StripeRefund){const meta=refund.metadata;requireCondition(meta?.kff_refund_request_id===request.id&&meta.kff_payment_id===original.id&&meta.kff_order_id===original.order_id&&meta.kff_brand_id===original.brand_id&&String(refund.amount)===request.amount_minor&&(!request.provider_refund_id||request.provider_refund_id===refund.id)&&request.submitted_at,'STRIPE_REFUND_REQUEST_MISMATCH','Stripe 退款与固定申请或原提交不匹配',409);}
async function collect<T extends {id:string}>(get:(cursor?:string)=>Promise<{data:T[];has_more:boolean}>,renew:()=>Promise<void>){
 const values:T[]=[],seen=new Set<string>();let cursor:string|undefined;
 for(let page=0;page<100;page++){await renew();const response=await get(cursor);requireCondition(response.data.length<=100,'STRIPE_PAGINATION_INVALID','财务分页数量无效',409);for(const item of response.data){requireCondition(!seen.has(item.id),'STRIPE_PAGINATION_INVALID','财务分页重复，保留原额度等待核对',409);seen.add(item.id);values.push(item);}if(!response.has_more)return values;requireCondition(response.data.length>0,'STRIPE_PAGINATION_INVALID','财务分页游标未前进',409);cursor=response.data.at(-1)!.id;}
 requireCondition(false,'STRIPE_PAGINATION_LIMIT','财务结果超过本次核验上限，需要人工处理',409);
}
export async function captureFinancialSnapshot(gateway:StripeFinancialGateway,original:FinancialPayment,connection:StripeConnection,known:{refunds:string[];disputes:string[]},renew:()=>Promise<void>,event?:FinancialEvent):Promise<FinancialSnapshot>{
 await renew();validateFinancialPayment(original,connection,await gateway.retrievePayment(original.provider_intent_id));
 const refunds=await collect(cursor=>gateway.listRefunds(original.provider_intent_id,cursor),renew),disputes=await collect(cursor=>gateway.listDisputes(original.provider_intent_id,cursor),renew);
 const refundIds=new Set(refunds.map(row=>row.id)),disputeIds=new Set(disputes.map(row=>row.id));if(event?.financial.kind==='refund')known.refunds.push(event.financial.object.id);if(event?.financial.kind==='dispute')known.disputes.push(event.financial.object.id);
 for(const id of new Set(known.refunds)){if(refundIds.has(id))continue;await renew();const object=await gateway.retrieveRefund(id);requireCondition(object.id===id,'STRIPE_REFUND_OBJECT_MISMATCH','退款查询返回了其他对象',409);refunds.push(object);refundIds.add(id);}
 for(const id of new Set(known.disputes)){if(disputeIds.has(id))continue;await renew();const object=await gateway.retrieveDispute(id);requireCondition(object.id===id,'STRIPE_DISPUTE_OBJECT_MISMATCH','争议查询返回了其他对象',409);disputes.push(object);disputeIds.add(id);}
 await renew();const payment=await gateway.retrievePayment(original.provider_intent_id),charge=validateFinancialPayment(original,connection,payment);
 for(const refund of refunds)validateRefundObject(original,charge.id,refund);
 for(const dispute of disputes){requireCondition(dispute.payment_intent===original.provider_intent_id&&dispute.charge===charge.id&&dispute.livemode===payment.livemode,'STRIPE_DISPUTE_OBJECT_MISMATCH','争议不属于此原付款或模式',409);for(const entry of dispute.balance_transactions)requireCondition(BigInt(entry.amount)-BigInt(entry.fee)===BigInt(entry.net),'STRIPE_BALANCE_MISMATCH','争议余额变动金额不一致',409);}
 if(event){const received=event.financial;if(received.kind==='refund'){const actual=refunds.find(row=>row.id===received.object.id)!;validateRefundObject(original,charge.id,received.object);requireCondition(actual.amount===received.object.amount&&actual.currency===received.object.currency&&actual.payment_intent===received.object.payment_intent&&actual.charge===received.object.charge,'STRIPE_REFUND_OBJECT_MISMATCH','退款回调与服务器原对象不一致',409);}else if(received.kind==='dispute'){requireCondition(received.object.payment_intent===original.provider_intent_id&&received.object.charge===charge.id&&received.object.livemode===payment.livemode,'STRIPE_DISPUTE_OBJECT_MISMATCH','争议回调对象不匹配',409);}else requireCondition(received.object.id===charge.id&&received.object.payment_intent===original.provider_intent_id&&received.object.currency===charge.currency&&received.object.amount===charge.amount&&received.object.livemode===charge.livemode,'STRIPE_CHARGE_OBJECT_MISMATCH','Charge 回调不属于原付款',409);}
 return {payment,refunds:refunds.sort((a,b)=>a.id.localeCompare(b.id)),disputes:disputes.sort((a,b)=>a.id.localeCompare(b.id))};
}
const statuses=new Set(['pending','requires_action','succeeded','failed','canceled']);
async function observe(client:PoolClient,original:FinancialPayment,object:{id:string;version:number},kind:'refund'|'dispute',proof:StripeRefund|StripeDispute,hash:string,event?:FinancialEvent){return (await client.query('INSERT INTO kff.financial_observations(organization_id,brand_id,payment_id,refund_id,dispute_id,object_version,proof,proof_hash,source_event_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id',[original.organization_id,original.brand_id,original.id,kind==='refund'?object.id:null,kind==='dispute'?object.id:null,object.version,proof,hash,event?.id??null])).rows[0].id as string;}
export async function applyFinancialSnapshot(connection:StripeConnection,original:FinancialPayment,token:string,snapshot:FinancialSnapshot,event?:FinancialEvent){const scope=connectionScope(connection);return scoped(scope,async client=>{
 const ledger=await lockRefundLedger(client,original.id);const owned=(await client.query('SELECT lease_token=$2 AND lease_until>clock_timestamp() AS valid FROM kff.refund_ledgers WHERE payment_id=$1',[original.id,token])).rows[0].valid;requireCondition(owned,'FINANCIAL_LEASE_LOST','财务核验租约已变化',409);
 if(event)requireCondition((await client.query("SELECT id FROM kff.stripe_events WHERE id=$1 AND lease_token=$2 AND state='PROCESSING' AND lease_until>clock_timestamp() FOR UPDATE",[event.id,event.lease_token])).rowCount,'FINANCIAL_LEASE_LOST','财务事件已由其他处理者接管',409);
 const charge=validateFinancialPayment(original,connection,snapshot.payment);requireCondition(!ledger.provider_charge_id||ledger.provider_charge_id===charge.id,'STRIPE_CHARGE_OBJECT_MISMATCH','原 Charge 身份发生变化',409);
 let remote=0n,unknown=false;const deltas:{refund_id:string;observation_id:string;amount:bigint}[]=[];
 for(const refund of snapshot.refunds){
  validateRefundObject(original,charge.id,refund);const status=refund.status&&statuses.has(refund.status)?refund.status:'unknown';if(status!=='failed'&&status!=='canceled')remote+=BigInt(refund.amount);if(status==='unknown')unknown=true;
  let request:RefundRequest|undefined;const requestId=refund.metadata?.kff_refund_request_id;if(requestId){request=(await client.query<RefundRequest>('SELECT * FROM kff.refund_requests WHERE id::text=$1 AND payment_id=$2 FOR UPDATE',[requestId,original.id])).rows[0];requireCondition(request,'STRIPE_REFUND_REQUEST_MISMATCH','退款关联的 KFF 申请不存在',409);validateRequestedRefund(original,request,refund);}
  const hash=digest(refund),old=(await client.query<{id:string;version:number;proof_hash:string;request_id:string|null}>('SELECT id,version,proof_hash,request_id FROM kff.stripe_refunds WHERE connection_id=$1 AND provider_refund_id=$2',[connection.id,refund.id])).rows[0];
  if(old){requireCondition(old.request_id===(request?.id??null),'STRIPE_REFUND_REQUEST_MISMATCH','退款关联被修改',409);requireCondition((await client.query('SELECT 1 FROM kff.stripe_refunds WHERE id=$1 AND payment_id=$2 AND amount_minor=$3 AND currency=$4 AND provider_charge_id=$5 AND provider_intent_id=$6',[old.id,original.id,String(refund.amount),refund.currency.toUpperCase(),charge.id,original.provider_intent_id])).rowCount,'STRIPE_REFUND_OBJECT_MISMATCH','已保存退款的固定金额或原付款关联发生变化',409);}
  if(!old||old.proof_hash!==hash){let row:{id:string;version:number};
   if(old)row=(await client.query('UPDATE kff.stripe_refunds SET provider_status=$1,failure_reason=$2,proof=$3,proof_hash=$4,version=version+1,observed_at=clock_timestamp() WHERE id=$5 RETURNING id,version',[status,refund.failure_reason??null,refund,hash,old.id])).rows[0];
   else row=(await client.query('INSERT INTO kff.stripe_refunds(organization_id,brand_id,payment_id,connection_id,provider_refund_id,provider_charge_id,provider_intent_id,amount_minor,currency,request_id,provider_status,failure_reason,proof,proof_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id,version',[scope.organization_id,scope.brand_id,original.id,connection.id,refund.id,charge.id,original.provider_intent_id,String(refund.amount),refund.currency.toUpperCase(),request?.id??null,status,refund.failure_reason??null,refund,hash])).rows[0];
   const observation=await observe(client,original,row,'refund',refund,hash,event),posted=BigInt((await client.query<{amount:string}>('SELECT coalesce(sum(amount_minor),0)::text AS amount FROM kff.refund_postings WHERE refund_id=$1',[row.id])).rows[0].amount),effective=status==='unknown'?posted:status==='succeeded'?-BigInt(refund.amount):0n;
   if(effective!==posted)deltas.push({refund_id:row.id,observation_id:observation,amount:effective-posted});await audit(client,scope,'stripe.refund_observed',row.id,{payment_id:original.id,provider_refund_id:refund.id,status,observation_id:observation,mode:original.mode});
  }
  if(request)await client.query('UPDATE kff.refund_requests SET provider_refund_id=$1,state=$2,error_code=$3 WHERE id=$4',[refund.id,status==='unknown'?'NEEDS_HUMAN':status.toUpperCase(),status==='unknown'?'STRIPE_FINANCIAL_STATUS_UNKNOWN':null,request.id]);
 }
 requireCondition(remote<=BigInt(original.amount_minor),'STRIPE_REFUND_TOTAL_EXCEEDED','Stripe 退款合计与原付款冲突',409);remote=remote>BigInt(charge.amount_refunded)?remote:BigInt(charge.amount_refunded);
 for(const delta of deltas.sort((a,b)=>a.amount>b.amount?-1:a.amount<b.amount?1:0)){await client.query('INSERT INTO kff.refund_postings(organization_id,brand_id,payment_id,refund_id,observation_id,amount_minor,kind) VALUES($1,$2,$3,$4,$5,$6,$7)',[scope.organization_id,scope.brand_id,original.id,delta.refund_id,delta.observation_id,delta.amount.toString(),delta.amount<0n?'REFUND':'REFUND_REVERSAL']);}
 for(const dispute of snapshot.disputes){
  const hash=digest(dispute),old=(await client.query<{id:string;version:number;proof_hash:string}>('SELECT id,version,proof_hash FROM kff.stripe_disputes WHERE connection_id=$1 AND provider_dispute_id=$2',[connection.id,dispute.id])).rows[0];let row=old;
  if(!old||old.proof_hash!==hash){if(old)row=(await client.query('UPDATE kff.stripe_disputes SET amount_minor=$1,currency=$2,provider_status=$3,is_charge_refundable=$4,reason=$5,proof=$6,proof_hash=$7,version=version+1,observed_at=clock_timestamp() WHERE id=$8 RETURNING id,version,proof_hash',[String(dispute.amount),dispute.currency.toUpperCase(),dispute.status,dispute.is_charge_refundable,dispute.reason,dispute,hash,old.id])).rows[0];
   else row=(await client.query('INSERT INTO kff.stripe_disputes(organization_id,brand_id,payment_id,connection_id,provider_dispute_id,provider_charge_id,provider_intent_id,amount_minor,currency,provider_status,is_charge_refundable,reason,proof,proof_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING id,version,proof_hash',[scope.organization_id,scope.brand_id,original.id,connection.id,dispute.id,charge.id,original.provider_intent_id,String(dispute.amount),dispute.currency.toUpperCase(),dispute.status,dispute.is_charge_refundable,dispute.reason,dispute,hash])).rows[0];
   const observation=await observe(client,original,row!,'dispute',dispute,hash,event);await audit(client,scope,'stripe.dispute_observed',row!.id,{payment_id:original.id,provider_dispute_id:dispute.id,status:dispute.status,observation_id:observation,mode:original.mode});}
  for(const entry of dispute.balance_transactions){const entryHash=digest(entry),prior=(await client.query<{proof_hash:string;dispute_id:string}>('SELECT proof_hash,dispute_id FROM kff.dispute_balance_entries WHERE connection_id=$1 AND provider_transaction_id=$2',[connection.id,entry.id])).rows[0];if(prior){requireCondition(prior.proof_hash===entryHash&&prior.dispute_id===row!.id,'STRIPE_BALANCE_MISMATCH','已保存的争议余额对象发生变化',409);continue;}
   await client.query('INSERT INTO kff.dispute_balance_entries(organization_id,brand_id,payment_id,connection_id,dispute_id,provider_transaction_id,amount_minor,fee_minor,net_minor,currency,proof,proof_hash) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[scope.organization_id,scope.brand_id,original.id,connection.id,row!.id,entry.id,String(entry.amount),String(entry.fee),String(entry.net),entry.currency.toUpperCase(),entry,entryHash]);}
 }
 const blocked=unknown||(charge.disputed&&snapshot.disputes.length===0)||snapshot.disputes.some(dispute=>!dispute.is_charge_refundable),hash=digest(snapshot);
 requireCondition((await client.query('UPDATE kff.refund_ledgers SET provider_charge_id=$1,remote_reserved_minor=$2,refund_blocked=$3,synced_at=clock_timestamp(),snapshot_hash=$4,error_code=$5,version=version+1 WHERE payment_id=$6 AND lease_token=$7 AND lease_until>clock_timestamp()',[charge.id,remote.toString(),blocked,hash,unknown?'STRIPE_FINANCIAL_STATUS_UNKNOWN':null,original.id,token])).rowCount,'FINANCIAL_LEASE_LOST','财务核验已过期，结果没有提交',409);
 if(event)requireCondition((await client.query("UPDATE kff.stripe_events SET state='PROCESSED',error_code=NULL,lease_token=NULL,lease_until=NULL WHERE id=$1 AND lease_token=$2 AND lease_until>clock_timestamp()",[event.id,event.lease_token])).rowCount,'FINANCIAL_LEASE_LOST','财务事件已过期，结果没有提交',409);
 return {blocked,changed:ledger.snapshot_hash!==hash};
});}
