import {randomUUID,createHmac} from 'node:crypto';
import {spawn} from 'node:child_process';
import {beforeAll,beforeEach,afterAll,it,expect} from 'vitest';
import {migrate} from '../../scripts/migrate';
import {seed,localIds} from '../../scripts/seed';
import {query,scoped,closePool} from '../../packages/database/src/index';
import type {Scope} from '../../packages/contracts/src/index';
import type {FacebookEvent} from '../../packages/contracts/src/lead';
import {createAccount,createEnvironment} from '../../packages/core/src/service';
import {createFacebookFixture,configureFacebook,receiveFacebookEvent,injectFacebookFixture,receiveFacebookWebhook,facebookWorkspace} from '../../packages/core/src/facebook-inbound';
import {inboxWorkspace,inboxConversation,customerDetail} from '../../packages/core/src/inbox';
const scope:Scope={organization_id:localIds.organization,brand_id:localIds.brand,user_id:localIds.user,role:'admin'};
let counter=0;
async function setup(actor=scope){const page='81000'+(++counter);const account=await createFacebookFixture(actor,{request_id:randomUUID(),name:'FB integration '+page,page_id:page,agent_id:localIds.agent});const config={request_id:randomUUID(),...account,expected_version:0,state:'ACTIVE' as const,auto_reply:true,reply_window_hours:24,policy_ref:'fixture.fb.service-window.v1'};await configureFacebook(actor,config);return {...account,page,config};}
function incoming(page:string,overrides:Partial<FacebookEvent>={}):FacebookEvent{return {event_id:'m_'+randomUUID(),page_id:page,sender_id:'999888777666555444',body:'Interested in your product',kind:'MESSAGE',display_name:'Same name',occurred_at:new Date().toISOString(),source:{kind:'MESSENGER',page_id:page,source_id:null,ref:'ad/first',ad_id:'5001'},has_attachment:false,...overrides};}
beforeAll(async()=>{const name=(await query('SELECT current_database() AS name'))[0].name;if(name!==process.env.KFF_TEST_DATABASE||!/^kff_test_[a-f0-9]{20}$/.test(name))throw new Error('Isolated database required');await migrate();await seed();});
beforeEach(async()=>{await query('TRUNCATE kff.facebook_connections,kff.site_channels,kff.customers CASCADE');await query("DELETE FROM kff.inbound_events WHERE source_kind='facebook'");});
afterAll(closePool);
it('reuses existing customer, identity and inbox models with stable account/source and event evidence',async()=>{const account=await setup(),event=incoming(account.page);const result=await injectFacebookFixture(scope,account.account_id,event);expect(result.duplicate).toBe(false);const detail=await inboxConversation(scope,result.conversation_id!);expect(detail.conversation).toMatchObject({account_id:account.account_id,channel_kind:'FACEBOOK_MESSENGER',handling_mode:'AI'});expect(detail.messages[0]).toMatchObject({body:event.body,source:event.source});const customer=await customerDetail(scope,detail.conversation.customer_id);expect(customer.acquisition_source).toMatchObject({page_id:account.page,account_id:account.account_id,ref:'ad/first'});expect(customer.identities[0].remote_id).toBe(event.sender_id);expect((await inboxWorkspace(scope)).counts).toEqual({customers:1,conversations:1,inbound_messages:1});});
it('deduplicates concurrent events and messages, but rejects replacing one event body or sender',async()=>{const account=await setup(),event=incoming(account.page);const results=await Promise.all(Array.from({length:12},()=>injectFacebookFixture(scope,account.account_id,event)));expect(new Set(results.map(row=>row.message_id)).size).toBe(1);expect(results.filter(row=>!row.duplicate)).toHaveLength(1);for(const change of [{body:'changed'},{sender_id:'123'}])await expect(injectFacebookFixture(scope,account.account_id,{...event,...change})).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});expect((await inboxWorkspace(scope)).counts.inbound_messages).toBe(1);});
it('preserves first source and chronological bounds for out-of-order messages without merging same-name customers',async()=>{const account=await setup(),first=incoming(account.page),result=await injectFacebookFixture(scope,account.account_id,first);const earlier=new Date(Date.now()-3600000).toISOString();await injectFacebookFixture(scope,account.account_id,incoming(account.page,{occurred_at:earlier,source:{...first.source,ref:'another'}}));await injectFacebookFixture(scope,account.account_id,incoming(account.page,{sender_id:'123123'}));const customer=await customerDetail(scope,result.customer_id!);expect(customer.customer.first_interaction_at?.toString()).toBe(new Date(earlier).toString());expect(customer.acquisition_source).toMatchObject({ref:'ad/first'});expect(customer.conversations[0].last_sequence).toBe(2);expect((await inboxWorkspace(scope)).counts.customers).toBe(2);});
it('keeps same remote customer on two Facebook accounts isolated throughout history and attribution',async()=>{const a=await setup(),b=await setup(),ra=await injectFacebookFixture(scope,a.account_id,incoming(a.page)),rb=await injectFacebookFixture(scope,b.account_id,incoming(b.page,{body:'B account only'}));expect(ra.customer_id).not.toBe(rb.customer_id);expect((await inboxConversation(scope,ra.conversation_id!)).messages.map(row=>row.body)).toEqual(['Interested in your product']);await expect(injectFacebookFixture(scope,b.account_id,incoming(a.page))).rejects.toMatchObject({code:'ACCOUNT_MISMATCH'});});
it('receives comments/engagement without inventing Messenger permission or merging platform identity namespaces',async()=>{const a=await setup();await injectFacebookFixture(scope,a.account_id,incoming(a.page));for(const kind of ['COMMENT','INTERACTION'] as const){const row=await injectFacebookFixture(scope,a.account_id,incoming(a.page,{kind,source:{kind,page_id:a.page,source_id:'post_1',ref:null,ad_id:null}}));const detail=await inboxConversation(scope,row.conversation_id!);expect(detail.conversation.reply_window_expires_at).toBeNull();expect(detail.conversation.handling_mode).toBe('HUMAN');expect((await query('SELECT contact_permission_id FROM kff.messages WHERE id=$1',[row.message_id]))[0].contact_permission_id).toBeNull();}expect((await inboxWorkspace(scope)).counts).toEqual({customers:3,conversations:3,inbound_messages:1});});
it('native Facebook human echoes and unsupported attachments place conversation under human control',async()=>{const a=await setup(),first=await injectFacebookFixture(scope,a.account_id,incoming(a.page));await injectFacebookFixture(scope,a.account_id,incoming(a.page,{kind:'ECHO',body:'Human has replied'}));expect((await inboxConversation(scope,first.conversation_id!)).conversation).toMatchObject({handling_mode:'HUMAN',control_version:2,last_inbound_sequence:1});expect((await inboxWorkspace(scope)).counts.inbound_messages).toBe(1);});
it('paused reception continues to collect customers with no automatic handling',async()=>{const a=await setup();await configureFacebook(scope,{...a.config,request_id:randomUUID(),expected_version:1,state:'PAUSED'});const row=await injectFacebookFixture(scope,a.account_id,incoming(a.page));expect((await inboxConversation(scope,row.conversation_id!)).conversation.handling_mode).toBe('HUMAN');});
it('enforces viewer, brand, account/environment scope, immutable identity and optimistic config version',async()=>{const a=await setup(),other={...scope,brand_id:randomUUID()};await expect(createFacebookFixture({...scope,role:'viewer'},{request_id:randomUUID(),name:'bad',page_id:'333',agent_id:localIds.agent})).rejects.toMatchObject({code:'FORBIDDEN_SCOPE'});await expect(injectFacebookFixture({...scope,role:'viewer'},a.account_id,incoming(a.page))).rejects.toMatchObject({code:'FORBIDDEN_SCOPE'});expect((await facebookWorkspace(other)).connections).toEqual([]);await expect(injectFacebookFixture(other,a.account_id,incoming(a.page))).rejects.toMatchObject({code:'FORBIDDEN_SCOPE'});await expect(configureFacebook(scope,{...a.config,request_id:randomUUID()})).rejects.toMatchObject({code:'VERSION_CONFLICT'});await expect(configureFacebook(scope,{...a.config,request_id:randomUUID(),expected_version:1,environment_id:localIds.environment})).rejects.toMatchObject({code:'FORBIDDEN_SCOPE'});const r=await injectFacebookFixture(scope,a.account_id,incoming(a.page));await expect(inboxConversation(other,r.conversation_id!)).rejects.toMatchObject({code:'NOT_FOUND'});await expect(scoped(scope,client=>client.query('UPDATE kff.messages SET body=$1 WHERE id=$2',['changed',r.message_id]))).rejects.toThrow();await expect(query('UPDATE kff.facebook_connections SET page_id=$1,version=version+1 WHERE account_id=$2',['777',a.account_id])).rejects.toThrow('FACEBOOK_ACCOUNT_MISMATCH');});
it('signed batched webhook resolves only configured real pages and does not admit unsigned fixture injection into real accounts',async()=>{const account=await createAccount(scope,{display_name:'Real shape, no credentials',external_id:'710099',platform:'facebook',account_type:'page'});const environment=await createEnvironment(scope,{name:'Real shape',account_id:account.id,agent_id:localIds.agent});await configureFacebook(scope,{request_id:randomUUID(),account_id:account.id,environment_id:environment.id,expected_version:0,state:'ACTIVE',auto_reply:false,reply_window_hours:24,policy_ref:'fixture.contract-only'});await expect(injectFacebookFixture(scope,account.id,incoming(account.external_id))).rejects.toMatchObject({code:'FORBIDDEN_SCOPE'});const previous=process.env.KFF_FACEBOOK_APP_SECRET;process.env.KFF_FACEBOOK_APP_SECRET='fixture-signed-callback-secret';try{const bytes=Buffer.from(JSON.stringify({object:'page',entry:[{id:account.external_id,messaging:[{sender:{id:'8888'},recipient:{id:account.external_id},timestamp:Date.now(),message:{mid:'signed1',text:'Hi'}}]},{id:'123456',messaging:[]}]})),signature='sha256='+createHmac('sha256',process.env.KFF_FACEBOOK_APP_SECRET).update(bytes).digest('hex');await expect(receiveFacebookWebhook(bytes,null)).rejects.toMatchObject({code:'INVALID_SIGNATURE'});expect(await receiveFacebookWebhook(bytes,signature)).toMatchObject({stored:1,duplicates:0});expect(await receiveFacebookWebhook(bytes,signature)).toMatchObject({stored:0,duplicates:1});}finally{if(previous===undefined)delete process.env.KFF_FACEBOOK_APP_SECRET;else process.env.KFF_FACEBOOK_APP_SECRET=previous;}});
for(const boundary of ['before','after'] as const)it('recovers after actual inbound process dies '+boundary+' transaction commit',async()=>{const a=await setup(),event=incoming(a.page);const child=spawn(process.execPath,['--import','tsx','tests/helpers/facebook-inbound-process.ts',boundary],{cwd:process.cwd(),env:process.env,windowsHide:true,stdio:['ignore','ignore','ignore','ipc']});try{const barrier=new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Missing process barrier')),10000);child.on('message',value=>{if(value&&typeof value==='object'&&'barrier' in value){clearTimeout(timer);resolve();}});child.once('exit',()=>{clearTimeout(timer);reject(new Error('Exited before barrier'));});});child.send({scope,account_id:a.account_id,event});await barrier;await new Promise<void>(resolve=>{child.once('exit',()=>resolve());child.kill('SIGKILL');});const row=await receiveFacebookEvent(scope,a.account_id,event);expect(row.duplicate).toBe(boundary==='after');expect((await inboxWorkspace(scope)).counts).toEqual({customers:1,conversations:1,inbound_messages:1});}finally{if(child.exitCode===null)child.kill('SIGKILL');}});
