import {randomUUID} from 'node:crypto';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {migrate} from '../../scripts/migrate';
import {seed,localIds} from '../../scripts/seed';
import {query,scoped,closePool} from '../../packages/database/src/index';
import type {Scope} from '../../packages/contracts/src/index';
import {createSiteChannel,beginVisitorSession,receiveVisitorMessage,inboxConversation} from '../../packages/core/src/inbox';
import {saveProductVersion,controlProduct,previewOrder,confirmOrder,ownedOrderDetail,cancelOwnedOrder} from '../../packages/core/src/orders';
import {registerStripeConnection,queueStripeCheckout,receiveStripeWebhook,paymentWorkspace,controlStripeConnection,requestPaymentRecheck} from '../../packages/core/src/payments';
import {processStripeCheckout,processStripeEvent} from '../../packages/core/src/payment-worker';
import {StripeFixture,syntheticStripeCredentials,signedStripeEvent} from '../helpers/stripe-fixture';
import {POST} from '../../apps/web/app/api/[[...path]]/route';
import {AppError} from '../../packages/core/src/index';
const scope:Scope={organization_id:localIds.organization,brand_id:localIds.brand,user_id:localIds.user,role:'admin'};
let fixture:StripeFixture,ref:string,secret:string,connectionId:string;
async function order(currency='USD',exponent=2,amount='1250'){
 const channel=await createSiteChannel(scope,{request_id:randomUUID(),name:'Synthetic Stripe inquiry',is_synthetic:true,session_hours:1,reply_window_hours:1,sessions_per_minute:10,messages_per_minute:20}),visitor=await beginVisitorSession(channel.id);
 const receipt=await receiveVisitorMessage(channel.id,visitor.token,{client_message_id:randomUUID(),body:'Synthetic payment inquiry',display_name:'Synthetic Stripe buyer',client_sent_at:null}),customer=(await inboxConversation(scope,receipt.message.conversation_id)).conversation.customer_id;
 const product=await saveProductVersion(scope,{request_id:randomUUID(),sku:'PAY-'+randomUUID().slice(0,8),name:'Synthetic Stripe product',currency,minor_unit_exponent:exponent,precision_source:'Synthetic Stripe currency definition',unit_amount_minor:amount,delivery_scope:'Synthetic report only',terms:'No real purchase'});await controlProduct(scope,product.product_id,{request_id:randomUUID(),expected_version:1,state:'ACTIVE',reason:'Synthetic product approval'});
 const preview=await previewOrder(scope,{request_id:randomUUID(),customer_id:customer,conversation_id:null,items:[{product_id:product.product_id,quantity:2}]});return confirmOrder(scope,{request_id:randomUUID(),preview_id:preview.id,preview_hash:preview.snapshot_hash,confirmed_total_minor:preview.snapshot.total_minor,currency,confirmation:'CREATE_THIS_ORDER'});
}
async function checkout(){const saved=await order(),input={request_id:randomUUID(),connection_id:connectionId,expected_version:saved.version,snapshot_hash:saved.snapshot_hash,confirmation:'CREATE_STRIPE_CHECKOUT' as const},queued=await queueStripeCheckout(scope,saved.id,input);return {order:saved,input,id:queued.id};}
async function open(){const value=await checkout();await processStripeCheckout(value.id,fixture.factory);const row=(await paymentWorkspace(scope,value.order.id)).checkouts[0];expect(row.state).toBe('OPEN');return {...value,sessionId:row.provider_session_id!};}
async function webhook(sessionId:string,type='checkout.session.completed',changes:Record<string,unknown>={}){const event=signedStripeEvent(fixture.sessions.get(sessionId)!,secret,type,changes);await receiveStripeWebhook(connectionId,event.raw,event.signature);const rows=await query('SELECT id FROM kff.stripe_events WHERE provider_event_id=$1',[event.payload.id]);return {...event,id:rows[0].id as string};}
beforeAll(async()=>{const name=(await query('SELECT current_database() AS name'))[0].name;if(name!==process.env.KFF_TEST_DATABASE||!/^kff_test_[a-f0-9]{20}$/.test(name))throw new Error('Isolated database required');await migrate();await seed();});
beforeEach(async()=>{await query('TRUNCATE kff.stripe_connections,kff.products,kff.order_previews,kff.commerce_currencies CASCADE');await query('UPDATE kff.brands SET outbound_paused=false');await query('UPDATE kff.organizations SET outbound_paused=false');fixture=new StripeFixture();ref='KFF_STRIPE_'+randomUUID().slice(0,8).toUpperCase();secret=syntheticStripeCredentials(ref,{organization_id:scope.organization_id,brand_id:scope.brand_id,stripe_account_id:fixture.accountId}).secret;connectionId=(await registerStripeConnection(scope,{request_id:randomUUID(),name:'Synthetic Stripe',stripe_account_id:fixture.accountId,mode:'TEST',credential_ref:ref},fixture.factory)).id;});
afterEach(()=>{for(const suffix of ['API_KEY','WEBHOOK_SECRETS','ORGANIZATION_ID','BRAND_ID','ACCOUNT_ID'])delete process.env[ref+'_'+suffix];});afterAll(closePool);
it('queues once, freezes price and exact provider parameters, and recovers a lost create response with the same key',async()=>{
 const saved=await checkout();const copies=await Promise.all(Array.from({length:5},()=>queueStripeCheckout(scope,saved.order.id,saved.input)));expect(copies.every(row=>row.id===saved.id)).toBe(true);fixture.loseResponse=1;await processStripeCheckout(saved.id,fixture.factory);expect((await paymentWorkspace(scope)).checkouts[0].state).toBe('CREATING');
 await processStripeCheckout(saved.id,fixture.factory);expect(fixture.sessions.size).toBe(1);expect(fixture.calls).toHaveLength(2);expect(fixture.calls[0]).toEqual(fixture.calls[1]);expect(fixture.calls[0].input).not.toHaveProperty('payment_method_types');expect(fixture.calls[0].input).toMatchObject({mode:'payment',ui_mode:'hosted_page',adaptive_pricing:{enabled:false},automatic_tax:{enabled:false},allow_promotion_codes:false});
 await expect(queueStripeCheckout(scope,saved.order.id,{...saved.input,request_id:randomUUID()})).rejects.toMatchObject({code:'PAYMENT_ALREADY_PENDING'});await expect(queueStripeCheckout(scope,saved.order.id,{...saved.input,snapshot_hash:'f'.repeat(64)})).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});
});
it('persists before acknowledgement, deduplicates concurrent events and payment objects, and separates test receipts from revenue',async()=>{
 const saved=await open();fixture.pay(saved.sessionId);const event=signedStripeEvent(fixture.sessions.get(saved.sessionId)!,secret);const receipts=await Promise.all(Array.from({length:5},()=>receiveStripeWebhook(connectionId,event.raw,event.signature)));expect(receipts.filter(row=>!row.duplicate)).toHaveLength(1);const id=(await query('SELECT id FROM kff.stripe_events WHERE provider_event_id=$1',[event.payload.id]))[0].id;
 expect((await ownedOrderDetail(scope,saved.order.id)).order.payment_state).toBe('UNVERIFIED');await Promise.all(Array.from({length:5},()=>processStripeEvent(id,fixture.factory)));
 const another=await webhook(saved.sessionId);await processStripeEvent(another.id,fixture.factory);const detail=await ownedOrderDetail(scope,saved.order.id);expect(detail.order.payment_state).toBe('VERIFIED_TEST_PAID');expect(detail.verified_revenue).toBe(false);expect(detail.order.version).toBe(2);expect((await paymentWorkspace(scope)).verified).toHaveLength(1);expect((await query("SELECT count(*)::int AS n FROM kff.audit_events WHERE event_type='stripe.payment_verified' AND object_id=$1",[saved.order.id]))[0].n).toBe(1);
});
it('keeps a successful creation with a rejected follow-up query unresolved and recovers it from the original webhook',async()=>{
 const saved=await checkout();const gateway=async()=>({...fixture,isSynthetic:true,identity:()=>fixture.identity(),createSession:async(input:Parameters<StripeFixture['createSession']>[0],key:string)=>{const created=await fixture.createSession(input,key);fixture.pay(created.id);return fixture.retrieveSession(created.id);},retrieveSession:fixture.retrieveSession.bind(fixture),retrieveIntent:async()=>{throw new AppError('STRIPE_REQUEST_REJECTED','Synthetic follow-up lookup rejected');}});
 await processStripeCheckout(saved.id,gateway);expect(fixture.sessions.size).toBe(1);expect((await paymentWorkspace(scope,saved.order.id)).checkouts[0]).toMatchObject({state:'NEEDS_HUMAN',provider_session_id:null});await expect(queueStripeCheckout(scope,saved.order.id,{...saved.input,request_id:randomUUID()})).rejects.toMatchObject({code:'PAYMENT_ALREADY_PENDING'});await expect(cancelOwnedOrder(scope,saved.order.id,{request_id:randomUUID(),expected_version:1,reason:'Unsafe cancellation after unknown payment'})).rejects.toMatchObject({code:'PAYMENT_ALREADY_PENDING'});
 const event=await webhook([...fixture.sessions.keys()][0]);await processStripeEvent(event.id,fixture.factory);expect((await paymentWorkspace(scope,saved.order.id)).checkouts[0].state).toBe('PAID');expect(fixture.calls).toHaveLength(1);
});
it('handles delayed payment and old failure events without regressing a verified payment',async()=>{
 const saved=await open();fixture.pay(saved.sessionId,true);const pending=await webhook(saved.sessionId),oldFailure=await webhook(saved.sessionId,'checkout.session.async_payment_failed');await processStripeEvent(pending.id,fixture.factory);expect((await paymentWorkspace(scope)).verified).toHaveLength(0);expect((await paymentWorkspace(scope)).checkouts[0].state).toBe('PENDING');
 fixture.pay(saved.sessionId);const paid=await webhook(saved.sessionId,'checkout.session.async_payment_succeeded');await processStripeEvent(paid.id,fixture.factory);await processStripeEvent(oldFailure.id,fixture.factory);expect((await paymentWorkspace(scope)).checkouts[0].state).toBe('PAID');expect((await paymentWorkspace(scope)).verified).toHaveLength(1);
});
it('rejects wrong amount, currency, order, brand, snapshot, payment object, mode and received amount',async()=>{
 const patches=[{amount_total:1},{currency:'jpy'},{client_reference_id:randomUUID()},{metadata:{kff_brand_id:randomUUID()}},{metadata:{kff_snapshot_hash:'e'.repeat(64)}},{livemode:true}];
 for(const patch of patches){const saved=await open();fixture.pay(saved.sessionId);const original=structuredClone(fixture.sessions.get(saved.sessionId)!);Object.assign(fixture.sessions.get(saved.sessionId)!,patch.metadata?{metadata:{...original.metadata,...patch.metadata}}:patch);const event=await webhook(saved.sessionId);await processStripeEvent(event.id,fixture.factory);expect((await query('SELECT state FROM kff.stripe_events WHERE id=$1',[event.id]))[0].state).toBe('REJECTED');expect((await ownedOrderDetail(scope,saved.order.id)).order.payment_state).toBe('UNVERIFIED');}
 const saved=await open();fixture.pay(saved.sessionId);const pi=fixture.sessions.get(saved.sessionId)!.payment_intent as string;fixture.intents.get(pi)!.amount_received=1;const event=await webhook(saved.sessionId);await processStripeEvent(event.id,fixture.factory);expect((await paymentWorkspace(scope,saved.order.id)).verified).toHaveLength(0);
});
it('will not accept another merchant or another PaymentIntent with copied metadata',async()=>{
 const saved=await open();fixture.pay(saved.sessionId);fixture.wrongAccount=true;const event=await webhook(saved.sessionId);await processStripeEvent(event.id,fixture.factory);expect((await query('SELECT error_code FROM kff.stripe_events WHERE id=$1',[event.id]))[0].error_code).toBe('STRIPE_ACCOUNT_MISMATCH');fixture.wrongAccount=false;
 const pi=fixture.sessions.get(saved.sessionId)!.payment_intent as string;fixture.intents.get(pi)!.id='pi_wrong';const second=await webhook(saved.sessionId);await processStripeEvent(second.id,fixture.factory);expect((await paymentWorkspace(scope)).verified).toHaveLength(0);
});
it('rejects forged, expired, future, wrong-mode and changed duplicate events without recording payment',async()=>{
 const saved=await open();const event=signedStripeEvent(fixture.sessions.get(saved.sessionId)!,secret);await expect(receiveStripeWebhook(connectionId,event.raw,event.signature+'bad')).rejects.toMatchObject({code:'STRIPE_SIGNATURE_INVALID'});
 const {default:Stripe}=await import('stripe');for(const timestamp of [Math.floor(Date.now()/1000)-600,Math.floor(Date.now()/1000)+600]){const signature=Stripe.webhooks.generateTestHeaderString({payload:event.raw.toString(),secret,timestamp});await expect(receiveStripeWebhook(connectionId,event.raw,signature)).rejects.toMatchObject({code:'STRIPE_SIGNATURE_INVALID'});}
 const wrong=signedStripeEvent(fixture.sessions.get(saved.sessionId)!,secret,'checkout.session.completed',{livemode:true});await expect(receiveStripeWebhook(connectionId,wrong.raw,wrong.signature)).rejects.toMatchObject({code:'STRIPE_MODE_MISMATCH'});
 await receiveStripeWebhook(connectionId,event.raw,event.signature);const changed=signedStripeEvent({...fixture.sessions.get(saved.sessionId)!,amount_total:9},secret,'checkout.session.completed',{id:event.payload.id});await expect(receiveStripeWebhook(connectionId,changed.raw,changed.signature)).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});expect((await paymentWorkspace(scope)).verified).toHaveLength(0);
});
it('keeps failures durable and processes a retry after the Stripe API recovers',async()=>{
 const saved=await open();fixture.pay(saved.sessionId);const event=await webhook(saved.sessionId);fixture.unavailable=true;await processStripeEvent(event.id,fixture.factory);expect((await query('SELECT state FROM kff.stripe_events WHERE id=$1',[event.id]))[0].state).toBe('PENDING');expect((await paymentWorkspace(scope)).verified).toHaveLength(0);fixture.unavailable=false;await processStripeEvent(event.id,fixture.factory);expect((await paymentWorkspace(scope)).verified).toHaveLength(1);
});
it('keeps receipt, order state and processed acknowledgement atomic when payment persistence fails',async()=>{
 const saved=await open();fixture.pay(saved.sessionId);const event=await webhook(saved.sessionId);await query("CREATE FUNCTION kff.synthetic_payment_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Synthetic persistence failure'; END $$");await query('CREATE TRIGGER synthetic_payment_failure BEFORE INSERT ON kff.verified_payments FOR EACH ROW EXECUTE FUNCTION kff.synthetic_payment_failure()');
 try{await processStripeEvent(event.id,fixture.factory);expect((await paymentWorkspace(scope)).verified).toHaveLength(0);expect((await ownedOrderDetail(scope,saved.order.id)).order.payment_state).toBe('UNVERIFIED');expect((await query('SELECT state FROM kff.stripe_events WHERE id=$1',[event.id]))[0].state).toBe('PENDING');}finally{await query('DROP TRIGGER synthetic_payment_failure ON kff.verified_payments');await query('DROP FUNCTION kff.synthetic_payment_failure()');}
 await processStripeEvent(event.id,fixture.factory);expect((await paymentWorkspace(scope)).verified).toHaveLength(1);
});
it('pauses new checkout submission but still accepts and verifies incoming payments',async()=>{
 const queued=await checkout();await controlStripeConnection(scope,connectionId,{request_id:randomUUID(),expected_version:1,outbound_enabled:false,reason:'Synthetic pause'});await processStripeCheckout(queued.id,fixture.factory);expect(fixture.calls).toHaveLength(0);
 await controlStripeConnection(scope,connectionId,{request_id:randomUUID(),expected_version:2,outbound_enabled:true,reason:'Synthetic resume'});await processStripeCheckout(queued.id,fixture.factory);expect((await paymentWorkspace(scope,queued.order.id)).checkouts[0].state).toBe('OPEN');const saved=await open();fixture.pay(saved.sessionId);await query('UPDATE kff.brands SET outbound_paused=true WHERE id=$1',[scope.brand_id]);const event=await webhook(saved.sessionId);await processStripeEvent(event.id,fixture.factory);expect((await paymentWorkspace(scope,saved.order.id)).verified).toHaveLength(1);
});
it('prevents cancellation in flight, permits cancellation after verified expiry, and guards RLS and immutable identities',async()=>{
 const saved=await open();await expect(cancelOwnedOrder(scope,saved.order.id,{request_id:randomUUID(),expected_version:1,reason:'Synthetic cancel'})).rejects.toMatchObject({code:'PAYMENT_ALREADY_PENDING'});
 await expect(query('UPDATE kff.payment_checkouts SET amount_minor=1 WHERE id=$1',[saved.id])).rejects.toThrow('IMMUTABLE_PAYMENT_REQUEST');await expect(query("UPDATE kff.stripe_connections SET stripe_account_id='acct_wrong' WHERE id=$1",[connectionId])).rejects.toThrow('IMMUTABLE_STRIPE_CONNECTION');
 fixture.expire(saved.sessionId);const event=await webhook(saved.sessionId,'checkout.session.expired');await processStripeEvent(event.id,fixture.factory);await cancelOwnedOrder(scope,saved.order.id,{request_id:randomUUID(),expected_version:1,reason:'Expired synthetic payment'});expect((await ownedOrderDetail(scope,saved.order.id)).order.state).toBe('CANCELED');
 const other={...scope,brand_id:randomUUID()};for(const table of ['stripe_connections','payment_checkouts','stripe_events','verified_payments'])expect(await scoped(other,async client=>(await client.query('SELECT * FROM kff.'+table)).rows)).toEqual([]);await expect(paymentWorkspace(other,saved.order.id)).rejects.toMatchObject({code:'NOT_FOUND'});await expect(queueStripeCheckout({...scope,role:'viewer'},saved.order.id,saved.input)).rejects.toMatchObject({code:'FORBIDDEN_SCOPE'});
});
it('never recreates an unknown session after the idempotency retention window',async()=>{
 const saved=await checkout();await query("UPDATE kff.payment_checkouts SET submitted_at=clock_timestamp()-interval '25 hours',state='CREATING' WHERE id=$1",[saved.id]);await processStripeCheckout(saved.id,fixture.factory);expect(fixture.calls).toHaveLength(0);expect((await paymentWorkspace(scope)).checkouts[0]).toMatchObject({state:'NEEDS_HUMAN',error_code:'STRIPE_IDEMPOTENCY_WINDOW_EXPIRED'});
});
it('supports a server query of the original object and does not infer payment from browser redirects',async()=>{
 const saved=await open();fixture.pay(saved.sessionId);await requestPaymentRecheck(scope,saved.id,{request_id:randomUUID(),reason:'Synthetic callback delivery recovery'});await processStripeCheckout(saved.id,fixture.factory);expect(fixture.calls).toHaveLength(1);expect((await paymentWorkspace(scope)).verified).toHaveLength(1);
 const another=await checkout();expect((await ownedOrderDetail(scope,another.order.id)).order.payment_state).toBe('UNVERIFIED');
});
it('receives signed raw HTTP requests without staff login and refuses altered bodies or oversized streams',async()=>{
 const saved=await open();const event=signedStripeEvent(fixture.sessions.get(saved.sessionId)!,secret),context={params:Promise.resolve({path:['stripe','webhooks',connectionId]})};
 const request=new Request('http://127.0.0.1:3000/api/stripe/webhooks/'+connectionId,{method:'POST',headers:{'Content-Type':'application/json','Stripe-Signature':event.signature},body:new Uint8Array(event.raw)});const response=await POST(request,context);expect(response.status).toBe(200);expect(await response.json()).toMatchObject({receipt:'STORED'});
 const changed=new Request(request.url,{method:'POST',headers:{'Content-Type':'application/json','Stripe-Signature':event.signature},body:event.raw.toString()+' '});expect((await POST(changed,context)).status).toBe(400);
 const large=new Request(request.url,{method:'POST',headers:{'Content-Type':'application/json'},body:'x'.repeat(524289)});expect((await POST(large,context)).status).toBe(413);
});
it('does not acknowledge a webhook until both durable event records have committed',async()=>{
 const saved=await open(),event=signedStripeEvent(fixture.sessions.get(saved.sessionId)!,secret),context={params:Promise.resolve({path:['stripe','webhooks',connectionId]})};await query("CREATE FUNCTION kff.synthetic_webhook_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Synthetic webhook storage failure'; END $$");await query('CREATE TRIGGER synthetic_webhook_failure BEFORE INSERT ON kff.stripe_events FOR EACH ROW EXECUTE FUNCTION kff.synthetic_webhook_failure()');
 const request=()=>new Request('http://127.0.0.1:3000/api/stripe/webhooks/'+connectionId,{method:'POST',headers:{'Content-Type':'application/json','Stripe-Signature':event.signature},body:new Uint8Array(event.raw)});
 try{expect((await POST(request(),context)).status).toBe(500);expect((await query("SELECT count(*)::int AS n FROM kff.inbound_events WHERE source_kind='stripe' AND source_key=$1",[connectionId+'/'+event.payload.id]))[0].n).toBe(0);}finally{await query('DROP TRIGGER synthetic_webhook_failure ON kff.stripe_events');await query('DROP FUNCTION kff.synthetic_webhook_failure()');}
 expect((await POST(request(),context)).status).toBe(200);
});
it('fences an expired event worker so its late observation cannot overwrite the new owner',async()=>{
 const saved=await open();fixture.pay(saved.sessionId,true);const event=await webhook(saved.sessionId);let release!:()=>void,ready!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),started=new Promise<void>(resolve=>ready=resolve);
 const slow=async()=>({...fixture,isSynthetic:true,identity:()=>fixture.identity(),createSession:fixture.createSession.bind(fixture),retrieveIntent:fixture.retrieveIntent.bind(fixture),retrieveSession:async(id:string)=>{const snapshot=await fixture.retrieveSession(id);ready();await gate;return snapshot;}});
 const first=processStripeEvent(event.id,slow);await started;await query("UPDATE kff.stripe_events SET lease_until=clock_timestamp()-interval '1 second' WHERE id=$1",[event.id]);fixture.pay(saved.sessionId);try{await processStripeEvent(event.id,fixture.factory);}finally{release();await first;}
 expect((await paymentWorkspace(scope)).checkouts[0].state).toBe('PAID');expect((await paymentWorkspace(scope)).verified).toHaveLength(1);
});
