import {randomUUID} from 'node:crypto';
import {spawn} from 'node:child_process';
import {beforeAll,beforeEach,afterEach,afterAll,it,expect} from 'vitest';
import {migrate} from '../../scripts/migrate';
import {seed,localIds} from '../../scripts/seed';
import {query,scoped,closePool} from '../../packages/database/src/index';
import type {Scope} from '../../packages/contracts/src/index';
import {createSiteChannel,beginVisitorSession,receiveVisitorMessage,inboxConversation} from '../../packages/core/src/inbox';
import {saveProductVersion,controlProduct,previewOrder,confirmOrder,ownedOrderDetail} from '../../packages/core/src/orders';
import {registerStripeConnection,queueStripeCheckout,receiveStripeWebhook,paymentWorkspace,controlStripeConnection} from '../../packages/core/src/payments';
import {processStripeCheckout,processStripeEvent} from '../../packages/core/src/payment-worker';
import {queueRefund,financialWorkspace,cancelUnsubmittedRefund,requestFinancialRecheck,recordFinancialAdjustment,reverseFinancialAdjustment} from '../../packages/core/src/refunds';
import {processRefundLedger} from '../../packages/core/src/refund-worker';
import {StripeFixture,syntheticStripeCredentials} from '../helpers/stripe-fixture';
import {StripeFinancialFixture,signedFinancialEvent} from '../helpers/stripe-financial-fixture';
import {POST} from '../../apps/web/app/api/[[...path]]/route';
const scope:Scope={organization_id:localIds.organization,brand_id:localIds.brand,user_id:localIds.user,role:'admin'};
let fixture:StripeFixture,finance:StripeFinancialFixture,ref:string,secret:string,connectionId:string,paymentId:string,orderId:string;
async function workspace(){return financialWorkspace(scope,paymentId);}
async function input(amount='500'){const data=await workspace();return {request_id:randomUUID(),expected_version:data.ledger.version,amount_minor:amount,confirmed_available_minor:data.available_minor,reason:'Synthetic approved refund',provider_reason:'requested_by_customer' as const,confirmation:'REFUND_CONFIRMED_AMOUNT' as const};}
async function queue(amount='500'){return queueRefund(scope,paymentId,await input(amount));}
async function sync(){return processRefundLedger(paymentId,finance.factory);}
async function event(object:unknown,type='refund.updated',changes:Record<string,unknown>={}){const signed=signedFinancialEvent(object,secret,type,changes);await receiveStripeWebhook(connectionId,signed.raw,signed.signature);const id=(await query('SELECT id FROM kff.stripe_events WHERE provider_event_id=$1',[signed.payload.id]))[0].id as string;return {...signed,id};}
async function receive(object:unknown,type='refund.updated'){const value=await event(object,type);await processStripeEvent(value.id,fixture.factory,finance.factory);return value.id;}
async function adjustment(amount='100'){const data=await workspace();return {request_id:randomUUID(),expected_version:data.ledger.version,amount_minor:amount,direction:'DEBIT' as const,currency:'USD',reason:'Synthetic accounting evidence',evidence_ref:'synthetic/'+randomUUID(),dispute_id:null,confirmation:'RECORD_ACCOUNTING_ADJUSTMENT' as const};}
beforeAll(async()=>{const name=(await query('SELECT current_database() AS name'))[0].name;if(name!==process.env.KFF_TEST_DATABASE||!/^kff_test_[a-f0-9]{20}$/.test(name))throw new Error('Isolated database required');await migrate();await seed();});
beforeEach(async()=>{
 await query('TRUNCATE kff.stripe_connections,kff.products,kff.order_previews,kff.commerce_currencies CASCADE');await query('UPDATE kff.brands SET outbound_paused=false');await query('UPDATE kff.organizations SET outbound_paused=false');await query("UPDATE kff.memberships SET role='admin' WHERE user_id=$1 AND brand_id=$2",[scope.user_id,scope.brand_id]);
 fixture=new StripeFixture();ref='KFF_STRIPE_'+randomUUID().slice(0,8).toUpperCase();secret=syntheticStripeCredentials(ref,{organization_id:scope.organization_id,brand_id:scope.brand_id,stripe_account_id:fixture.accountId}).secret;connectionId=(await registerStripeConnection(scope,{request_id:randomUUID(),name:'Synthetic refund provider',stripe_account_id:fixture.accountId,mode:'TEST',credential_ref:ref},fixture.factory)).id;
 const channel=await createSiteChannel(scope,{request_id:randomUUID(),name:'Synthetic refund inquiry',is_synthetic:true,session_hours:1,reply_window_hours:1,sessions_per_minute:10,messages_per_minute:20}),visitor=await beginVisitorSession(channel.id),receipt=await receiveVisitorMessage(channel.id,visitor.token,{client_message_id:randomUUID(),body:'Synthetic refund inquiry',display_name:'Synthetic refund buyer',client_sent_at:null}),customer=(await inboxConversation(scope,receipt.message.conversation_id)).conversation.customer_id;
 const product=await saveProductVersion(scope,{request_id:randomUUID(),sku:'REF-'+randomUUID().slice(0,8),name:'Synthetic refund product',currency:'USD',minor_unit_exponent:2,precision_source:'Synthetic USD precision',unit_amount_minor:'2500',delivery_scope:'Synthetic report only',terms:'No real purchase'});await controlProduct(scope,product.product_id,{request_id:randomUUID(),expected_version:1,state:'ACTIVE',reason:'Synthetic product review'});
 const preview=await previewOrder(scope,{request_id:randomUUID(),customer_id:customer,conversation_id:null,items:[{product_id:product.product_id,quantity:1}]}),order=await confirmOrder(scope,{request_id:randomUUID(),preview_id:preview.id,preview_hash:preview.snapshot_hash,confirmed_total_minor:'2500',currency:'USD',confirmation:'CREATE_THIS_ORDER'});orderId=order.id;
 const checkout=await queueStripeCheckout(scope,order.id,{request_id:randomUUID(),connection_id:connectionId,expected_version:order.version,snapshot_hash:order.snapshot_hash,confirmation:'CREATE_STRIPE_CHECKOUT'});await processStripeCheckout(checkout.id,fixture.factory);const sessionId=(await paymentWorkspace(scope,order.id)).checkouts[0].provider_session_id!;fixture.pay(sessionId);await processStripeCheckout(checkout.id,fixture.factory);const payment=(await paymentWorkspace(scope,order.id)).verified[0];paymentId=payment.id;finance=new StripeFinancialFixture(fixture.accountId,fixture.intents.get(payment.provider_intent_id)!);await sync();
});
afterEach(()=>{for(const suffix of ['API_KEY','WEBHOOK_SECRETS','ORGANIZATION_ID','BRAND_ID','ACCOUNT_ID'])delete process.env[ref+'_'+suffix];});afterAll(closePool);
it('serializes concurrent partial requests, holds their amounts and replays only identical requests',async()=>{const value=await input('1600'),results=await Promise.all(Array.from({length:5},()=>queueRefund(scope,paymentId,value)));expect(new Set(results.map(row=>row.id)).size).toBe(1);expect(await workspace()).toMatchObject({reserved_minor:'1600',available_minor:'900',refunded_minor:'0'});await expect(queueRefund(scope,paymentId,{...value,amount_minor:'1500'})).rejects.toMatchObject({code:'IDEMPOTENCY_CONFLICT'});const fresh=await input('700'),races=await Promise.allSettled([queueRefund(scope,paymentId,fresh),queueRefund(scope,paymentId,{...fresh,request_id:randomUUID()})]);expect(races.filter(row=>row.status==='fulfilled')).toHaveLength(1);expect((await workspace()).available_minor).toBe('200');await expect(queue('201')).rejects.toMatchObject({code:'REFUND_AMOUNT_EXCEEDED'});});
it('supports multiple partial successes up to the exact total without changing payment or delivery facts',async()=>{finance.nextStatus='succeeded';await queue('1029');await sync();expect(await workspace()).toMatchObject({refunded_minor:'1029',available_minor:'1471',net_after_refunds_minor:'1471',reserved_minor:'0'});await queue('1471');await sync();await sync();const data=await workspace();expect(data).toMatchObject({refunded_minor:'2500',available_minor:'0',net_after_refunds_minor:'0'});expect(data.postings).toHaveLength(2);expect(data.refunds).toHaveLength(2);expect(data.payment.mode).toBe('TEST');await expect(queue('1')).rejects.toMatchObject({code:'REFUND_AMOUNT_EXCEEDED'});expect((await ownedOrderDetail(scope,orderId)).order).toMatchObject({payment_state:'VERIFIED_TEST_PAID',state:'OPEN'});});
it('reserves pending and requires-action amounts, releases failed/canceled amounts and retains every observation',async()=>{await queue('800');await sync();const remote=[...finance.refunds.values()][0];expect(await workspace()).toMatchObject({reserved_minor:'0',provider_reserved_minor:'800',available_minor:'1700',refunded_minor:'0'});remote.status='requires_action';await receive(remote);expect((await workspace()).requests[0].state).toBe('REQUIRES_ACTION');remote.status='failed';remote.failure_reason='lost_or_stolen_card';await receive(remote,'refund.failed');expect(await workspace()).toMatchObject({available_minor:'2500',refunded_minor:'0'});finance.nextStatus='canceled';await queue('100');await sync();expect((await workspace()).available_minor).toBe('2500');expect((await workspace()).observations).toHaveLength(4);});
it('requeries old callbacks and records success, bank return, renewed success and later failure without double reduction',async()=>{await queue('700');await sync();const remote=[...finance.refunds.values()][0],old=await event(remote);remote.status='succeeded';const success=await receive(remote);expect(await workspace()).toMatchObject({refunded_minor:'700'});await processStripeEvent(old.id,fixture.factory,finance.factory);await processStripeEvent(success,fixture.factory,finance.factory);expect((await workspace()).postings).toHaveLength(1);remote.status='requires_action';await receive(remote);expect((await workspace()).refunded_minor).toBe('0');remote.status='succeeded';await receive(remote);expect((await workspace()).refunded_minor).toBe('700');remote.status='failed';await receive(remote,'refund.failed');expect((await workspace()).refunded_minor).toBe('0');const data=await workspace();expect(data.postings).toHaveLength(4);expect(new Set(data.postings.map(row=>row.observation_id)).size).toBe(4);expect(data.observations.filter(row=>row.source_event_id)).toHaveLength(4);expect(finance.calls).toHaveLength(1);});
it('recovers a lost POST acknowledgement by original metadata without issuing a new refund',async()=>{finance.loseResponse=1;const request=await queue();await sync();expect((await workspace()).requests[0]).toMatchObject({id:request.id,state:'SUBMITTING',provider_refund_id:null});expect((await workspace()).reserved_minor).toBe('500');await sync();expect(finance.refunds.size).toBe(1);expect(finance.calls).toHaveLength(1);expect((await workspace()).requests[0].provider_refund_id).toBe([...finance.refunds.keys()][0]);expect(finance.calls[0]).toMatchObject({key:'kff-refund-'+request.id,input:{amount:500,reason:'requested_by_customer',metadata:{kff_payment_id:paymentId,kff_order_id:orderId,kff_brand_id:scope.brand_id}}});});
it('reuses identical POST parameters if a lost response is also absent from provider lists',async()=>{finance.loseResponse=1;await queue();await sync();finance.omitRefunds=true;await sync();expect(finance.calls).toHaveLength(2);expect(finance.calls[0]).toEqual(finance.calls[1]);expect(finance.refunds.size).toBe(1);expect((await workspace()).available_minor).toBe('2000');});
it('binds a returned refund before a failed follow-up query and recovers the same object after a restart',async()=>{await queue();finance.afterCreate=async()=>{finance.unavailable=true;};await sync();expect((await workspace()).requests[0].provider_refund_id).toBe([...finance.refunds.keys()][0]);finance.unavailable=false;finance.afterCreate=null;finance.omitRefunds=true;await sync();expect(finance.calls).toHaveLength(1);expect((await workspace()).requests[0].state).toBe('PENDING');});
it('retains unknown refunds beyond the safe idempotency window and forbids local cancellation after submission',async()=>{const request=await queue();await query("UPDATE kff.refund_requests SET state='SUBMITTING',submitted_at=clock_timestamp()-interval '25 hours' WHERE id=$1",[request.id]);await sync();expect(finance.calls).toHaveLength(0);expect((await workspace()).requests[0]).toMatchObject({state:'NEEDS_HUMAN',error_code:'STRIPE_IDEMPOTENCY_WINDOW_EXPIRED'});await expect(cancelUnsubmittedRefund(scope,request.id,{request_id:randomUUID(),expected_version:(await workspace()).ledger.version,reason:'Cannot prove no refund'})).rejects.toMatchObject({code:'REFUND_ALREADY_SUBMITTED'});await requestFinancialRecheck(scope,paymentId,{request_id:randomUUID(),reason:'Query original only'});await sync();expect(finance.calls).toHaveLength(0);expect((await workspace()).reserved_minor).toBe('500');});
it('releases a definite first POST rejection but preserves unknown results after exhausted transient retries',async()=>{finance.rejectCreate=true;await queue('100');await sync();expect((await workspace()).requests[0].state).toBe('FAILED');expect((await workspace()).available_minor).toBe('2500');finance.rejectCreate=false;await sync();const request=await queue('300');finance.loseResponse=1;await sync();finance.omitRefunds=true;finance.rejectCreate=true;await sync();expect((await workspace()).requests.find(row=>row.id===request.id)).toMatchObject({state:'NEEDS_HUMAN'});expect((await workspace()).reserved_minor).toBe('300');});
it('fences expired owners after remote creation and lets a new owner recover the original refund',async()=>{const request=await queue(),newToken=randomUUID();finance.afterCreate=async()=>{await query("UPDATE kff.refund_ledgers SET lease_token=$2,lease_until=clock_timestamp()+interval '90 seconds' WHERE payment_id=$1",[paymentId,newToken]);};await sync();expect((await query('SELECT lease_token FROM kff.refund_ledgers WHERE payment_id=$1',[paymentId]))[0].lease_token).toBe(newToken);expect((await workspace()).requests[0].provider_refund_id).toBeNull();await query("UPDATE kff.refund_ledgers SET lease_until=clock_timestamp()-interval '1 second' WHERE payment_id=$1",[paymentId]);finance.afterCreate=null;await sync();expect(finance.calls).toHaveLength(1);expect((await workspace()).requests[0]).toMatchObject({id:request.id,state:'PENDING'});});
it('accounts for dashboard refunds and paginates beyond 100 objects while rejecting cursor loops',async()=>{for(let n=0;n<105;n++)finance.addRefund(1,'succeeded');await sync();expect(await workspace()).toMatchObject({refunded_minor:'105',available_minor:'2395'});expect(finance.pages.some(cursor=>cursor!==undefined)).toBe(true);expect((await query('SELECT count(*)::int AS n FROM kff.stripe_refunds WHERE payment_id=$1',[paymentId]))[0].n).toBe(105);finance.loopPages=true;await sync();expect((await workspace()).ledger.error_code).toBe('STRIPE_PAGINATION_INVALID');expect((await workspace()).refunded_minor).toBe('105');await expect(queue()).rejects.toMatchObject({code:'REFUND_RECONCILIATION_REQUIRED'});});
it('fails closed on new provider statuses, identity, immutable amount and current payment metadata mismatches',async()=>{const remote=finance.addRefund(100,'new_provider_status');await sync();expect((await workspace()).ledger).toMatchObject({refund_blocked:true,error_code:'STRIPE_FINANCIAL_STATUS_UNKNOWN'});remote.status='pending';await sync();remote.amount=101;await sync();expect((await workspace()).ledger.error_code).toBe('STRIPE_REFUND_OBJECT_MISMATCH');remote.amount=100;remote.charge='ch_wrong';await sync();expect((await workspace()).ledger.error_code).toBe('STRIPE_REFUND_OBJECT_MISMATCH');remote.charge=finance.payment.latest_charge!.id;finance.payment.metadata.kff_brand_id=randomUUID();await sync();expect((await workspace()).ledger.error_code).toBe('STRIPE_PAYMENT_OBJECT_MISMATCH');expect((await workspace()).refunded_minor).toBe('0');});
it('rejects bad signed-event mode, amount and forged KFF request metadata before any financial posting',async()=>{const remote=finance.addRefund(200,'succeeded'),wrong=signedFinancialEvent(remote,secret,'refund.updated',{livemode:true});await expect(receiveStripeWebhook(connectionId,wrong.raw,wrong.signature)).rejects.toMatchObject({code:'STRIPE_MODE_MISMATCH'});const bad=await event({...remote,amount:201});await processStripeEvent(bad.id,fixture.factory,finance.factory);expect((await query('SELECT state FROM kff.stripe_events WHERE id=$1',[bad.id]))[0].state).toBe('REJECTED');expect((await workspace()).postings).toHaveLength(0);remote.metadata={kff_refund_request_id:randomUUID(),kff_payment_id:paymentId,kff_order_id:orderId,kff_brand_id:scope.brand_id};await sync();expect((await workspace()).ledger.error_code).toBe('STRIPE_REFUND_REQUEST_MISMATCH');expect((await workspace()).postings).toHaveLength(0);});
it('commits financial objects, postings and event acknowledgement atomically after a persistence failure',async()=>{const remote=finance.addRefund(250,'succeeded'),signed=signedFinancialEvent(remote,secret),context={params:Promise.resolve({path:['stripe','webhooks',connectionId]})};const response=await POST(new Request('http://127.0.0.1:3000/api/stripe/webhooks/'+connectionId,{method:'POST',headers:{'content-type':'application/json','stripe-signature':signed.signature},body:new Uint8Array(signed.raw)}),context);expect(response.status).toBe(200);const duplicate=await receiveStripeWebhook(connectionId,signed.raw,signed.signature);expect(duplicate.duplicate).toBe(true);const id=(await query('SELECT id FROM kff.stripe_events WHERE provider_event_id=$1',[signed.payload.id]))[0].id;
 await query("CREATE FUNCTION kff.synthetic_refund_failure() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Synthetic refund persistence failure'; END $$");await query('CREATE TRIGGER synthetic_refund_failure BEFORE INSERT ON kff.refund_postings FOR EACH ROW EXECUTE FUNCTION kff.synthetic_refund_failure()');try{await processStripeEvent(id,fixture.factory,finance.factory);expect((await workspace()).postings).toHaveLength(0);expect((await workspace()).refunds).toHaveLength(0);expect((await query('SELECT state FROM kff.stripe_events WHERE id=$1',[id]))[0].state).toBe('PENDING');}finally{await query('DROP TRIGGER synthetic_refund_failure ON kff.refund_postings');await query('DROP FUNCTION kff.synthetic_refund_failure()');}await processStripeEvent(id,fixture.factory,finance.factory);expect((await workspace()).refunded_minor).toBe('250');expect((await query('SELECT state FROM kff.stripe_events WHERE id=$1',[id]))[0].state).toBe('PROCESSED');});
it('keeps disputes and provider balance movements distinct, including different-currency fees and later reinstatement',async()=>{const dispute=finance.addDispute();dispute.currency='cad';dispute.amount=3100;dispute.balance_transactions=[{id:'txn_'+randomUUID().replaceAll('-',''),object:'balance_transaction',currency:'eur',amount:-1800,fee:1500,net:-3300,type:'adjustment',created:Math.floor(Date.now()/1000)}];await receive(dispute,'charge.dispute.created');let data=await workspace();expect(data.ledger.refund_blocked).toBe(true);expect(data.refunded_minor).toBe('0');expect(data.net_with_manual_adjustments_minor).toBe('2500');expect(data.dispute_balances[0]).toMatchObject({currency:'EUR',amount_minor:'-1800',fee_minor:'1500',net_minor:'-3300'});const old=await event(dispute,'charge.dispute.updated');dispute.status='won';dispute.is_charge_refundable=true;dispute.balance_transactions.push({id:'txn_'+randomUUID().replaceAll('-',''),object:'balance_transaction',currency:'eur',amount:1800,fee:0,net:1800,type:'adjustment',created:Math.floor(Date.now()/1000)});await receive(dispute,'charge.dispute.funds_reinstated');await processStripeEvent(old.id,fixture.factory,finance.factory);data=await workspace();expect(data.disputes[0].provider_status).toBe('won');expect(data.dispute_balances).toHaveLength(2);expect(data.observations).toHaveLength(2);expect(data.ledger.refund_blocked).toBe(false);dispute.balance_transactions[0].amount=-1801;await sync();expect((await workspace()).ledger.error_code).toBe('STRIPE_BALANCE_MISMATCH');});
it('stops new POSTs on connection, brand, organization pause and revoked administrator authority while reconciling incoming refunds',async()=>{await queue();await controlStripeConnection(scope,connectionId,{request_id:randomUUID(),expected_version:1,outbound_enabled:false,reason:'Synthetic pause'});await sync();expect(finance.calls).toHaveLength(0);const remote=finance.addRefund(100,'succeeded');await receive(remote);expect((await workspace()).refunded_minor).toBe('100');await controlStripeConnection(scope,connectionId,{request_id:randomUUID(),expected_version:2,outbound_enabled:true,reason:'Synthetic resume'});
 for(const table of ['brands','organizations']){await query('UPDATE kff.'+table+' SET outbound_paused=true');await sync();expect(finance.calls).toHaveLength(0);await query('UPDATE kff.'+table+' SET outbound_paused=false');}await query("UPDATE kff.memberships SET role='operator' WHERE user_id=$1 AND brand_id=$2",[scope.user_id,scope.brand_id]);await sync();expect(finance.calls).toHaveLength(0);expect((await workspace()).requests[0].state).toBe('NEEDS_HUMAN');expect((await workspace()).reserved_minor).toBe('500');});
it('allows an authorized, unsubmitted cancellation once and does not call Stripe',async()=>{const request=await queue(),value={request_id:randomUUID(),expected_version:(await workspace()).ledger.version,reason:'Customer withdrew before submission'};await cancelUnsubmittedRefund(scope,request.id,value);await cancelUnsubmittedRefund(scope,request.id,value);await sync();expect((await workspace()).available_minor).toBe('2500');expect((await workspace()).requests[0].state).toBe('CANCELED');expect(finance.calls).toHaveLength(0);});
it('records immutable adjustments with explicit currency and unique evidence, exact one-time reversal and preserved originals',async()=>{const dispute=finance.addDispute();await sync();const value={...(await adjustment('150')),dispute_id:(await workspace()).disputes[0].id},saved=await recordFinancialAdjustment(scope,paymentId,value);expect(await recordFinancialAdjustment(scope,paymentId,value)).toEqual(saved);expect(await workspace()).toMatchObject({manual_adjustments_minor:'-150',net_with_manual_adjustments_minor:'2350',available_minor:'2500',refunded_minor:'0'});await expect(recordFinancialAdjustment(scope,paymentId,{...value,request_id:randomUUID(),expected_version:(await workspace()).ledger.version})).rejects.toMatchObject({code:'DUPLICATE_ADJUSTMENT_REFERENCE'});await expect(recordFinancialAdjustment(scope,paymentId,{...(await adjustment()),currency:'EUR'})).rejects.toMatchObject({code:'ADJUSTMENT_CURRENCY_MISMATCH'});await expect(recordFinancialAdjustment(scope,paymentId,{...(await adjustment()),dispute_id:randomUUID()})).rejects.toMatchObject({code:'NOT_FOUND'});const reversal={request_id:randomUUID(),expected_version:(await workspace()).ledger.version,reason:'Synthetic evidence correction',evidence_ref:'reverse/'+randomUUID(),confirmation:'REVERSE_THIS_ADJUSTMENT' as const},reversed=await reverseFinancialAdjustment(scope,saved.id,reversal);expect(await reverseFinancialAdjustment(scope,saved.id,reversal)).toEqual(reversed);expect((await workspace()).manual_adjustments_minor).toBe('0');expect((await workspace()).adjustments).toHaveLength(2);await expect(reverseFinancialAdjustment(scope,saved.id,{...reversal,request_id:randomUUID(),evidence_ref:'another',expected_version:(await workspace()).ledger.version})).rejects.toMatchObject({code:'ADJUSTMENT_ALREADY_REVERSED'});await expect(reverseFinancialAdjustment(scope,reversed.id,{...reversal,request_id:randomUUID()})).rejects.toMatchObject({code:'ADJUSTMENT_REVERSAL_MISMATCH'});await expect(query('UPDATE kff.financial_adjustments SET amount_minor=-200 WHERE id=$1',[saved.id])).rejects.toThrow('IMMUTABLE');expect(dispute.balance_transactions).toHaveLength(0);expect(finance.calls).toHaveLength(0);});
it('enforces administrator writes, brand RLS, immutable requests and a fresh verified available amount',async()=>{await expect(queueRefund({...scope,role:'operator'},paymentId,await input())).rejects.toMatchObject({code:'FORBIDDEN_SCOPE'});await expect(recordFinancialAdjustment({...scope,role:'viewer'},paymentId,await adjustment())).rejects.toMatchObject({code:'FORBIDDEN_SCOPE'});const other={...scope,brand_id:randomUUID()};for(const table of ['refund_ledgers','refund_requests','stripe_refunds','stripe_disputes','financial_observations','refund_postings','financial_adjustments','dispute_balance_entries'])expect(await scoped(other,async client=>(await client.query('SELECT * FROM kff.'+table)).rows)).toEqual([]);await expect(financialWorkspace(other,paymentId)).rejects.toMatchObject({code:'NOT_FOUND'});const request=await queue();await expect(query('UPDATE kff.refund_requests SET amount_minor=1 WHERE id=$1',[request.id])).rejects.toThrow('IMMUTABLE_REFUND_REQUEST');await query("UPDATE kff.refund_ledgers SET synced_at=clock_timestamp()-interval '16 minutes' WHERE payment_id=$1",[paymentId]);await expect(queue()).rejects.toMatchObject({code:'REFUND_RECONCILIATION_REQUIRED'});expect(finance.calls).toHaveLength(0);});
it('recovers after the actual refund worker process dies after Stripe accepts creation but before acknowledgement',async()=>{
 await queue();async function worker(killAfterCreate:boolean){return new Promise<{code:number|null;killed:boolean}>((resolve,reject)=>{let killed=false,errors='';const child=spawn(process.execPath,['--import','tsx','tests/helpers/refund-process.ts',paymentId],{windowsHide:true,env:process.env,stdio:['ignore','ignore','pipe','ipc']});const timeout=setTimeout(()=>{child.kill();reject(new Error('Refund subprocess timeout'));},15000);child.stderr!.on('data',chunk=>errors+=String(chunk));child.on('error',reject);child.on('message',async(message:{id:number;method:string;args:unknown[]})=>{try{if(!['identity','retrievePayment','createRefund','retrieveRefund','listRefunds','retrieveDispute','listDisputes'].includes(message.method))throw new Error('Invalid fixture RPC');const method=finance[message.method as keyof StripeFinancialFixture] as (...args:unknown[])=>Promise<unknown>,value=await method.apply(finance,message.args);if(killAfterCreate&&message.method==='createRefund'){killed=true;child.kill();}else if(child.connected)child.send({id:message.id,value});}catch{if(child.connected)child.send({id:message.id,error:{code:'STRIPE_UNAVAILABLE'}});}});child.on('exit',code=>{clearTimeout(timeout);if(!killed&&code!==0)reject(new Error('Refund subprocess failed: '+errors));else resolve({code,killed});});});}
 expect((await worker(true)).killed).toBe(true);expect(finance.refunds.size).toBe(1);expect((await workspace()).requests[0]).toMatchObject({state:'SUBMITTING',provider_refund_id:null});expect((await workspace()).reserved_minor).toBe('500');await query("UPDATE kff.refund_ledgers SET lease_until=clock_timestamp()-interval '1 second' WHERE payment_id=$1",[paymentId]);expect((await worker(false)).code).toBe(0);expect(finance.calls).toHaveLength(1);expect((await workspace()).requests[0].state).toBe('PENDING');expect((await workspace()).available_minor).toBe('2000');
});
it('applies a returned successful refund before its replacement debit when the original payment was fully refunded',async()=>{const old=finance.addRefund(2500,'succeeded');old.id='re_Zprevious';finance.refunds.clear();finance.refunds.set(old.id,old);await sync();expect((await workspace()).refunded_minor).toBe('2500');old.status='failed';const replacement=finance.addRefund(2500,'succeeded');finance.refunds.delete(replacement.id);replacement.id='re_Areplacement';finance.refunds.set(replacement.id,replacement);await sync();const data=await workspace();expect(data.ledger.error_code).toBeNull();expect(data.refunded_minor).toBe('2500');expect(data.postings).toHaveLength(3);expect(data.postings.filter(row=>row.kind==='REFUND_REVERSAL')).toHaveLength(1);});
it('blocks stale local reservations when an external refund reduces available funds before submission',async()=>{await queue('1500');finance.addRefund(1500,'pending');await sync();expect(finance.calls).toHaveLength(0);expect((await workspace()).requests[0]).toMatchObject({state:'NEEDS_HUMAN',error_code:'REFUND_AMOUNT_EXCEEDED'});expect((await workspace()).reserved_minor).toBe('1500');expect((await workspace()).available_minor).toBe('0');});
it('preserves a successful posting through unknown provider status without releasing its refund amount',async()=>{const refund=finance.addRefund(200,'succeeded');await sync();refund.status='future_status';await sync();expect(await workspace()).toMatchObject({refunded_minor:'200',available_minor:'2300',ledger:{refund_blocked:true}});expect((await workspace()).postings).toHaveLength(1);refund.status='failed';await sync();expect((await workspace()).refunded_minor).toBe('0');expect((await workspace()).postings).toHaveLength(2);});
