'use client';
import {discoveryIsSynthetic} from '../../../packages/contracts/src/acquisition';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import type {Workspace} from '@kff/core/service';
import type {acquisitionWorkspace} from '@kff/core/acquisition';
import {businessRequest,businessTime} from './business-ui';
import {useRequestKey} from './use-request-key';
import {AcquisitionProviderPanel} from './acquisition-provider-panel';
import {AcquisitionCandidates} from './acquisition-candidates';

type State=Awaited<ReturnType<typeof acquisitionWorkspace>>;
const ageNames:Record<string,string>={RECENT:'范围内',OLDER:'已超期',UNKNOWN:'时间待核对',UNRESTRICTED:'未设时间范围'};
const split=(text:FormDataEntryValue|null)=>String(text??'').split(/[,，\n]/).map(s=>s.trim()).filter(Boolean);
const names:Record<string,string>={DRAFT:'待审核草稿',REJECTED:'已拒绝草稿',NEW:'新线索',QUALIFIED:'值得跟进',DISMISSED:'已排除',OPTED_OUT:'已退出',QUEUED:'排队中',RUNNING:'采集中',COMPLETED:'本次采集结束',PARTIAL:'部分结果',FAILED:'失败',CANCELED:'已停止',VERIFIED_SUCCEEDED:'确认已提交',UNKNOWN_OUTCOME:'结果未知，请核验原动作',BLOCKED:'已阻止',APPROVED:'待试验许可',COMMENT_REPLY:'公开评论回复',PRIVATE_REPLY:'评论触发私信',PAUSED:'已暂停',ACTIVE:'监控中'};
export function AcquisitionWorkbench({data}:{data:Workspace}){
  const accountTools=useRef<HTMLDetailsElement>(null);
  const [state,setState]=useState<State|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [account,setAccount]=useState(''),[provider,setProvider]=useState('LOCAL_FIXTURE'),[strategy,setStrategy]=useState('COMMENTS'),[selectedMonitor,setSelectedMonitor]=useState(''),[selectedLead,setSelectedLead]=useState('');
  const [filter,setFilter]=useState(''),[minScore,setMinScore]=useState(0),[leadState,setLeadState]=useState('ALL'),[ageState,setAgeState]=useState('ALL');
  const key=useRequestKey(),admin=data.scope.role==='admin',write=data.scope.role!=='viewer';
  const refresh=useCallback(async()=>{setState(await businessRequest<State>('acquisition'));},[]);
  useEffect(()=>{if(selectedLead)document.getElementById('acquisition-lead-review')?.scrollIntoView({block:'start'});},[selectedLead]);
  useEffect(()=>{let active=true;const load=async()=>{try{const next=await businessRequest<State>('acquisition');if(active)setState(next);}catch(e){if(active)setError(e instanceof Error?e.message:'读取失败');}};void load();const timer=setInterval(()=>void load(),5000);return()=>{active=false;clearInterval(timer);};},[]);
  const post=async(path:string,payload:Record<string,unknown>,message:string)=>{
    setBusy(true);setError('');try{await businessRequest(path,{...payload,request_id:key.forPayload({path,payload})});key.confirmed();setNotice(message);await refresh();}catch(e){setError(e instanceof Error?e.message:'操作失败');}finally{setBusy(false);}
  };
  if(!state)return <p role="status">{error||'正在读取获客工作台…'}</p>;
  const chosen=state.accounts.find(a=>a.id===account)??state.accounts[0],monitor=state.monitors.find(m=>m.id===selectedMonitor),lead=state.leads.find(l=>l.id===selectedLead);
  const leadBrowser=lead?.config.discovery.provider==='LOCAL_BROWSER'&&lead.config.discovery.browser?.template==='facebook-comments-dom-v1';
  const priorDraft=lead&&state.actions.find(a=>a.lead_id===lead.id&&!a.superseded_at&&['DRAFT','REJECTED'].includes(a.status)&&!a.run_id);
  const personalAccount = chosen?.platform === 'facebook' && chosen.account_type === 'profile' && !chosen.is_synthetic;
  const actualProvider=chosen?.is_synthetic?(provider==='LOCAL_BROWSER'?'LOCAL_BROWSER':'LOCAL_FIXTURE'):personalAccount&&provider!=='DATA_PROVIDER'?'LOCAL_BROWSER':provider==='LOCAL_FIXTURE'||provider==='LOCAL_BROWSER'?'META_API':provider;
  const personalBrowser = personalAccount && actualProvider === 'LOCAL_BROWSER';
  // Mirrors acquisition.ts:172-173 (outreach) and :245 (automation scheduler). Without
  // these the forms rendered and saved for leads/monitors the server always refuses, so
  // every submit was a 409 and the success notice was a lie.
  const leadDiscovery = lead?.config.discovery;
  const leadBrowserAction = leadDiscovery?.provider === 'LOCAL_BROWSER' && leadDiscovery.browser?.template === 'facebook-comments-dom-v1';
  const canPrepareOutreach = Boolean(leadDiscovery) && leadDiscovery!.strategy === 'COMMENTS' && (leadBrowserAction || ['LOCAL_FIXTURE', 'META_API'].includes(leadDiscovery!.provider));
  const monitorDiscovery = monitor?.config.discovery;
  const canAutomate = Boolean(monitorDiscovery) && monitorDiscovery!.strategy === 'COMMENTS' && ['LOCAL_FIXTURE', 'META_API'].includes(monitorDiscovery!.provider);
  const actualStrategy = personalBrowser && !['KEYWORD','COMMENTS','PAGE'].includes(strategy) ? 'KEYWORD' : strategy;
  const browserSearch = personalBrowser && actualStrategy === 'KEYWORD';
  const browserPage = personalBrowser && actualStrategy === 'PAGE';
  const browserComments = personalBrowser && actualStrategy === 'COMMENTS';
  const collectionEnvironments=state.environments.filter(e=>e.account_id===chosen?.id&&e.browser_configured);
  const environments=state.environments.filter(e=>e.account_id===(lead?.account_id??monitor?.account_id??chosen?.id)&&(!leadBrowser||e.id===lead?.config.discovery.browser?.environment_id));
  const filtered=state.leads.filter(l=>(!selectedMonitor||l.monitor_id===selectedMonitor)&&(ageState==='ALL'||l.publication_age===ageState)&&l.score>=minScore&&(leadState==='ALL'||l.state===leadState)&&JSON.stringify(l.fields).toLowerCase().includes(filter.toLowerCase()));
  function saveMonitor(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);if(!chosen)return;void post('acquisition/monitors',{title:f.get('title'),account_id:chosen.id,discovery:{platform:chosen.platform,strategy:actualStrategy,provider:actualProvider,...(actualProvider==='LOCAL_BROWSER'?{browser:{environment_id:f.get('collection_environment'),...(browserComments?{comment_order:f.get('comment_order')}:{}),template:personalBrowser?(browserSearch?'facebook-search-dom-v1':browserPage?'facebook-page-dom-v1':'facebook-comments-dom-v1'):'fixture-discovery-dom-v1'}}:{}),keywords:split(f.get('keywords')),max_age_days:f.get('max_age_days')?Number(f.get('max_age_days')):undefined,exclusions:split(f.get('exclusions')),target:browserSearch?'':String(f.get('target')??''),processing_basis:f.get('basis'),...(!chosen.is_synthetic&&actualProvider!=='LOCAL_BROWSER'?{credential_ref:chosen.credential_ref??undefined,graph_version:String(f.get('version')??'')||undefined}:{})},...(personalBrowser&&(browserSearch||browserPage)&&f.get('continue_comments')==='on'?{comment_continuation:{allowed_source_types:['POST','REEL'],max_sources_per_scan:Number(f.get('sources_per_scan')),max_sources_total:Number(f.get('sources_total')),source_lifetime_hours:Number(f.get('source_hours')),comment_order:'VISIBLE_WINDOW'}}:{}),interval_minutes:Number(f.get('interval')),max_records:Number(f.get('records')),page_size:Number(f.get('page_size')),max_pages:browserComments&&f.get('comment_order')==='VISIBLE_WINDOW'?1:20,retention_days:14},'监控已保存。点击扫描一次，或启动持续监控。');}
  return <div className="business-workbench acquisition-workbench">
    {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <AcquisitionCandidates data={state.candidates} accounts={state.accounts} environments={state.environments} admin={admin} write={write} busy={busy} post={post} onPrepare={id=>{if(accountTools.current)accountTools.current.open=true;setSelectedLead(id);}} onMonitorPrepared={async id=>{await refresh();setSelectedMonitor(id);setNotice('只读监控已准备并保持暂停。请核对来源后扫描一次，找到原评论再审核。');if(accountTools.current){accountTools.current.open=true;accountTools.current.scrollIntoView({block:'start'});}}}/>
    <details className="business-box acquisition-section" open={!state.external.sources.length}><summary>外部数据导入与来源明细</summary><AcquisitionProviderPanel data={state.external} admin={admin} write={write} busy={busy} connected={state.readiness.apify_configured} post={post}/></details>
    <details ref={accountTools} className="business-box acquisition-section" open={!state.external.sources.length}><summary>账号采集与合成验证</summary>
    <div className="business-counts"><div><span>监控来源</span><strong>{state.monitors.length}</strong></div><div><span>当前可见线索</span><strong>{state.leads.length}</strong></div><div><span>已确认动作</span><strong>{state.actions.filter(a=>a.state==='VERIFIED_SUCCEEDED').length}</strong></div></div>
    <section className="business-box acquisition-section"><h2>来源与接入状态</h2><p>{state.readiness.scope}</p><p>真实采集：{state.readiness.discovery_enabled?'已启用':'未启用'} · Apify：{state.readiness.apify_configured?'凭据已配置，采集结果待验收':'未连接'} · 其他数据服务：{state.readiness.provider_configured?'已配置，待实测覆盖':'未配置'} · 真实发送：{state.readiness.live_enabled?'已启用，仍需许可':'未启用'}</p><p>Apify 当前读取已完成的评论采集结果；重复扫描不会启动新抓取。个人账号浏览器支持单关键词公开搜索、指定公开帖子或 Reel 的评论，以及固定公共主页的帖子。所有浏览器采集仅覆盖本次可见窗口，主页排序不保证按发布时间；结果可能是同行推广，按原文待筛选。话题策略使用数据服务；Meta 直连只采集已授权自有帖子/媒体的评论。合成结果始终标记为本地验证。</p>
      {admin&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post('acquisition/fixtures',{platform:f.get('platform'),agent_id:f.get('agent')},'已建立独立合成账号与环境，可以创建监控。');}} className="acquisition-inline" aria-label="添加获客验证账号"><label>验证平台<select name="platform"><option value="facebook">Facebook</option><option value="instagram">Instagram</option></select></label><label>执行 Agent<select name="agent" required>{state.agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><button className="button" disabled={busy||!state.agents.length}>添加本地验证账号</button><a href="/accounts">登记真实账号</a></form>}
    </section>
    {admin&&<details className="business-box acquisition-section" open={!state.monitors.length}><summary>新建关键词 / 评论区 / 主页监控</summary><form onSubmit={saveMonitor} className="acquisition-grid" aria-label="创建获客监控">
      <label>监控名称<input name="title" required maxLength={120} placeholder="例如：关系咨询评论监控"/></label>
      <label>采集账号<select value={chosen?.id??''} onChange={e=>{setAccount(e.target.value);setProvider(state.accounts.find(a=>a.id===e.target.value)?.is_synthetic?'LOCAL_FIXTURE':'META_API');}} required>{state.accounts.map(a=><option key={a.id} value={a.id}>{a.display_name} · {a.platform} · {a.is_synthetic?'合成':'真实'}</option>)}</select></label>
      <label>来源类型<select value={actualProvider} onChange={e=>setProvider(e.target.value)}>{chosen?.is_synthetic?<><option value="LOCAL_FIXTURE">本地合成数据</option><option value="LOCAL_BROWSER">本地浏览器采集验证</option></>:<>{personalAccount?<option value="LOCAL_BROWSER">Facebook 浏览器公开内容</option>:<option value="META_API">Meta API 自有评论</option>}<option value="DATA_PROVIDER">Apify / 其他数据服务</option></>}</select></label>
      {actualProvider==='LOCAL_BROWSER'&&<label>采集环境<select name="collection_environment" required>{collectionEnvironments.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><small>{personalBrowser?'核对当前身份后读取公开可见结果；启用前请在能力页面登记当前实现证据。':'使用固定的本地合成评论页。'}<a href="/environments">配置浏览器环境</a></small></label>}
      <label>监控策略<select value={actualStrategy} onChange={e=>setStrategy(e.target.value)}><option value="COMMENTS">评论区</option><option value="KEYWORD">关键词搜索</option><option value="PAGE">主页 / 创作者监控</option>{!personalBrowser&&<option value="HASHTAG">话题 / Hashtag</option>}</select></label>
      {browserPage&&<p>只采集该主页发布的公开帖子和 Reels；精选重复项按链接去重。原始时间保留，不能据此保证抓到全部最新帖子。</p>}
      <label>{browserSearch?'搜索关键词（仅一个）':'关键词（逗号或换行分隔）'}<textarea name="keywords" required placeholder="marriage problem, feng shui"/></label><label>排除词<textarea name="exclusions" placeholder="招聘, giveaway"/></label>
      <label>{browserPage?'公开主页链接（数字 ID，以 / 结尾）':personalBrowser?'公开帖子或 Reel 链接（评论必填，去除参数并以 / 结尾）':actualProvider==='DATA_PROVIDER'?'来源标识（Apify 填 apify-run:运行ID）':'指定帖子或媒体 ID'}<input name="target" maxLength={300} placeholder={browserPage?'https://www.facebook.com/主页数字ID/':personalBrowser?'https://www.facebook.com/reel/视频ID/':actualProvider==='DATA_PROVIDER'?'apify-run:已成功的评论采集运行ID':'Meta 直连填写帖子或媒体 ID'} required={actualProvider==='META_API'||personalBrowser&&!browserSearch} disabled={browserSearch}/></label>
      {browserComments&&<label>评论读取顺序<select name="comment_order" defaultValue="NEWEST"><option value="NEWEST">由新到旧（需要排序控件）</option><option value="VISIBLE_WINDOW">当前可见窗口（无排序控件时）</option></select><small>可见窗口只读取一页，不声明按新旧排序或覆盖全部评论。</small></label>}
      {!chosen?.is_synthetic&&actualProvider!=='LOCAL_BROWSER'&&<label>Graph API 版本<input name="version" placeholder="填写当前已核实版本" required={actualProvider==='META_API'}/></label>}
      <label>扫描间隔（分钟）<input type="number" name="interval" min={5} max={10080} defaultValue={30} required/></label><label>每次读取上限<input type="number" name="records" min={1} max={1000} defaultValue={100} required/></label>
      <label>发布时间范围（最近天数）<input type="number" name="max_age_days" min={1} max={365} defaultValue={7} placeholder="留空不限"/><small>明确超期的内容不进入新候选；时间不足以判断时保留待核对。原始采集记录保留。</small></label>
      <label>每页读取上限<input type="number" name="page_size" min={1} max={100} defaultValue={25} required/></label>
      {personalBrowser&&(browserSearch||browserPage)&&<fieldset><legend>自动接续评论采集</legend><label><input type="checkbox" name="continue_comments"/> 从符合关键词和时间范围的帖子 / Reel 自动建立评论监控</label><label>每轮新增来源上限<input type="number" name="sources_per_scan" min={1} max={5} defaultValue={1}/></label><label>累计来源上限<input type="number" name="sources_total" min={1} max={50} defaultValue={5}/></label><label>来源有效小时<input type="number" name="source_hours" min={1} max={168} defaultValue={24}/></label><small>需填写发布时间范围。评论读取当前可见的一页，沿用账号、环境、关键词和读取上限。父监控暂停会停止子采集，达到累计上限后停止新增来源。</small></fieldset>}
      <label>来源使用依据<textarea name="basis" minLength={10} maxLength={500} required placeholder="说明可访问来源、用途和授权依据；合成验证也请明确标记。"/></label><button className="button primary" disabled={busy||!chosen||(actualProvider==='LOCAL_BROWSER'&&!collectionEnvironments.length)}>保存监控</button>
    </form></details>}
    <section className="business-box acquisition-section"><h2>监控与扫描记录</h2><label>选择监控<select value={selectedMonitor} onChange={e=>{setSelectedMonitor(e.target.value);setSelectedLead('');}}><option value="">全部监控</option>{state.monitors.map(m=><option key={m.id} value={m.id}>{m.title} · {names[m.state]} · {m.config.discovery.platform}</option>)}</select></label>
      {monitor&&<div>{monitor.parent_monitor_id&&<p>自动接续来源 · 父监控 {monitor.parent_monitor_id} · 到期 {businessTime(monitor.derived_expires_at)} · <a href={monitor.derived_source_url} target="_blank" rel="noreferrer">原帖子</a></p>}{monitor.config.comment_continuation&&<p>已配置自动评论接续：每轮最多 {monitor.config.comment_continuation.max_sources_per_scan} 个，累计最多 {monitor.config.comment_continuation.max_sources_total} 个来源。子监控可在上方列表查看。</p>}<p>{monitor.config.discovery.keywords.join('、')}{monitor.config.discovery.browser?.template==='facebook-comments-dom-v1'?' · '+(monitor.config.discovery.browser.comment_order==='VISIBLE_WINDOW'?'仅当前可见窗口，不保证最新排序':'由新到旧'):''} · 发布时间：{monitor.config.discovery.max_age_days?'最近 '+monitor.config.discovery.max_age_days+' 天':'不限'} · 每 {monitor.interval_minutes} 分钟 · 下一次 {businessTime(monitor.next_due_at)} · {discoveryIsSynthetic(monitor.config.discovery)?'本地合成':'真实来源'}</p>{admin&&<div className="acquisition-inline">{(['SCAN',monitor.state==='ACTIVE'?'PAUSE':'START'] as const).map(action=><button key={action} disabled={busy} className="button" onClick={()=>void post('acquisition/monitors/'+monitor.id+'/control',{expected_version:monitor.version,action,reason:'管理员在工作台调整监控'},action==='SCAN'?'扫描已安排。':'监控状态已更新；旧版本动作不会复活。')}>{action==='SCAN'?'扫描一次':action==='START'?'启动持续监控':'暂停监控与旧动作'}</button>)}</div>}</div>}
      <div className="acquisition-scroll"><table><thead><tr><th>扫描</th><th>状态</th><th>读取 / 去重</th><th>停止原因</th></tr></thead><tbody>{state.scans.filter(s=>!selectedMonitor||s.monitor_id===selectedMonitor).slice(0,15).map(s=><tr key={s.id}><td>#{s.scan_number} · {businessTime(s.created_at)}</td><td>{names[s.state]??s.state}</td><td>{s.returned_count} / {s.unique_count}</td><td>{s.error_code??s.stop_reason??'进行中'}</td></tr>)}</tbody></table></div>
    </section>
    <section className="business-box acquisition-section"><h2>潜客线索池</h2><p>显示最近可见的最多 200 条线索；规则分数用于排序，不代表购买概率。原始数据缺失的作者身份不会补造。</p><div className="acquisition-inline"><label>搜索内容<input value={filter} onChange={e=>setFilter(e.target.value)}/></label><label>最低评分<input type="number" min={0} max={100} value={minScore} onChange={e=>setMinScore(Number(e.target.value))}/></label><label>发布时间判断<select value={ageState} onChange={e=>setAgeState(e.target.value)}><option value="ALL">全部</option>{Object.entries(ageNames).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>线索状态<select value={leadState} onChange={e=>setLeadState(e.target.value)}><option value="ALL">全部</option>{['NEW','QUALIFIED','DISMISSED','OPTED_OUT'].map(s=><option key={s} value={s}>{names[s]}</option>)}</select></label></div>
      <div className="acquisition-scroll"><table aria-label="获客线索列表"><thead><tr><th>平台 / 来源</th><th>命中内容</th><th>评分与依据</th><th>状态</th><th>操作</th></tr></thead><tbody>{filtered.map(l=><tr key={l.id}><td>{l.config.discovery.platform}<br/>{discoveryIsSynthetic(l.config.discovery)?'合成验证':'真实来源'}<br/><a href={l.source_url} target="_blank" rel="noreferrer">查看来源</a></td><td>{l.fields.message?.value??'正文未返回'}<small>作者：{l.fields.author_id?.value??'未返回'}</small><small>来源时间：{l.fields.created_time?.value??'未返回'}{l.fields.created_time?.kind==='DISPLAYED_TIME'?'（页面时间，时区未取得）':''} · {ageNames[l.publication_age]}</small></td><td>{l.score}<small>{l.reason}</small></td><td>{names[l.state]}<small>{l.automation_error}</small></td><td><button className="button small" onClick={()=>setSelectedLead(l.id)}>核对与执行</button></td></tr>)}</tbody></table>{!filtered.length&&<p>尚无符合筛选条件的线索。先保存监控并扫描。</p>}</div>
    </section>
    {lead&&<section id="acquisition-lead-review" className="business-box acquisition-section"><h2>核对线索与准备动作</h2>{leadBrowser&&<div><p>{lead.public_reply_eligibility.scope}</p>{lead.public_reply_eligibility.reasons.map((reason:string)=><p key={reason}>{reason}</p>)}</div>}<p>{lead.fields.message?.value} · {names[lead.state]}</p>
      {write&&<form className="acquisition-inline" aria-label="更新获客线索" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post('acquisition/leads/'+lead.id+'/control',{expected_version:lead.version,state:f.get('state'),reason:f.get('reason')},'线索状态已保存。');}}><label>处理状态<select name="state" defaultValue={lead.state}>{['NEW','QUALIFIED','DISMISSED','OPTED_OUT'].map(s=><option key={s} value={s}>{names[s]}</option>)}</select></label><label>判断依据<input name="reason" required minLength={5}/></label><button className="button" disabled={busy}>保存线索状态</button></form>}
      {write&&!canPrepareOutreach&&<p className="field-hint">此来源仅供筛选：直接评论互动只对「评论区策略」的自有内容来源开放（本地合成评论页或 Meta 直连自有帖子）。</p>}
      {write&&canPrepareOutreach&&<form aria-label="准备获客动作" className="acquisition-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post('acquisition/outreach',{lead_id:lead.id,expected_version:lead.version,environment_id:f.get('environment'),action:f.get('action'),body:f.get('body'),authorization_basis:f.get('basis'),delay_minutes:Number(f.get('delay')),...(leadBrowser?{expires_at:new Date(String(f.get('expires_at'))).toISOString(),...(priorDraft&&f.get('replace')==='on'?{replaces_task_id:priorDraft.task_id}:{})}:{})},leadBrowser?'草稿已保存。请到任务工作台核对账号、原评论、正文和期限，然后审核；尚未安排发送。':'动作已准备。真实动作请到任务工作台登记许可；合成动作进入本地队列。');}}><label>执行环境<select name="environment" required>{environments.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>动作<select name="action">{!leadBrowser&&<option value="PRIVATE_REPLY">评论触发私信</option>}<option value="COMMENT_REPLY">公开评论回复</option></select></label><label>回复话术<textarea name="body" required maxLength={1000}/></label><label>触达依据<textarea name="basis" required minLength={10} maxLength={500}/></label><label>延迟（分钟）<input name="delay" type="number" min={0} max={1440} defaultValue={0}/></label>{leadBrowser&&<><label>动作到期（本机时区，48 小时内）<input name="expires_at" type="datetime-local" required/></label>{priorDraft&&<label><input name="replace" type="checkbox" required/>重新准备此条未执行草稿，保留旧版本</label>}</>}<button className="button primary" disabled={busy||!environments.length||leadBrowser&&!lead.public_reply_eligibility.can_prepare}>{leadBrowser?'保存待审核的公开回复':'准备一次动作'}</button><p>{leadBrowser?'先核对线索为“值得跟进”。公开回复草稿绑定原评论和指定账号，审核与单次许可后才可执行；不会自动发送私信。':'仅自有内容的已核实评论可生成原生动作。竞品搜索结果不会自动获得私信资格。私信后须等客户回复，再进入接待窗口。'}</p></form>}
    </section>}
    {monitor&&admin&&!canAutomate&&<p className="field-hint">自动执行只对「评论区策略」的自有内容来源（本地合成评论页 / Meta 直连自有帖子）生效，此监控不会被自动执行调度选中。</p>}
    {monitor&&admin&&canAutomate&&<details className="business-box acquisition-section"><summary>为此监控配置自动执行</summary><form key={monitor.id} aria-label="配置获客自动化" className="acquisition-grid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void post('acquisition/automation',{monitor_id:monitor.id,expected_version:monitor.version,enabled:f.get('enabled')==='on',environment_id:f.get('environment'),action:f.get('action'),body:f.get('body'),authorization_basis:f.get('basis'),min_score:Number(f.get('score')),daily_limit:Number(f.get('limit')),delay_minutes:Number(f.get('delay'))},'自动执行规则已保存；真实动作仍逐项等待试验许可。');}}><label><input name="enabled" type="checkbox" defaultChecked={monitor.automation?.enabled??false}/> 自动准备命中线索的动作</label><label>环境<select name="environment" required defaultValue={monitor.automation?.environment_id}>{state.environments.filter(e=>e.account_id===monitor.account_id).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>动作<select name="action" defaultValue={monitor.automation?.action??'PRIVATE_REPLY'}><option value="PRIVATE_REPLY">评论触发私信</option><option value="COMMENT_REPLY">公开评论回复</option></select></label><label>最低评分<input name="score" type="number" min={1} max={100} defaultValue={monitor.automation?.min_score??70}/></label><label>账号每日上限<input name="limit" type="number" min={1} max={100} defaultValue={monitor.automation?.daily_limit??10}/></label><label>延迟（分钟）<input name="delay" type="number" min={0} max={1440} defaultValue={monitor.automation?.delay_minutes??5}/></label><label>固定话术<textarea name="body" required maxLength={1000} defaultValue={monitor.automation?.body}/></label><label>批准范围与依据<textarea name="basis" required minLength={10} maxLength={500} defaultValue={monitor.automation?.authorization_basis}/></label><button className="button primary" disabled={busy}>保存自动执行规则</button></form></details>}
    <section className="business-box acquisition-section"><h2>动作与结果</h2><p>确认提交不等于客户已读、已到达 WhatsApp 或成交。未知结果请核验原提交，勿重新发送。</p><div className="acquisition-scroll"><table><thead><tr><th>动作</th><th>目标</th><th>状态</th><th>处理</th></tr></thead><tbody>{state.actions.map(a=><tr key={a.task_id}><td>{names[a.action_kind]}</td><td>{a.source_object_id}</td><td>{a.superseded_at?'已由新草稿替代':names[a.state??a.status]??a.status}<small>{a.error_code}</small></td><td><a href={a.run_id?'/runs?run='+a.run_id:'/tasks'}>{a.run_id?'查看执行记录':'核对任务和试验许可'}</a></td></tr>)}</tbody></table></div></section>
    </details>
  </div>;
}
