'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import type {CollectionQuery} from '@kff/contracts';
import type {CollectionFilter} from '../../../packages/contracts/src/target-selection';
import type {TargetPreview,TargetSnapshot} from '@kff/core/target-snapshots';
import {saveDownload} from './import-workbench';
import { Field } from './field';

export const emptyFilter:CollectionFilter={id_prefix:'',message_contains:'',author_id:'',min_reactions:null,field_states:{}};
const labels={message:'正文',author_id:'作者标识',reaction_count:'互动数',comment_count:'评论数',created_time:'来源时间'};
const modes={CURRENT_PAGE:'当前页',MANUAL:'手选行',ALL_FILTERED:'全部筛选结果'};
const reasons:Record<string,string>={SOURCE_PURPOSE_NOT_ALLOWED:'来源未允许此用途',ACTION_AND_CONTACT_QUALIFICATION_REQUIRED:'还需具体动作及联系资格验证',SOURCE_FIELD_NOT_ALLOWED:'所选字段超出来源允许范围'};
async function api<T>(endpoint:string,body?:unknown):Promise<T>{const response=await fetch('/api/'+endpoint,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error?.message??'操作未完成');return value;}
export function CollectionFilterForm({query,filter,onApply}:{query:CollectionQuery;filter:CollectionFilter;onApply:(value:CollectionFilter)=>void}) {
  function apply(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const kind=String(form.get('kind'));const field=String(form.get('field'));onApply({id_prefix:String(form.get('id_prefix')??''),message_contains:String(form.get('message_contains')??''),author_id:String(form.get('author_id')??''),min_reactions:form.get('min_reactions')?Number(form.get('min_reactions')):null,field_states:kind?{[field]:kind as 'VALUE'|'DISPLAYED_TIME'|'NULL'|'NOT_RETURNED'|'HIDDEN'}:{}});}
  return <details className="collection-filter"><summary>筛选查询结果</summary><form key={JSON.stringify(filter)} onSubmit={apply}><div className="form-grid"><Field label="对象 ID 前缀"><input name="id_prefix" maxLength={160} defaultValue={filter.id_prefix}/></Field>
    {query.snapshot.fields.includes('message')&&<Field label="正文包含"><input name="message_contains" maxLength={100} defaultValue={filter.message_contains}/></Field>}
    {query.snapshot.fields.includes('author_id')&&<Field label="作者 ID 等于"><input name="author_id" maxLength={160} defaultValue={filter.author_id}/></Field>}
    {query.snapshot.fields.includes('reaction_count')&&<Field label="互动数至少"><input name="min_reactions" type="number" min={0} max={Number.MAX_SAFE_INTEGER} defaultValue={filter.min_reactions??''}/></Field>}
    <Field label="按字段状态筛选"><select name="field" defaultValue={Object.keys(filter.field_states)[0]??query.snapshot.fields[0]}>{query.snapshot.fields.map(key=><option key={key} value={key}>{labels[key]}</option>)}</select></Field><Field label="字段状态"><select name="kind" defaultValue={Object.values(filter.field_states)[0]??''}><option value="">不限</option><option value="VALUE">有值（包含零及空字符串）</option><option value="DISPLAYED_TIME">页面时间标签</option><option value="NULL">空值</option><option value="NOT_RETURNED">来源未返回</option><option value="HIDDEN">来源隐藏</option></select></Field></div><div className="contact-actions"><button className="button subtle">应用筛选</button><button type="button" className="text-button" onClick={()=>onApply({...emptyFilter})}>清除筛选</button></div><p className="field-hint">条件同时生效；筛选在服务端计算。修改筛选会清空当前手选，已保存快照保持原范围。</p></form></details>;
}
export function CollectionTargets({query,filter,after,pageHash,pageSize,selected,filteredCount,canWrite,onClear}:{query:CollectionQuery;filter:CollectionFilter;after:string;pageHash:string;pageSize:number;selected:Record<string,string>;filteredCount:number;canWrite:boolean;onClear:()=>void}){
  const [preview,setPreview]=useState<TargetPreview|null>(null);const [saved,setSaved]=useState<Omit<TargetSnapshot,'definition'>[]>([]);const [focused,setFocused]=useState<TargetSnapshot|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [mode,setMode]=useState<keyof typeof modes>('CURRENT_PAGE');const [page,setPage]=useState(0);
  const requests=useRef(new Map<string,string>());const request=(input:unknown)=>{const key=JSON.stringify(input);if(!requests.current.has(key))requests.current.set(key,crypto.randomUUID());return requests.current.get(key)!;};
  const refresh=async()=>setSaved(await api('collections/'+query.id+'/target-snapshots'));
  useEffect(()=>{let active=true;void api<typeof saved>('collections/'+query.id+'/target-snapshots').then(value=>{if(active)setSaved(value);}).catch(failure=>{if(active)setError(failure.message);});return()=>{active=false;};},[query.id]);
  async function act(operation:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await operation();await refresh();}catch(failure){setError(failure instanceof Error?failure.message:'操作未完成');}finally{setBusy(false);}}
  async function prepare(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await act(async()=>{const input={query_id:query.id,mode,filter,after,page_size:pageSize,page_hash:mode==='CURRENT_PAGE'?pageHash:null,result_ids:mode==='MANUAL'?Object.keys(selected):[],observations:mode==='MANUAL'?Object.entries(selected).map(([result_id,observation_id])=>({result_id,observation_id})):[],purpose:form.get('purpose'),fields:form.getAll('fields')};setPreview(await api<TargetPreview>('target-previews',{...input,request_id:request(input)}));setPage(0);setNotice('预览已固定，请核对纳入与排除对象。');});}
  const definition=preview?.definition;
  const observed=(value:string)=>new Date(value).toLocaleString('zh-CN',{timeZone:query.snapshot.display_timezone,hour12:false})+'（'+query.snapshot.display_timezone+'）';
  return <section className="collection-targets" aria-label="精确目标快照"><h3>精确目标快照</h3><p className="field-hint">当前筛选匹配 {filteredCount} 个对象；手选 {Object.keys(selected).length} 个。快照固定对象、字段、用途与观察版本，用于后续任务准备。</p>{error&&<p role="alert" className="alert error">{error}</p>}{notice&&<p role="status" className="alert warning">{notice}</p>}
    {canWrite&&<form aria-label="选择目标范围" onSubmit={event=>void prepare(event)}><fieldset disabled={busy}><div className="form-grid"><Field label="目标选择范围"><select value={mode} onChange={event=>{setMode(event.target.value as keyof typeof modes);setPreview(null);}}>{Object.entries(modes).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></Field><Field label="本次目标用途"><select name="purpose" defaultValue={query.snapshot.allowed_purposes[0]} onChange={()=>setPreview(null)}><option value="software_verification">软件验证</option><option value="data_review">数据核对</option><option value="marketing">营销联系</option><option value="customer_service">客户服务联系</option></select></Field></div><fieldset className="collection-field-choice"><legend>快照保留字段</legend>{query.snapshot.fields.map(key=><label key={key}><input type="checkbox" name="fields" value={key} defaultChecked onChange={()=>setPreview(null)}/>{labels[key]}</label>)}</fieldset><div className="contact-actions"><button className="button subtle" disabled={busy||mode==='MANUAL'&&!Object.keys(selected).length}>预览目标范围</button><button type="button" className="text-button" onClick={()=>{onClear();setPreview(null);}}>清空手选</button></div></fieldset></form>}
    {preview&&definition&&<div className="target-preview" aria-label="目标范围预览"><h4>{modes[definition.input.mode]} · 已固定预览</h4><p>纳入 {definition.included_count} 个，排除 {definition.excluded_count} 个。共 {definition.targets.length} 个所选对象。</p><p className="field-hint">预览至 {observed(preview.expires_at)} 有效；保存后不跟随筛选或新增采集扩张。</p><div className="table-scroll"><table aria-label="目标预览明细"><thead><tr><th>原始对象 ID</th><th>观察版本</th><th>纳入与排除</th></tr></thead><tbody>{definition.targets.slice(page*25,page*25+25).map(row=><tr key={row.result_id}><td className="mono">{row.source_object_id}</td><td>{row.object_version}<small>{observed(row.observed_at)}</small></td><td>{row.disposition==='INCLUDED'?'纳入':row.reason_codes.map(reason=>reasons[reason]??reason).join('；')}</td></tr>)}</tbody></table></div><div className="contact-actions"><button className="text-button" disabled={!page} onClick={()=>setPage(value=>value-1)}>上一页目标</button><span>第 {page+1} 页</span><button className="text-button" disabled={(page+1)*25>=definition.targets.length} onClick={()=>setPage(value=>value+1)}>下一页目标</button></div>
      <form key={preview.id} onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void act(async()=>{const input={preview_id:preview.id,preview_hash:preview.definition_hash,title:form.get('title'),confirmed_included_count:definition.included_count,confirmed_excluded_count:definition.excluded_count};setFocused(await api<TargetSnapshot>('target-snapshots',{...input,request_id:request(input)}));setPreview(null);setNotice('目标快照已保存，范围和观察版本已固定。');});}}><Field label="目标快照名称"><input name="title" defaultValue={query.title.slice(0,100)+' · 目标'} maxLength={120} required/></Field><label className="import-confirm"><input type="checkbox" required disabled={busy}/>我已核对这 {definition.targets.length} 个对象及纳入、排除原因。</label><button className="button primary" disabled={busy}>确认并保存目标快照</button></form></div>}
    <div className="target-saved"><h4>已保存快照</h4>{!saved.length&&<p className="field-hint">此查询还没有固定的目标范围。</p>}{saved.map(row=><button className="text-button" key={row.id} disabled={busy} onClick={()=>void act(async()=>setFocused(await api<TargetSnapshot>('target-snapshots/'+row.id)))}>{row.title} · 纳入 {row.included_count} / 排除 {row.excluded_count} · {row.expired?'已到期':row.state==='REVOKED'?'已撤销':'已保存'}</button>)}</div>
    {focused&&<div className="target-snapshot-detail" aria-label="已保存目标快照"><h4>{focused.title}</h4><p>固定 {focused.included_count} 个纳入对象，{focused.excluded_count} 个排除对象。</p><p className="field-hint">此快照不构成平台执行或联系许可。创建具体任务前仍需核对用途、退出、动作能力、审核和预算。</p><details><summary>查看固定范围与摘要</summary><code>{focused.definition_hash}</code>{focused.definition?.targets.map(row=><p className="mono" key={row.result_id}>{row.source_object_id} · 观察 {row.object_version} · {row.disposition==='INCLUDED'?'纳入':'排除'}</p>)}</details>
      <div className="contact-actions">{(['csv','xlsx'] as const).map(format=><button className="button subtle" key={format} disabled={busy||focused.expired||focused.state!=='ACTIVE'||!focused.definition} onClick={()=>void act(async()=>{const allowed=query.snapshot.source_type==='MANUAL_IMPORT'?query.snapshot.export_fields:query.snapshot.fields;const fields=focused.definition!.input.fields.filter(field=>allowed.includes(field));await saveDownload(await fetch('/api/collections/'+query.id+'/exports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({format,fields,target_snapshot_id:focused.id})}),'kff-targets.'+format);})}>导出固定快照 {format.toUpperCase()}</button>)}</div>
      {canWrite&&focused.state==='ACTIVE'&&<form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void act(async()=>{const value={expected_version:focused.version,reason:form.get('reason')};await api('target-snapshots/'+focused.id+'/revoke',{...value,request_id:request({id:focused.id,...value})});setFocused(await api<TargetSnapshot>('target-snapshots/'+focused.id));setNotice('快照已撤销，后续使用已阻止。');});}}><Field label="撤销快照原因"><input name="reason" required minLength={5} maxLength={300} disabled={busy}/></Field><button className="button danger" disabled={busy}>撤销此目标快照</button></form>}
    </div>}
  </section>;
}
