'use client';
import { cloneElement, useCallback, useEffect, useId, useRef, useState, type FormEvent, type ReactElement } from 'react';
import type { Workspace } from '@kff/core/service';
import type { CollectionQuery, CollectionRun, CollectionResult, CollectionRecord } from '@kff/contracts';
import { ImportWorkbench } from './import-workbench';
import { CollectionExport } from './collection-export';
import {CollectionFilterForm,CollectionTargets,emptyFilter} from './collection-targets';
import type {CollectionFilter} from '../../../packages/contracts/src/target-selection';

interface Summary extends CollectionQuery { run_id: string; state: CollectionRun['state']; returned_count: number; unique_count: number; committed_pages: number; stop_reason: string | null }
interface Detail { filter:CollectionFilter;filtered_count:number;page_hash:string;page_after:string;query: CollectionQuery; run: CollectionRun; results: CollectionResult[]; next_cursor: string | null; expired: boolean; pages: { page_number: number; evidence_hash: string; returned_count: number }[] }
interface Observation { id: string; object_version: number; observed_at: string; fields: CollectionRecord['fields']; source_url: string; evidence_hash: string }
const fields = { message: '正文', author_id: '作者标识', reaction_count: '互动数', comment_count: '评论数', created_time: '来源时间' };
const states = { QUEUED: '等待采集', RUNNING: '读取当前页', COMPLETED: '样本读取完成', PARTIAL: '部分结果', FAILED: '读取失败', CANCELED: '已停止' };
const reasons: Record<string, string> = { SOURCE_EXHAUSTED: '已遍历此来源当前返回的样本', MAX_RECORDS: '已达到返回条数上限', MAX_PAGES: '已达到分页上限', CURSOR_LOOP: '来源游标重复，已停止继续读取', CURSOR_EXPIRED: '来源游标已失效，需要重新核对查询', REMOTE_ERROR: '来源连接失败，已保存的分页仍保留', COLLECTION_SOURCE_MISMATCH: '账号或来源已变化，需要重新核对', COLLECTION_INVALID_PAGE: '来源响应不符合字段合同', COLLECTION_FIELDS_MISMATCH: '返回字段与允许字段不符', STOP_REQUESTED: '操作员已停止后续采集', RETENTION_EXPIRED: '数据保留期已结束' };
function Field({ label, children }: { label: string; children: ReactElement<{ id?: string }> }) { const id = useId(); return <div className="field"><label htmlFor={id}>{label}</label>{cloneElement(children, { id })}</div>; }
function datum(value: CollectionRecord['fields'][keyof CollectionRecord['fields']]) { return !value ? '未请求' : value.kind === 'VALUE' ? value.value === '' ? '空字符串' : String(value.value) : value.kind === 'NULL' ? '空值' : value.kind === 'HIDDEN' ? '来源隐藏' : '来源未返回'; }
function observed(value: string, timezone: string) { return new Date(value).toLocaleString('zh-CN', { timeZone: timezone, hour12: false }); }
async function api<T>(path: string, body?: unknown): Promise<T> { const response = await fetch('/api/' + path, { method: body === undefined ? 'GET' : 'POST', headers: body === undefined ? {} : { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body), cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message ?? '查询暂时无法读取'); return result; }

export function CollectionWorkbench({ data }: { data: Workspace }) {
  const [queries, setQueries] = useState<Summary[]>([]); const [selected, setSelected] = useState(''); const [after, setAfter] = useState('0');
  const [detail, setDetail] = useState<Detail | null>(null); const [revision, setRevision] = useState(0); const [history, setHistory] = useState<{ query_id: string; id: string; records: Observation[] } | null>(null);
  const [filter,setFilter]=useState<CollectionFilter>(emptyFilter); const [selectedTargets,setSelectedTargets]=useState<Record<string,string>>({});
  const requests = useRef(new Map<string, string>());
  const request = (value: unknown) => { const key = JSON.stringify(value); if (!requests.current.has(key)) requests.current.set(key, crypto.randomUUID()); return { request_id: requests.current.get(key)! }; };
  const [accountId, setAccountId] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [reason, setReason] = useState('');
  const accounts = data.accounts.filter(account => account.is_synthetic); const account = accounts.find(value => value.id === accountId) ?? accounts[0];
  const load = useCallback(async () => { const records = await api<Summary[]>('collections'); setQueries(records); setSelected(current => records.some(record => record.id === current) ? current : records[0]?.id ?? ''); }, []);
  useEffect(() => { let active = true; const update = () => { if (active) void load().catch(failure => { if (active) setError(failure instanceof Error ? failure.message : '查询列表无法读取'); }); }; update(); const timer = setInterval(update, 3000); return () => { active = false; clearInterval(timer); }; }, [load]);
  useEffect(() => {
    if (!selected) return; let active = true; let inFlight = false;
    const update = async () => { if (inFlight) return; inFlight = true; try { const result = await api<Detail>('collections/' + selected + '?after=' + after + '&filter=' + encodeURIComponent(JSON.stringify(filter))); if (active) setDetail(result); } catch (failure) { if (active) setError(failure instanceof Error ? failure.message : '查询详情无法读取'); } finally { inFlight = false; } };
    void update(); const timer = setInterval(() => void update(), 2500); return () => { active = false; clearInterval(timer); };
  }, [selected, after, revision, filter]);
  const current = detail?.query.id === selected && detail.page_after === after && JSON.stringify(detail.filter) === JSON.stringify(filter) ? detail : null;
  async function act(operation: () => Promise<void>, message: string) { setBusy(true); setError(''); setNotice(''); try { await operation(); await load(); setNotice(message); } catch (failure) { setError(failure instanceof Error ? failure.message : '操作未完成'); } finally { setBusy(false); setRevision(value => value + 1); } }
  async function create(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!account) return; const form = new FormData(event.currentTarget);
    await act(async () => {
      const value = { title: form.get('title'), account_id: account.id, targets: [account.external_id], fields: form.getAll('fields'), source_key: 'kff.fixture.page.posts', purpose: 'software_verification', mode: 'TEST_ONLY', incremental_rule: 'append_observations', max_records: Number(form.get('max_records')), max_pages: Number(form.get('max_pages')), page_size: Number(form.get('page_size')), display_timezone: form.get('display_timezone'), retention_days: Number(form.get('retention_days')), scenario: form.get('scenario') };
      const result = await api<{ id: string }>('collections', { ...value, ...request(value) }); requests.current.clear();
      setSelected(result.id); setAfter('0'); setHistory(null); setFilter(emptyFilter); setSelectedTargets({}); setReason('');
    }, '查询已可靠入队，将逐页保存来源与观察记录');
  }
  async function control(action: 'STOP' | 'RESUME') { if (!current) return; await act(async () => { const value = { expected_version: current.run.version, reason }; await api('collections/' + current.query.id + '/' + (action === 'STOP' ? 'stop-requests' : 'resume'), { ...value, ...request({ query_id: current.query.id, action, ...value }) }); }, action === 'STOP' ? '已停止后续采集，已保存结果保留' : '已从原检查点重新排队'); }
  return <div className="collection-workbench">
    <ImportWorkbench data={data} onConfirmed={id => { setSelected(id); setAfter('0'); setHistory(null); setFilter(emptyFilter); setSelectedTargets({}); setRevision(value=>value+1); void load(); }} />
    {error && <p className="alert error" role="alert">{error}</p>}{notice && <p className="alert warning" role="status">{notice}</p>}
    {data.scope.role !== 'viewer' && <section className="panel collection-create"><details><summary>创建新的查询</summary><p className="field-hint">当前来源为本项目合成主页，仅用于软件验证。真实 Facebook 采集入口将在取得来源范围和测试证据后接入。</p><form onSubmit={event => void create(event)}><fieldset disabled={busy || !account}>
      <Field label="查询名称"><input name="title" required maxLength={120} placeholder="例如：核对主页数据分页" /></Field>
      <div className="form-grid"><Field label="采集执行账号"><select value={account?.id ?? ''} onChange={event => setAccountId(event.target.value)} required>{accounts.map(value => <option key={value.id} value={value.id}>{value.display_name}</option>)}</select></Field><Field label="查询目标标识"><input value={account?.external_id ?? ''} readOnly /></Field></div>
      <fieldset className="collection-field-choice"><legend>允许读取的字段</legend>{Object.entries(fields).map(([key, label]) => <label key={key}><input type="checkbox" name="fields" value={key} defaultChecked />{label}</label>)}</fieldset>
      <div className="form-grid"><Field label="返回观察条数上限"><input type="number" name="max_records" required min={1} max={1000} defaultValue={20} /></Field><Field label="读取页数上限"><input type="number" name="max_pages" required min={1} max={100} defaultValue={10} /></Field><Field label="每页读取条数"><input type="number" name="page_size" required min={1} max={100} defaultValue={2} /></Field><Field label="显示时区"><input name="display_timezone" required defaultValue="Asia/Shanghai" maxLength={80} /></Field><Field label="观察数据保留天数"><input type="number" name="retention_days" required min={1} max={30} defaultValue={7} /></Field><Field label="采集验证场景"><select name="scenario" defaultValue="normal"><option value="normal">正常分页与重复观察</option><option value="empty">正常空结果</option><option value="empty_first_page">空页后仍有结果</option><option value="cursor_loop">游标循环</option><option value="cursor_expired">游标失效</option><option value="fail_second_page">后续页连接失败</option></select></Field></div>
      <p className="field-hint">用途：软件验证。按原始对象标识去重，新观察保留版本；不会据此生成客户或联系授权。</p><button className="button primary" disabled={busy || !account}>保存并执行查询</button>
    </fieldset></form></details></section>}
    <section className="panel"><div className="panel-head"><h2>查询记录</h2><button className="text-button" disabled={busy} onClick={() => void act(load, '查询列表已刷新')}>刷新查询记录</button></div><div className="table-scroll"><table aria-label="采集查询列表"><thead><tr><th>查询</th><th>读取状态</th><th>返回观察</th><th>去重对象</th><th>已保存页</th></tr></thead><tbody>{queries.map(record => <tr key={record.id} className={selected === record.id ? 'template-selected' : ''}><td><button className="text-button strong" onClick={() => { setSelected(record.id); setAfter('0'); setHistory(null); setFilter(emptyFilter); setSelectedTargets({}); setReason(''); }}>{record.title}</button><small>{record.snapshot.source_type === 'MANUAL_IMPORT' ? '人工导入 · 数据核对' : '本地合成主页 · 软件验证'}</small></td><td>{record.snapshot.source_type === 'MANUAL_IMPORT' ? '导入完成' : states[record.state]}</td><td>{record.returned_count}</td><td>{record.unique_count}</td><td>{record.committed_pages}</td></tr>)}</tbody></table>{!queries.length && <p className="collection-empty">还没有查询记录。</p>}</div><div className="panel-footer">最近 100 个查询 · 返回量与去重对象数分别记录</div></section>
    {current && <section className="panel collection-detail" aria-label="采集查询详情"><div className="panel-head"><h2>{current.query.title}</h2><span>{current.query.snapshot.source_type === 'MANUAL_IMPORT' ? '导入完成' : states[current.run.state]}</span></div><div className="collection-summary"><p>{current.run.stop_reason ? current.run.stop_reason === 'IMPORT_CONFIRMED' ? '有效行已确认入库，错误行已明确排除' : reasons[current.run.stop_reason] ?? '当前来源无法继续读取' : '按允许字段与上限逐页读取。'}</p><p>已返回 <strong>{current.run.returned_count}</strong> 条观察，去重后 <strong>{current.run.unique_count}</strong> 个对象。来源总量{current.run.reported_total === null ? '未知' : '为 ' + current.run.reported_total}。</p><p>{current.query.snapshot.source_type === 'MANUAL_IMPORT' ? '覆盖仅限已上传并确认的有效行；人工导入不作为自动采集证据。' : '覆盖仅限本项目合成样本；不代表任何 Facebook 账号的全量数据。'}</p><p>保留期至 {observed(current.query.expires_at, current.query.snapshot.display_timezone)}（{current.query.snapshot.display_timezone}）</p>
      {data.scope.role !== 'viewer' && (['QUEUED','RUNNING'].includes(current.run.state) || current.run.error_code === 'REMOTE_ERROR') && <div className="collection-control"><Field label="查询操作原因"><input value={reason} onChange={event => setReason(event.target.value)} minLength={5} maxLength={300} /></Field>{['QUEUED','RUNNING'].includes(current.run.state) ? <button className="button danger" disabled={busy || reason.trim().length < 5} onClick={() => void control('STOP')}>停止此查询</button> : <button className="button subtle" disabled={busy || reason.trim().length < 5 || current.expired} onClick={() => void control('RESUME')}>从原检查点继续</button>}</div>}
    </div>
    <CollectionFilterForm query={current.query} filter={filter} onApply={value=>{setFilter(value);setAfter('0');setSelectedTargets({});setHistory(null);}} />
    <p className="collection-filter-count">筛选匹配 {current.filtered_count} 个对象，本页显示 {current.results.length} 个。</p>
    <div className="table-scroll"><table aria-label="采集结果"><thead><tr><th>手选</th><th>原始对象标识</th>{current.query.snapshot.fields.map(field => <th key={field}>{fields[field]}</th>)}<th>观察与来源</th></tr></thead><tbody>{current.results.map(result => <tr key={result.id}><td><input type="checkbox" aria-label={'手选 '+result.source_object_id} disabled={data.scope.role==='viewer'} checked={selectedTargets[result.id]!==undefined} onChange={event=>{const checked=event.target.checked;setSelectedTargets(values=>{const next={...values};if(checked)next[result.id]=result.observation_id;else delete next[result.id];return next;});}} /></td><td><button className="text-button mono" onClick={() => void act(async () => setHistory({ query_id: current.query.id, id: result.source_object_id, records: await api<Observation[]>('collections/' + current.query.id + '/results/' + result.id) }), '已读取此查询的观察版本')}>{result.source_object_id}</button><small>观察版本 {result.object_version}</small></td>{current.query.snapshot.fields.map(field => <td className="collection-value" key={field}>{datum(result.fields[field])}</td>)}<td><span>{observed(result.observed_at, current.query.snapshot.display_timezone)}</span><small><a className="text-link" href={result.source_url} target="_blank" rel="noreferrer">{current.query.snapshot.source_type === 'MANUAL_IMPORT' ? '查看原文件' : '查看合成来源'}</a></small></td></tr>)}</tbody></table>
      {!current.results.length && <p className="collection-empty">{current.expired ? '观察数据已到保留期限，内容不再提供。' : current.run.state === 'COMPLETED' && current.run.returned_count === 0 ? '来源正常返回空结果。' : current.run.state === 'FAILED' ? '读取失败，尚无已确认结果；不作为正常空结果。' : '当前没有可显示的已确认结果。'}</p>}
    </div><div className="panel-footer"><span>正文、空值、隐藏与未返回分别显示</span><div className="contact-actions"><button className="text-button" disabled={after === '0'} onClick={() => setAfter('0')}>返回首页</button><button className="text-button" disabled={!current.next_cursor} onClick={() => current.next_cursor && setAfter(current.next_cursor)}>下一页结果</button></div></div>
    {history && history.query_id === current.query.id && <div className="collection-history" role="region" aria-label="观察版本记录"><h3>{history.id}</h3>{history.records.map(record => <article key={record.id}><strong>观察版本 {record.object_version}</strong><small>{observed(record.observed_at, current.query.snapshot.display_timezone)}</small><dl>{Object.entries(record.fields).map(([key, value]) => <div key={key}><dt>{fields[key as keyof typeof fields]}</dt><dd>{datum(value)}</dd></div>)}</dl><details><summary>查看来源证据摘要</summary><code>{record.evidence_hash}</code></details></article>)}</div>}
    <CollectionTargets key={'targets:'+current.query.id} query={current.query} filter={filter} after={after} pageHash={current.page_hash} pageSize={25} selected={selectedTargets} filteredCount={current.filtered_count} canWrite={data.scope.role!=='viewer'&&!current.expired} onClear={()=>setSelectedTargets({})} />
    <CollectionExport key={'export:'+current.query.id} query={current.query} results={current.results} expired={current.expired} />
    <details className="collection-checkpoints"><summary>已确认分页 · {current.pages.length} 页</summary>{current.pages.map(page => <div key={page.page_number}><span>第 {page.page_number} 页 · {page.returned_count} 条观察</span><code>{page.evidence_hash}</code></div>)}</details></section>}
  </div>;
}
