'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import type {Workspace} from '@kff/core/service';
import type {FacebookConnection,FacebookEvent} from '../../../packages/contracts/src/lead';
import {receptionPolicy} from '../../../packages/contracts/src/lead';
import {businessRequest} from './business-ui';
import {useRequestKey} from './use-request-key';

export function FacebookSetup({data,onReceived}:{data:Workspace;onReceived:()=>Promise<void>}){
  const [workspace,setWorkspace]=useState(data),[connections,setConnections]=useState<FacebookConnection[]>([]),[account,setAccount]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const requestKey=useRequestKey(),pendingEvent=useRef<{key:string;event:FacebookEvent}|null>(null);
  const refresh=useCallback(async()=>{const [next,fb]=await Promise.all([businessRequest<Workspace>('workspace'),businessRequest<{connections:FacebookConnection[]}>('facebook')]);setWorkspace(next);setConnections(fb.connections);},[]);
  useEffect(()=>{let active=true;businessRequest<{connections:FacebookConnection[]}>('facebook').then(value=>{if(active)setConnections(value.connections);}).catch(failure=>{if(active)setError(failure.message);});return()=>{active=false;};},[]);
  const selected=connections.find(row=>row.account_id===account),current=workspace.accounts.find(row=>row.id===account);
  const realBrowser=current?.account_type==='profile'&&!current.is_synthetic;
  async function perform(work:()=>Promise<void>){setBusy(true);setError('');try{await work();await refresh();}catch(failure){setError(failure instanceof Error?failure.message:'操作未完成，请保留原内容重试');}finally{setBusy(false);}}
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget);await perform(async()=>{const payload={name:fields.get('name'),page_id:fields.get('page_id'),agent_id:fields.get('agent_id')};const result=await businessRequest<{account_id:string}>('facebook/fixtures',{...payload,request_id:requestKey.forPayload(payload)});requestKey.confirmed();setAccount(result.account_id);});}
  async function configure(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget);await perform(async()=>{const payload={account_id:account,environment_id:fields.get('environment_id'),expected_version:selected?.version??0,transport:fields.get('transport'),state:fields.get('state'),auto_reply:fields.get('auto_reply')==='on',reply_window_hours:Number(fields.get('reply_window_hours')),policy_ref:fields.get('policy_ref')};await businessRequest('facebook/connections',{...payload,request_id:requestKey.forPayload(payload)});requestKey.confirmed();});}
  async function inject(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget);await perform(async()=>{
    if(!current)return;const kind=String(fields.get('kind')) as FacebookEvent['kind'],payload={account_id:account,sender_id:String(fields.get('sender_id')),body:String(fields.get('body')),kind},key=JSON.stringify(payload);
    if(pendingEvent.current?.key!==key)pendingEvent.current={key,event:{event_id:'fixture_'+crypto.randomUUID(),page_id:current.external_id,sender_id:payload.sender_id,body:payload.body,kind,display_name:'本地验证客户',occurred_at:new Date().toISOString(),has_attachment:false,source:{kind:kind==='COMMENT'?'COMMENT':'MESSENGER',page_id:current.external_id,source_id:kind==='COMMENT'?'fixture_comment':null,ref:'本地浏览器验证',ad_id:null}}};
    await businessRequest('facebook/fixtures/'+account+'/events',pendingEvent.current.event);pendingEvent.current=null;await onReceived();
  });}
  async function rules(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget);await perform(async()=>{const policy=receptionPolicy.parse({provider:fields.get('provider'),business_context:fields.get('business_context'),greeting_reply:fields.get('greeting_reply'),question_reply:fields.get('question_reply'),qualification_keywords:String(fields.get('qualification_keywords')).split(/[,，\n]/).map(v=>v.trim()).filter(Boolean),referral_after_replies:Number(fields.get('referral_after_replies')),min_confidence:Number(fields.get('min_confidence')),max_replies_per_conversation:Number(fields.get('max_replies_per_conversation')),max_account_replies_per_day:Number(fields.get('max_account_replies_per_day')),min_reply_interval_seconds:Number(fields.get('min_reply_interval_seconds')),stop_after_referral:fields.get('stop_after_referral')==='on'});const payload={account_id:account,expected_version:selected!.version,policy};await businessRequest('facebook/reception-policy',{...payload,request_id:requestKey.forPayload(payload)});requestKey.confirmed();});}
  return <details className="business-box channel-settings"><summary>Facebook 账号与接待 <span>{connections.length} 个</span></summary>
    <p className="muted">真实 Facebook 尚待账号权限和平台联调。合成账号可在本地验证收件、接待和引流流程。</p>
    {error&&<p role="alert" className="alert warning">{error}</p>}
    <label>选择 Facebook 账号<select value={account} onChange={event=>setAccount(event.target.value)}><option value="">选择账号</option>{workspace.accounts.filter(row=>row.platform==='facebook').map(row=><option key={row.id} value={row.id}>{row.display_name} · {row.is_synthetic?'本地合成':'真实待验'}</option>)}</select></label>
    {account&&current&&<>
      <p>{realBrowser?'个人账号':'Page'} {current.external_id} · {selected?.state==='ACTIVE'?'接待启用':selected?'接待暂停，继续收件':'尚未配置接待'}</p>
      {workspace.scope.role==='admin'&&<form key={account+'/'+(selected?.version??0)} className="business-form" aria-label="Facebook 接待配置" onSubmit={event=>void configure(event)}>
        <label>绑定执行环境<select name="environment_id" required defaultValue={selected?.environment_id}>{workspace.environments.filter(row=>row.account_id===account).map(row=><option value={row.id} key={row.id}>{row.name}</option>)}</select></label>
        <label>回复渠道<select name="transport" defaultValue={selected?.transport??(realBrowser?'BROWSER':'API')}>{realBrowser?<option value="BROWSER">AdsPower 人工回复</option>:<option value="API">官方接口</option>}{current.is_synthetic&&workspace.environments.some(row=>row.account_id===account&&row.browser_configuration?.driver==='native')&&<option value="BROWSER">本地浏览器验证</option>}</select></label>
        <label>接待状态<select name="state" defaultValue={selected?.state??'ACTIVE'}><option value="ACTIVE">启用接待</option><option value="PAUSED">暂停接待，继续收件</option></select></label>
        {realBrowser?<><input type="hidden" name="reply_window_hours" value="1"/><input type="hidden" name="policy_ref" value="kff.facebook-browser.explicit-consent.v1"/><p className="muted business-wide">人工处理已收到的私信。每次发送须关联客户明确同意，并单独审核一次回复；保存此配置不会自动发送。</p></>:<><label>私信服务窗口（小时）<input name="reply_window_hours" type="number" min={1} max={24} required defaultValue={selected?.reply_window_hours??24}/></label>
        <label>窗口依据<input name="policy_ref" maxLength={160} minLength={5} required defaultValue={selected?.policy_ref??(current.is_synthetic?'kff.fixture.service-window.v1':'')}/></label>
        <label><input name="auto_reply" type="checkbox" defaultChecked={selected?.auto_reply??false}/> 自动接待新私信</label></>}
        <button className="button primary" disabled={busy}>保存 Facebook 接待配置</button>
      </form>}
      {selected&&!realBrowser&&workspace.scope.role==='admin'&&<details key={account+'/rules/'+selected.version}><summary>意图识别与自动接待规则</summary><p className="muted">本地规则用于预演；模型接口须由服务端配置。模型只给出基础接待建议，低置信度和连续失败转人工。</p><form className="business-form" aria-label="自动接待规则" onSubmit={event=>void rules(event)}>
        <label>判断方式<select name="provider" defaultValue={receptionPolicy.parse(selected.reception_policy).provider}><option value="LOCAL_RULES">本地规则预演</option><option value="OPENAI_COMPATIBLE">模型接口</option></select></label><label>最低置信度<input name="min_confidence" type="number" min={0.5} max={1} step={0.05} required defaultValue={receptionPolicy.parse(selected.reception_policy).min_confidence}/></label>
        <label className="business-wide">业务介绍<textarea name="business_context" maxLength={3000} defaultValue={receptionPolicy.parse(selected.reception_policy).business_context}/></label><label className="business-wide">问候话术<textarea name="greeting_reply" required maxLength={1000} defaultValue={receptionPolicy.parse(selected.reception_policy).greeting_reply}/></label><label className="business-wide">追问话术<textarea name="question_reply" required maxLength={1000} defaultValue={receptionPolicy.parse(selected.reception_policy).question_reply}/></label><label className="business-wide">有效咨询关键词（逗号分隔）<input name="qualification_keywords" defaultValue={receptionPolicy.parse(selected.reception_policy).qualification_keywords.join(', ')}/></label>
        <label>咨询几轮后引流<input name="referral_after_replies" type="number" min={0} max={5} required defaultValue={receptionPolicy.parse(selected.reception_policy).referral_after_replies}/></label><label>每个会话自动回复上限<input name="max_replies_per_conversation" type="number" min={1} max={20} required defaultValue={receptionPolicy.parse(selected.reception_policy).max_replies_per_conversation}/></label><label>账号每日回复上限（UTC）<input name="max_account_replies_per_day" type="number" min={1} max={1000} required defaultValue={receptionPolicy.parse(selected.reception_policy).max_account_replies_per_day}/></label><label>账号回复间隔（秒）<input name="min_reply_interval_seconds" type="number" min={0} max={3600} required defaultValue={receptionPolicy.parse(selected.reception_policy).min_reply_interval_seconds}/></label><label><input name="stop_after_referral" type="checkbox" defaultChecked={receptionPolicy.parse(selected.reception_policy).stop_after_referral}/> 成功引流后停止自动接待</label><button className="button primary" disabled={busy}>保存自动接待规则</button>
      </form></details>}
      {selected?.transport==='BROWSER'&&<p className="muted">{realBrowser?'真实浏览器回复由绑定的 AdsPower 环境执行，当前按单条人工试验验证。':'本地浏览器接待读取合成会话，回复和 WhatsApp 邀请由绑定浏览器执行。'}</p>}
      {selected?.is_synthetic&&selected.transport!=='BROWSER'&&workspace.scope.role!=='viewer'&&<form className="business-form" aria-label="模拟 Facebook 客户" onSubmit={event=>void inject(event)}><h3>本地模拟客户互动</h3><label>客户平台 ID<input name="sender_id" required pattern="[0-9]+" maxLength={128} defaultValue="900001"/></label><label>事件类型<select name="kind"><option value="MESSAGE">客户私信</option><option value="COMMENT">客户评论</option><option value="ECHO">Facebook 原生人工回复</option></select></label><label>消息内容<textarea name="body" required maxLength={5000} defaultValue="你好，我想了解产品，可以加 WhatsApp 吗？"/></label><button className="button subtle" disabled={busy}>提交模拟互动</button></form>}
    </>}
    {workspace.scope.role==='admin'&&<details><summary>添加本地合成 Facebook 账号</summary><form className="business-form" aria-label="新增合成 Facebook 账号" onSubmit={event=>void create(event)}><label>账号名称<input name="name" required maxLength={80}/></label><label>合成 Page ID<input name="page_id" required pattern="[0-9]+" maxLength={128}/></label><label>执行 Agent<select name="agent_id" required>{workspace.agents.filter(row=>row.status!=='REVOKED').map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></label><button className="button subtle" disabled={busy}>创建合成账号</button></form></details>}
  </details>;
}
