'use client';
import { cloneElement, useEffect, useId, useRef, useState, type FormEvent, type ReactElement } from 'react';
import type { Workspace } from '@kff/core/service';
import type { importDetail } from '@kff/core/imports';
import type { ImportRowPreview } from '@kff/contracts';

type Detail=Awaited<ReturnType<typeof importDetail>>;
interface Preview {id:string;preview_hash:string;summary:{total_rows:number;valid_rows:number;error_rows:number;unique_objects:number;duplicate_rows:number;existing_objects:{source_object_id:string}[]};rows:ImportRowPreview[]|null}
const fields={message:'正文',author_id:'作者标识',reaction_count:'互动数',comment_count:'评论数',created_time:'来源时间'};
const errorNames:Record<string,string>={FORMULA_CELL:'包含公式，请改为原始值后导入',TEXT_REQUIRED:'需要文本格式；数值 ID 已丢失的精度无法还原',INVALID_ID:'标识为空或格式无效',INVALID_COUNT:'数量必须是非负安全整数',UTC_TIMESTAMP_REQUIRED:'时间需要使用带 Z 的 UTC 格式',INVALID_TIMESTAMP:'时间无效',INVALID_FIELD_KIND:'字段状态无效',NONEMPTY_NULL_FIELD:'空值状态与非空内容冲突',INVALID_TEXT_ESCAPE:'文本转义不匹配，请核对编码方式',INVALID_TEXT_ENCODING_MARKER:'本行缺少有效的 KFF 文本编码标记',UNSUPPORTED_CELL:'不支持此单元格类型'};
function rowError(error:string) {const [field,code]=error.split(': ');return code?((field==='source_object_id'?'对象 ID':fields[field as keyof typeof fields]??field)+'：'+(errorNames[code]??code)):(errorNames[field]??field);}
function Field({label,children}:{label:string;children:ReactElement<{id?:string}>}) { const id=useId(); return <div className="field"><label htmlFor={id}>{label}</label>{cloneElement(children,{id})}</div>; }
async function api<T>(endpoint:string,body?:unknown):Promise<T> { const response=await fetch('/api/'+endpoint,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'}); const value=await response.json(); if(!response.ok) throw new Error(value.error?.message??'操作失败'); return value; }
export async function saveDownload(response:Response,fallback:string) { if(!response.ok) { const error=await response.json(); throw new Error(error.error?.message??'下载未完成'); } const blob=await response.blob(); const url=URL.createObjectURL(blob); const link=document.createElement('a'); link.href=url; link.download=decodeURIComponent(response.headers.get('content-disposition')?.split("UTF-8''")[1]??fallback); link.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); }
export function ImportWorkbench({data,onConfirmed}:{data:Workspace;onConfirmed:(id:string)=>void}) {
  const [files,setFiles]=useState<{id:string;configuration:{title:string;filename:string};query_id:string|null}[]>([]);
  const [detail,setDetail]=useState<Detail|null>(null); const [sheet,setSheet]=useState(0); const [headerRow,setHeaderRow]=useState(1);
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [page,setPage]=useState(0); const [errorsOnly,setErrorsOnly]=useState(false);
  const requests=useRef(new Map<string,string>()); const request=(value:unknown)=>{const key=JSON.stringify(value); if(!requests.current.has(key)) requests.current.set(key,crypto.randomUUID());return requests.current.get(key)!;};
  const refresh=async()=>setFiles(await api('imports'));
  useEffect(()=>{let active=true; void api<typeof files>('imports').then(value=>{if(active)setFiles(value);}).catch(failure=>{if(active)setError(failure.message);});return()=>{active=false;};},[]);
  async function act(operation:()=>Promise<void>) {setBusy(true);setError('');setNotice('');try{await operation();await refresh();}catch(failure){setError(failure instanceof Error?failure.message:'操作未完成');}finally{setBusy(false);}}
  async function select(id:string) {await act(async()=>{setDetail(await api<Detail>('imports/'+id));setSheet(0);setHeaderRow(1);setPage(0);setErrorsOnly(false);});}
  async function upload(event:FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form=new FormData(event.currentTarget); const file=form.get('file'); if(!(file instanceof File)||!file.size)return;
    await act(async()=>{
      const input={title:form.get('title'),account_id:form.get('account_id'),filename:file.name,format:file.name.toLowerCase().endsWith('.xlsx')?'xlsx':'csv',encoding:form.get('encoding'),source_namespace:form.get('source_namespace'),source_description:form.get('source_description'),processing_basis:form.get('processing_basis'),purpose:'data_review',export_fields:form.getAll('export_fields'),original_access:form.get('original_access'),original_retention_days:Number(form.get('original_retention_days')),retention_days:Number(form.get('retention_days')),display_timezone:form.get('display_timezone')};
      const response=await fetch('/api/imports',{method:'POST',headers:{'Content-Type':'application/octet-stream','x-kff-import-metadata':encodeURIComponent(JSON.stringify({...input,request_id:request({input,size:file.size,last_modified:file.lastModified})}))},body:file});
      const result=await response.json();if(!response.ok)throw new Error(result.error?.message??'上传失败');
      setDetail(await api<Detail>('imports/'+result.id));setSheet(0);setHeaderRow(1);setPage(0);setErrorsOnly(false);requests.current.clear();setNotice('文件已保存，请选择字段映射并预览。');
    });
  }
  async function preview(event:FormEvent<HTMLFormElement>) {event.preventDefault();if(!detail)return;const form=new FormData(event.currentTarget);await act(async()=>{
    const mapped:Record<string,number>={};const kinds:Record<string,number>={};for(const key of Object.keys(fields)){const column=String(form.get(key));const kind=String(form.get(key+'__kind'));if(column!=='')mapped[key]=Number(column);if(kind!=='')kinds[key]=Number(kind);}
    const input={sheet,header_row:headerRow,source_object_id:Number(form.get('source_object_id')),fields:mapped,kind_columns:kinds,text_encoding:form.get('text_encoding')};
    await api('imports/'+detail.id+'/previews',{...input,request_id:request({id:detail.id,...input})});setDetail(await api<Detail>('imports/'+detail.id));setPage(0);setNotice('预览已生成，核对错误、重复和有效行后再确认。');
  });}
  const previewData=detail?.preview as Preview|null;const shown=(previewData?.rows??[]).filter(row=>!errorsOnly||row.errors.length);const headers=detail?.sheets[sheet]?.headers[headerRow-1]??[];
  const names=headers.map((cell,index)=>({index,label:cell.type==='text'?cell.value:cell.type==='number'?String(cell.value):'无文本表头'}));
  const defaultColumn=(key:string)=>{const index=names.findIndex(column=>column.label===key);return index<0?'':String(index);};
  const options=<>{names.map(column=><option key={column.index} value={column.index}>{column.index+1} · {column.label}</option>)}</>;
  return <section className="panel import-workbench"><details><summary>Excel / CSV 导入</summary><p className="field-hint">上传 → 字段映射 → 预览验证 → 确认入库。人工导入用于数据核对，不构成联系许可。</p>
    {error&&<p className="alert error" role="alert">{error}</p>}{notice&&<p className="alert warning" role="status">{notice}</p>}
    {data.scope.role!=='viewer'&&<form aria-label="上传导入文件" onSubmit={event=>void upload(event)}><fieldset disabled={busy}>
      <div className="form-grid"><Field label="导入名称"><input name="title" required maxLength={120}/></Field><Field label="归属账号"><select name="account_id" required>{data.accounts.map(account=><option value={account.id} key={account.id}>{account.display_name}</option>)}</select></Field>
      <Field label="CSV 或 Excel 文件"><input name="file" type="file" accept=".csv,.xlsx" required/></Field><Field label="CSV 文件编码"><select name="encoding"><option value="utf-8">UTF-8（含 BOM）</option><option value="gb18030">GB18030 / GBK</option><option value="utf-16le">UTF-16LE</option></select></Field>
      <Field label="人工来源标识"><input name="source_namespace" pattern="[a-z0-9][a-z0-9_-]{2,63}" required placeholder="例如 owned-records"/></Field><Field label="来源说明"><input name="source_description" required minLength={5} maxLength={500}/></Field><Field label="数据处理依据"><input name="processing_basis" required minLength={5} maxLength={500}/></Field><Field label="显示时区"><input name="display_timezone" required defaultValue="Asia/Shanghai"/></Field>
      <Field label="原文件访问范围"><select name="original_access"><option value="owner_admin">上传者和管理员</option><option value="brand">当前品牌内成员</option></select></Field><Field label="原文件保留天数"><input name="original_retention_days" type="number" min={1} max={30} defaultValue={7} required/></Field><Field label="数据保留天数"><input name="retention_days" type="number" min={1} max={30} defaultValue={7} required/></Field></div>
      <fieldset className="collection-field-choice"><legend>来源允许导出的字段</legend>{Object.entries(fields).map(([key,label])=><label key={key}><input name="export_fields" type="checkbox" value={key} defaultChecked/>{label}</label>)}</fieldset>
      <p className="field-hint">8 MiB 以内，每表最多 1000 数据行、32 列、5 个工作表。ID 请保存为文本。相同来源标识与账号下按原始 ID 去重。</p><button className="button primary" disabled={busy}>上传并解析文件</button>
    </fieldset></form>}
    {files.length>0&&<div className="import-files"><h3>已保存的导入文件</h3>{files.map(file=><button key={file.id} className="text-button" disabled={busy} onClick={()=>void select(file.id)}>{file.configuration.title} · {file.configuration.filename}{file.query_id?' · 已入库':''}</button>)}</div>}
    {detail&&<div className="import-detail" aria-label="导入文件详情"><h3>{detail.configuration.title}</h3><p className="field-hint">原文件 {detail.byte_length} 字节 · 人工来源 {detail.configuration.source_namespace}</p><details><summary>文件摘要与保留期</summary><code>{detail.file_hash}</code><p>原文件至 {new Date(detail.original_expires_at).toLocaleString('zh-CN')}；数据至 {new Date(detail.expires_at).toLocaleString('zh-CN')}</p></details><button className="text-button" disabled={busy} onClick={()=>void act(async()=>saveDownload(await fetch('/api/imports/'+detail.id+'/original'),detail.configuration.filename))}>下载保存的原文件</button>
      {detail.expired?<p className="alert warning">数据保留期已结束，不能继续预览或入库。</p>:detail.confirmation?<button className="button subtle" onClick={()=>onConfirmed(detail.confirmation!.query_id)}>查看已入库结果</button>:data.scope.role!=='viewer'&&<>
      <div className="form-grid"><Field label="工作表"><select disabled={busy} value={sheet} onChange={event=>{setSheet(Number(event.target.value));setHeaderRow(1);}}>{detail.sheets.map((item,index)=><option value={index} key={index}>{item.name} · {item.row_count} 行</option>)}</select></Field><Field label="表头行号"><input disabled={busy} value={headerRow} onChange={event=>setHeaderRow(Number(event.target.value))} type="number" min={1} max={Math.min(20,detail.sheets[sheet]?.row_count??1)}/></Field></div>
      <form key={detail.id+'/'+sheet+'/'+headerRow} aria-label="字段映射" onSubmit={event=>void preview(event)}><fieldset disabled={busy}><div className="form-grid"><Field label="对象 ID 列"><select name="source_object_id" defaultValue={defaultColumn('source_object_id')} required><option value="">请选择</option>{options}</select></Field><Field label="文本编码方式"><select name="text_encoding" defaultValue={names.some(column=>column.label==='_kff_text_encoding')&&detail.configuration.format==='csv'?'kff-apostrophe-v1':'plain'}><option value="plain">普通文本 / XLSX 文本类型</option><option value="kff-apostrophe-v1">KFF CSV 文本转义格式</option></select></Field>
        {Object.entries(fields).map(([key,label])=><div className="import-field-pair" key={key}><Field label={label+'列'}><select name={key} defaultValue={defaultColumn(key)}><option value="">不导入</option>{options}</select></Field><Field label={label+'状态列'}><select name={key+'__kind'} defaultValue={defaultColumn(key+'__kind')}><option value="">根据单元格判断</option>{options}</select></Field></div>)}</div><button className="button subtle">生成验证预览</button></fieldset></form>
      </>}
      {previewData&&<div className="import-preview" aria-label="导入验证预览"><h3>验证预览</h3><p>原始 {previewData.summary.total_rows} 行 · 有效 {previewData.summary.valid_rows} 行 · 错误 {previewData.summary.error_rows} 行 · 去重后 {previewData.summary.unique_objects} 个对象</p><p className="field-hint">文件内重复 {previewData.summary.duplicate_rows} 行；已存在同源对象 {previewData.summary.existing_objects.length} 个。有效重复行将保留为新的观察版本。</p>
        <label className="import-filter"><input type="checkbox" checked={errorsOnly} onChange={event=>{setErrorsOnly(event.target.checked);setPage(0);}}/>仅显示错误行</label><div className="table-scroll"><table aria-label="导入行预览"><thead><tr><th>原始行号</th><th>原始对象 ID</th><th>验证结果</th><th>映射内容</th></tr></thead><tbody>{shown.slice(page*25,page*25+25).map(row=><tr key={row.row_number} className={row.errors.length ? "import-row-error" : undefined}><td>{row.row_number}</td><td className="mono">{row.source_object_id??'无法读取'}</td><td>{row.errors.length?row.errors.map(rowError).join('；'):row.duplicate_in_file?'有效 · 文件内重复':'有效'}</td><td>{row.record&&Object.entries(row.record.fields).map(([key,value])=><div key={key}>{fields[key as keyof typeof fields]}：{value.kind==='VALUE'?(value.value===''?'空字符串':String(value.value)):value.kind==='NULL'?'空值':value.kind==='HIDDEN'?'来源隐藏':'来源未返回'}</div>)}</td></tr>)}</tbody></table></div><div className="panel-footer"><span>{shown.length} 行 · 第 {page+1} 页</span><button className="text-button" disabled={!page} onClick={()=>setPage(value=>value-1)}>上一页预览</button><button className="text-button" disabled={(page+1)*25>=shown.length} onClick={()=>setPage(value=>value+1)}>下一页预览</button></div>
        {!detail.confirmation&&!detail.expired&&data.scope.role!=='viewer'&&<form key={previewData.id} onSubmit={event=>{event.preventDefault();void act(async()=>{const value={preview_id:previewData.id,preview_hash:previewData.preview_hash,excluded_error_rows:previewData.summary.error_rows,confirm_valid_rows:true};const result=await api<{query_id:string}>('imports/'+detail.id+'/confirmations',{...value,request_id:request({id:detail.id,...value})});setDetail(await api<Detail>('imports/'+detail.id));onConfirmed(result.query_id);setNotice('有效行已入库，原始来源和观察版本已保存。');});}}><label className="import-confirm"><input type="checkbox" required disabled={busy}/>我已核对预览，确认导入 {previewData.summary.valid_rows} 个有效行，排除 {previewData.summary.error_rows} 个错误行。</label><button className="button primary" disabled={busy||!previewData.summary.valid_rows}>确认有效行入库</button></form>}
      </div>}
    </div>}
  </details></section>;
}
