'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import type {Workspace} from '@kff/core/service';
import type {leadAnalytics,leadAudit,LeadMetric} from '@kff/core/lead-management';
import {businessRequest,businessTime} from './business-ui';
import {actionNames,sourceNames} from './lead-ui';
type Report=Awaited<ReturnType<typeof leadAnalytics>>;
const percent=(n:number|null)=>n===null?'—':(n*100).toFixed(1)+'%';
export function LeadAnalytics({data}:{data:Workspace}){
  const [report,setReport]=useState<Report|null>(null),[audit,setAudit]=useState<Awaited<ReturnType<typeof leadAudit>>|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const today=new Date().toISOString().slice(0,10);
  const load=useCallback(async(query:string)=>{setBusy(true);setError('');try{const [next,logs]=await Promise.all([businessRequest<Report>('lead-analytics?'+query),businessRequest<Awaited<ReturnType<typeof leadAudit>>>('lead-audit')]);setReport(next);setAudit(logs);}catch(failure){setError(failure instanceof Error?failure.message:'统计暂时无法读取');}finally{setBusy(false);}},[]);
  useEffect(()=>{void load(new URLSearchParams({from:today,to:today,synthetic:'true'}).toString());},[load,today]);
  function filter(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget),query=new URLSearchParams({from:String(fields.get('from')),to:String(fields.get('to')),synthetic:String(fields.get('synthetic'))});if(fields.get('account_id'))query.set('account_id',String(fields.get('account_id')));void load(query.toString());}
  const total=report?.metrics.find(row=>row.group_kind==='TOTAL');
  return <div className="business-workbench lead-analytics">{error&&<p className="alert warning" role="alert">{error}</p>}<section className="business-box"><form className="business-form" aria-label="引流统计筛选" onSubmit={filter}><label>开始日期（UTC）<input name="from" type="date" required defaultValue={today}/></label><label>结束日期（UTC）<input name="to" type="date" required defaultValue={today}/></label><label>数据范围<select name="synthetic"><option value="true">本地合成数据</option><option value="false">真实 Facebook 数据</option></select></label><label>Facebook 账号<select name="account_id"><option value="">本品牌全部账号</option>{data.accounts.filter(row=>row.platform==='facebook').map(row=><option key={row.id} value={row.id}>{row.display_name}</option>)}</select></label><button className="button primary" disabled={busy}>刷新引流统计</button></form></section>
    {total&&<><div className="business-counts lead-counts">{[['新客户',total.new_customers],['客户私信',total.inbound_messages],['自动回复',total.ai_replies],['人工接管',total.handoffs],['有效咨询',total.valid_inquiries],['高意向',total.high_intent],['已确认邀请',total.referrals],['客户已联系',total.confirmed]].map(([label,count])=><div key={label}><span>{label}</span><strong>{count}</strong></div>)}</div><section className="business-box"><h2>有效咨询 → WhatsApp 邀请</h2><p className="lead-conversion">{percent(total.conversion_rate)} <small>{total.referred_valid_customers} / {total.valid_inquiries} 位客户</small></p><p className="muted">分母为本期新建客户中当前标记为有效咨询的人数；分子为其中本期已有确认发送邀请的客户人数。同一客户只计一次。邀请次数另计，结果未知不计成功；客户实际添加需人工核实。日期按 UTC，合成与真实数据分开。</p></section></>}
    {report&&<><section className="business-box"><h2>自动与人工回复观察</h2><p className="muted">按已确认回复统计客户与后续来信；有效咨询使用当前标记，不推断因果或成交。</p><div className="lead-table"><table><thead><tr><th>接待方式</th><th>已确认回复</th><th>接待客户</th><th>当前有效咨询</th><th>回复后继续来信</th></tr></thead><tbody>{report.outcomes.map(row=><tr key={row.actor_kind}><td>{row.actor_kind==='AI'?'自动':'人工'}</td><td>{row.replies}</td><td>{row.customers}</td><td>{row.valid_customers}</td><td>{row.subsequent_inquiries}</td></tr>)}</tbody></table></div></section><MetricTable title="按 Facebook 账号" rows={report.metrics.filter(row=>row.group_kind==='ACCOUNT')} dimension={row=>row.account_name??'未知账号'}/><MetricTable title="按首次获客来源" rows={report.metrics.filter(row=>row.group_kind==='SOURCE')} dimension={row=>sourceNames[row.source??'UNKNOWN']??row.source??'未知'}/><MetricTable title="按日期（UTC）" rows={report.metrics.filter(row=>row.group_kind==='DAY')} dimension={row=>row.day??''}/><section className="business-box"><h2>接待判断与引流话术</h2><p className="muted">这些计数反映实际判断、发送和人工记录，不能证明 AI 带来了成交。</p><div className="lead-table"><table><thead><tr><th>判断方式</th><th>建议</th><th>次数</th></tr></thead><tbody>{report.decisions.map(row=><tr key={row.model+'/'+row.action}><td>{row.model==='LOCAL_RULES'?'本地规则预演':'模型接口'}</td><td>{actionNames[row.action]??row.action}</td><td>{row.count}</td></tr>)}</tbody></table></div><div className="lead-table"><table><thead><tr><th>话术版本</th><th>引流方式</th><th>此次来源</th><th>确认邀请</th><th>客户已联系</th></tr></thead><tbody>{report.templates.map((row,index)=><tr key={index}><td>{row.destination_id.slice(0,8)} · v{row.destination_version}</td><td>{row.actor_kind==='AI'?'自动':'人工'}</td><td>{sourceNames[row.source]??row.source}</td><td>{row.sent}</td><td>{row.confirmed}</td></tr>)}</tbody></table></div></section></>}
    <section className="business-box reception-history" aria-label="引流操作日志"><h2>操作与审计日志</h2><p className="muted">本品牌最近 200 条记录，覆盖收件、判断、接管、配置和客户修改。</p>{audit?.events.map(row=><article key={row.id}><strong>{row.event_type}</strong><small>{businessTime(row.created_at)} · 操作人 {row.actor_id.slice(0,8)} · 对象 {row.object_id.slice(0,8)}</small><p>{Object.entries(row.details).map(([key,value])=>key+': '+String(value)).join(' · ')}</p></article>)}</section>
  </div>;
}
function MetricTable({title,rows,dimension}:{title:string;rows:LeadMetric[];dimension:(row:LeadMetric)=>string}){return <section className="business-box"><h2>{title}</h2><div className="lead-table"><table><thead><tr><th>范围</th><th>新客户</th><th>有效咨询</th><th>客户私信</th><th>自动 / 人工回复</th><th>确认邀请</th><th>客户转化率</th></tr></thead><tbody>{rows.map((row,index)=><tr key={index}><td>{dimension(row)}</td><td>{row.new_customers}</td><td>{row.valid_inquiries}</td><td>{row.inbound_messages}</td><td>{row.ai_replies} / {row.human_replies}</td><td>{row.referrals}</td><td>{percent(row.conversion_rate)}</td></tr>)}</tbody></table>{!rows.length&&<p className="muted">此范围尚无数据。</p>}</div></section>;}
