'use client';
import {useState,type FormEvent} from 'react';
import type {Customer} from '../../../packages/contracts/src/inbox';
import {leadStatuses} from '../../../packages/contracts/src/lead';
import {businessRequest,businessTime} from './business-ui';
import {leadNames,intentNames,sourceNames} from './lead-ui';
import {useRequestKey} from './use-request-key';
export function LeadCustomer({customer,writable,onSaved}:{customer:Customer;writable:boolean;onSaved:()=>Promise<void>}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false);const request=useRequestKey(),source=customer.acquisition_source;
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget);setBusy(true);setError('');const payload={expected_version:customer.version,lead_status:fields.get('lead_status'),intent_level:fields.get('intent_level'),valid_inquiry:fields.get('valid_inquiry')==='on',tags:String(fields.get('tags')).split(/[,，\n]/).map(v=>v.trim()).filter(Boolean),reason:fields.get('reason')};try{await businessRequest('customers/'+customer.id+'/lead',{...payload,request_id:request.forPayload(payload)});request.confirmed();await onSaved();}catch(failure){setError(failure instanceof Error?failure.message:'客户判断未保存');}finally{setBusy(false);}}
  return <section className="lead-customer" aria-label="客户意向与引流"><div className="customer-origin"><p><strong>获客来源</strong> {sourceNames[String(source?.kind??'UNKNOWN')]??'未知'}</p>{source&&<><p>Page：{String(source.page_id??'未知')} · 来源对象：{String(source.source_id??'未提供')}</p><p>活动：{String(source.ref??'未提供')} · 广告：{String(source.ad_id??'未提供')}</p></>}<p>首次互动 {businessTime(customer.first_interaction_at)} · 最近互动 {businessTime(customer.last_interaction_at)}</p><p><strong>{leadNames[customer.lead_status]}</strong> · {intentNames[customer.intent_level]} · {customer.valid_inquiry?'有效咨询':'待资格核对'}</p><p>{customer.intent_reason??'尚无意图判断依据'}</p></div>
    <form key={customer.version} className="business-form" aria-label="编辑客户意向" onSubmit={event=>void save(event)}><label>引流阶段<select name="lead_status" disabled={!writable} defaultValue={customer.lead_status}>{leadStatuses.map(key=><option key={key} value={key}>{leadNames[key]}</option>)}</select></label><label>意向等级<select name="intent_level" disabled={!writable} defaultValue={customer.intent_level}>{Object.entries(intentNames).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="business-wide">客户标签（逗号分隔）<input name="tags" disabled={!writable} defaultValue={customer.tags.join(', ')}/></label><label><input type="checkbox" name="valid_inquiry" defaultChecked={customer.valid_inquiry} disabled={!writable}/> 已核实为有效咨询</label>{writable&&<><label className="business-wide">判断依据<input name="reason" required maxLength={500}/></label><small className="business-wide muted">忽略、停止接待或交销售跟进会暂停自动接待。手动标记阶段不会生成 WhatsApp 发送证据。</small><button className="button subtle" disabled={busy}>保存客户意向</button></>}{error&&<p role="alert" className="business-wide">{error}</p>}</form>
  </section>;
}
