'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import type {Workspace} from '@kff/core/service';
import type {commerceWorkspace,ownedOrderDetail,productHistory} from '@kff/core/orders';
import {displayMinor,type CatalogProduct,type OrderPreview,type OrderSnapshot} from '../../../packages/contracts/src/order';
import {businessRequest,businessTime} from './business-ui';
import {useRequestKey} from './use-request-key';
import {StripeSettings,StripeOrderPayment} from './stripe-payment';

type Commerce=Awaited<ReturnType<typeof commerceWorkspace>>;
type OrderDetail=Awaited<ReturnType<typeof ownedOrderDetail>>;
const amount=(minor:string,currency:string,exponent:number)=>currency+' '+displayMinor(minor,exponent);
export function OrderWorkbench({data}:{data:Workspace}){
  const [commerce,setCommerce]=useState<Commerce|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState(''),[editing,setEditing]=useState<CatalogProduct|null>(null),[history,setHistory]=useState<Awaited<ReturnType<typeof productHistory>>|null>(null);
  const refresh=useCallback(async()=>{setCommerce(await businessRequest<Commerce>('commerce'));},[]);
  useEffect(()=>{setSelected(new URLSearchParams(window.location.search).get('order')??'');void refresh().catch(failure=>setError(failure.message));},[refresh]);
  if(!commerce)return <p role="status">{error||'正在读取商品与订单…'}</p>;
  return <div className="business-workbench orders-workbench">{error&&<p className="alert warning" role="alert">{error}</p>}
    <div className="business-toolbar"><p>保存报价与订单条款，支付与交付分别核实。</p><button className="button subtle" onClick={()=>void refresh().catch(failure=>setError(failure.message))}>刷新订单与商品</button></div>
    <StripeSettings admin={data.scope.role==='admin'}/>
    <details className="business-box catalog-settings"><summary>商品与价格版本 <span>{commerce.products.length} 个</span></summary><div className="table-scroll"><table aria-label="商品列表"><thead><tr><th>商品</th><th>单价</th><th>当前版本</th><th>操作</th></tr></thead><tbody>{commerce.products.map(product=><tr key={product.id}><td><strong>{product.definition.name}</strong><small>{product.sku}</small></td><td>{amount(product.definition.unit_amount_minor,product.definition.currency,product.definition.minor_unit_exponent)}</td><td>v{product.definition.version_number}<small>{product.state==='ACTIVE'?'已启用':product.state==='DRAFT'?'草稿待启用':'已停用'}</small></td><td><div className="catalog-actions"><button className="text-button" onClick={()=>void businessRequest<Awaited<ReturnType<typeof productHistory>>>('products/'+product.id).then(setHistory).catch(failure=>setError(failure.message))}>历史版本</button>{data.scope.role==='admin'&&<button className="text-button" onClick={()=>setEditing(product)}>修改商品</button>}</div>{data.scope.role==='admin'&&<ProductControl key={product.version} product={product} onSaved={refresh}/>}</td></tr>)}</tbody></table></div>
      {history&&<section className="catalog-history" aria-label="商品历史版本"><h3>{history.product.definition.name} · 历史版本</h3>{history.versions.map(version=><article key={version.id}><strong>v{version.version_number} · {amount(version.unit_amount_minor,version.currency,version.minor_unit_exponent)}</strong><p>{version.delivery_scope}</p><p>{version.terms}</p><small>{businessTime(version.created_at)}</small></article>)}<button className="text-button" onClick={()=>setHistory(null)}>关闭历史版本</button></section>}
      {data.scope.role==='admin'&&<ProductForm key={editing?editing.id+':'+editing.version:'new'} editing={editing} onSaved={async()=>{setEditing(null);await refresh();}} onCancel={()=>setEditing(null)}/>}
    </details>
    <div className="order-layout"><div className="order-sidebar">{data.scope.role!=='viewer'&&<OrderComposer commerce={commerce} onSaved={async id=>{setSelected(id);await refresh();}}/>}
      <section className="business-box order-list" aria-label="订单列表"><div className="business-box-head"><h2>最近订单</h2><span>最多 200 笔</span></div>{commerce.orders.length===0&&<p className="business-empty">还没有订单。先启用商品，为已有客户核对报价。</p>}{commerce.orders.map(order=><button key={order.id} className={'conversation-item '+(selected===order.id?'selected':'')} onClick={()=>setSelected(order.id)}><span><strong>{order.snapshot.customer_display_name??'匿名客户'} · {amount(order.snapshot.total_minor,order.snapshot.currency,order.snapshot.minor_unit_exponent)}</strong><small>{order.id.slice(0,8)} · {order.state==='CANCELED'?'已取消':order.payment_state==='VERIFIED_PAID'?'已付款':order.payment_state==='VERIFIED_TEST_PAID'?'测试付款已核实':'待核实'} · {businessTime(order.created_at)}</small></span></button>)}</section>
    </div>{selected?<OrderPanel key={selected} id={selected} writable={data.scope.role!=='viewer'} onSaved={refresh}/>:<div className="business-box business-empty">选择订单，查看创建时的商品、价格和条款。</div>}</div>
  </div>;
}
function ProductForm({editing,onSaved,onCancel}:{editing:CatalogProduct|null;onSaved:()=>Promise<void>;onCancel:()=>void}){
  const [busy,setBusy]=useState(false),[error,setError]=useState('');const key=useRequestKey();
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,fields=new FormData(form);setBusy(true);setError('');
    const payload={...(editing?{expected_version:editing.version}:{}),sku:fields.get('sku'),name:fields.get('name'),currency:fields.get('currency'),minor_unit_exponent:Number(fields.get('exponent')),precision_source:fields.get('precision_source'),unit_amount_minor:fields.get('amount'),delivery_scope:fields.get('delivery_scope'),terms:fields.get('terms')};
    try{await businessRequest(editing?'products/'+editing.id+'/versions':'products',{request_id:key.forPayload(payload),...payload});key.confirmed();form.reset();await onSaved();}catch(failure){setError(failure instanceof Error?failure.message:'商品未保存');}finally{setBusy(false);}
  }
  return <form className="business-form" aria-label="商品版本表单" onSubmit={event=>void save(event)}><h3>{editing?'保存新的商品版本':'新增商品'}</h3>{error&&<p role="alert" className="alert warning business-wide">{error}</p>}
    <label>商品名称<input name="name" required maxLength={120} defaultValue={editing?.definition.name}/></label><label>商品 SKU<input name="sku" required pattern="[A-Za-z0-9._\-]{1,80}" title="1–80 位字母、数字、点、下划线或连字符" placeholder="例如 SERVICE-01" maxLength={80} defaultValue={editing?.sku} readOnly={!!editing}/></label>
    <label>币种代码<input name="currency" required pattern="[A-Z]{3}" maxLength={3} placeholder="例如 USD" defaultValue={editing?.definition.currency}/></label><label>金额小数位<input name="exponent" type="number" min={0} max={6} required defaultValue={editing?.definition.minor_unit_exponent}/></label>
    <label>精度依据<input name="precision_source" required minLength={5} maxLength={300} placeholder="登记币种小数位的依据" defaultValue={editing?.definition.precision_source}/></label><label>单价（最小单位整数）<input name="amount" inputMode="numeric" required pattern="(0|[1-9][0-9]{0,14})" defaultValue={editing?.definition.unit_amount_minor} placeholder="小数位为 2 时，1250 表示 12.50"/></label>
    <label className="business-wide">交付范围<textarea aria-label="交付范围" name="delivery_scope" required maxLength={2000} rows={2} defaultValue={editing?.definition.delivery_scope}/></label><label className="business-wide">订单条款<textarea aria-label="订单条款" name="terms" required maxLength={4000} rows={3} defaultValue={editing?.definition.terms}/></label>
    <p className="business-wide muted">新版本保存为草稿，启用后才能建单；同一币种沿用本品牌首次登记的精度依据。</p><div className="catalog-actions"><button className="button primary" disabled={busy}>保存商品草稿</button>{editing&&<button type="button" className="button subtle" onClick={onCancel}>取消修改</button>}</div>
  </form>;
}
function ProductControl({product,onSaved}:{product:CatalogProduct;onSaved:()=>Promise<void>}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false);const key=useRequestKey();
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget);setBusy(true);setError('');const payload={expected_version:product.version,state:product.state==='ACTIVE'?'ARCHIVED':'ACTIVE',reason:fields.get('reason')};try{await businessRequest('products/'+product.id+'/controls',{request_id:key.forPayload(payload),...payload});key.confirmed();await onSaved();}catch(failure){setError(failure instanceof Error?failure.message:'商品状态未更新');}finally{setBusy(false);}}
  return <form aria-label={'管理商品 '+product.sku} className="product-control" onSubmit={event=>void save(event)}><label>启停依据<input name="reason" required maxLength={300}/></label><button className="button small subtle" disabled={busy}>{product.state==='ACTIVE'?'停用商品':'启用商品'}</button>{error&&<small role="alert">{error}</small>}</form>;
}
function OrderComposer({commerce,onSaved}:{commerce:Commerce;onSaved:(id:string)=>Promise<void>}){
  const [customerId,setCustomerId]=useState(''),[lines,setLines]=useState([{key:'first',product_id:'',quantity:1}]),[preview,setPreview]=useState<OrderPreview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const requestKey=useRequestKey(),confirmKey=useRequestKey();
  useEffect(()=>setCustomerId(new URLSearchParams(window.location.search).get('customer')??''),[]);
  async function prepare(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const fields=new FormData(event.currentTarget);const payload={customer_id:customerId,conversation_id:String(fields.get('conversation')??'').trim()||null,items:lines.map(({product_id,quantity})=>({product_id,quantity}))};try{setPreview(await businessRequest<OrderPreview>('order-previews',{request_id:requestKey.forPayload(payload),...payload}));requestKey.confirmed();}catch(failure){setError(failure instanceof Error?failure.message:'报价预览未生成');}finally{setBusy(false);}}
  async function confirm(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!preview)return;setBusy(true);setError('');const payload={preview_id:preview.id,preview_hash:preview.snapshot_hash,confirmed_total_minor:preview.snapshot.total_minor,currency:preview.snapshot.currency,confirmation:'CREATE_THIS_ORDER'};try{const result=await businessRequest<{id:string}>('orders',{request_id:confirmKey.forPayload(payload),...payload});confirmKey.confirmed();setPreview(null);await onSaved(result.id);}catch(failure){setError(failure instanceof Error?failure.message:'订单尚未确认');}finally{setBusy(false);}}
  return <section className="business-box order-composer" aria-label="创建订单"><div className="business-box-head"><h2>为客户创建订单</h2></div>{error&&<p role="alert" className="alert warning">{error}</p>}
    <form aria-label="订单项目表单" onSubmit={event=>void prepare(event)} onChange={()=>setPreview(null)}><label>订单客户<select aria-label="订单客户" required value={customerId} onChange={event=>setCustomerId(event.target.value)}><option value="">选择已有客户</option>{commerce.customers.map(customer=><option key={customer.id} value={customer.id}>{customer.display_name??'匿名访客'} · {customer.id.slice(0,8)}</option>)}</select></label><label>来源会话 ID（选填）<input name="conversation" placeholder="只能关联这位客户的会话"/></label>
      {lines.map((line,index)=><div className="order-item-edit" key={line.key}><label>商品 {index+1}<select aria-label={'商品 '+(index+1)} required value={line.product_id} onChange={event=>setLines(previous=>previous.map(row=>row.key===line.key?{...row,product_id:event.target.value}:row))}><option value="">选择已启用商品</option>{commerce.products.filter(product=>product.state==='ACTIVE').map(product=><option key={product.id} value={product.id}>{product.definition.name} · {amount(product.definition.unit_amount_minor,product.definition.currency,product.definition.minor_unit_exponent)}</option>)}</select></label><label>数量 {index+1}<input aria-label={'数量 '+(index+1)} type="number" required min={1} max={1000} value={line.quantity} onChange={event=>setLines(previous=>previous.map(row=>row.key===line.key?{...row,quantity:Number(event.target.value)}:row))}/></label>{lines.length>1&&<button type="button" className="text-button" onClick={()=>{setLines(previous=>previous.filter(row=>row.key!==line.key));setPreview(null);}}>移除</button>}</div>)}
      <div className="catalog-actions"><button className="button subtle" type="button" disabled={lines.length>=50} onClick={()=>{setLines(previous=>[...previous,{key:crypto.randomUUID(),product_id:'',quantity:1}]);setPreview(null);}}>添加商品行</button><button className="button primary" disabled={busy}>预览订单报价</button></div>
    </form>{preview&&<form aria-label="确认订单报价" className="order-confirm" onSubmit={event=>void confirm(event)}><Snapshot snapshot={preview.snapshot}/><p className="muted">预览有效至 {businessTime(preview.expires_at)}</p><label className="order-checkbox"><input type="checkbox" required/>已核对客户、商品、总额、交付范围和条款</label><button className="button primary" disabled={busy}>确认创建订单</button></form>}
  </section>;
}
function Snapshot({snapshot}:{snapshot:OrderSnapshot}){return <div className="order-snapshot"><p className="order-total">{amount(snapshot.total_minor,snapshot.currency,snapshot.minor_unit_exponent)}</p><p className="muted">以下项目合计，运费或税费如适用需列为明确报价项目。</p>{snapshot.lines.map(line=><article key={line.product_id}><h3>{line.name} <small>v{line.product_version_number}</small></h3><p>{line.quantity} × {amount(line.unit_amount_minor,snapshot.currency,snapshot.minor_unit_exponent)} = {amount(line.line_total_minor,snapshot.currency,snapshot.minor_unit_exponent)}</p><dl><dt>交付范围</dt><dd>{line.delivery_scope}</dd><dt>订单条款</dt><dd>{line.terms}</dd></dl></article>)}</div>;}
function OrderPanel({id,writable,onSaved}:{id:string;writable:boolean;onSaved:()=>Promise<void>}){
  const [detail,setDetail]=useState<OrderDetail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const requestKey=useRequestKey();
  const refresh=useCallback(async()=>setDetail(await businessRequest<OrderDetail>('orders/'+id)),[id]);useEffect(()=>{void refresh().catch(failure=>setError(failure.message));},[refresh]);
  async function cancel(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!detail)return;const fields=new FormData(event.currentTarget),payload={expected_version:detail.order.version,reason:fields.get('reason')};setBusy(true);setError('');try{await businessRequest('orders/'+id+'/cancel',{request_id:requestKey.forPayload(payload),...payload});requestKey.confirmed();await refresh();await onSaved();}catch(failure){setError(failure instanceof Error?failure.message:'取消未完成');}finally{setBusy(false);}}
  return <section className="business-box order-panel" aria-label="订单详情">{error&&<p role="alert" className="alert warning">{error}</p>}{detail&&<><div className="business-box-head"><div><h2>订单 {id.slice(0,8)}</h2><p>{businessTime(detail.order.created_at)}</p></div><span className="badge neutral">{detail.order.state==='CANCELED'?'已取消':detail.order.payment_state==='VERIFIED_PAID'?'已付款':detail.order.payment_state==='VERIFIED_TEST_PAID'?'测试付款已核实':'待核实'}</span></div><div className="order-identity"><Link href={'/customers?customer='+detail.order.customer_id}>{detail.order.snapshot.customer_display_name??'匿名客户'} · 客户档案 →</Link>{detail.order.conversation_id&&<Link href={'/inbox?conversation='+detail.order.conversation_id}>来源会话 →</Link>}<p>支付：{detail.order.payment_state==='VERIFIED_PAID'?'已核实付款':detail.order.payment_state==='VERIFIED_TEST_PAID'?'测试支付已核实':'尚未核实'} · Stripe</p><p>交付：尚无交付记录</p></div><StripeOrderPayment order={detail.order} writable={writable} onSaved={async()=>{await refresh();await onSaved();}}/><Snapshot snapshot={detail.order.snapshot}/><div className="order-records"><h3>订单记录</h3>{detail.events.map(event=><p key={event.id}>{event.event_type==='CREATED'?'已创建订单':'已取消订单'} · {businessTime(event.created_at)}{event.details.reason&&<small>{event.details.reason}</small>}</p>)}</div>{writable&&detail.can_cancel&&<form className="order-cancel" aria-label="取消订单" onSubmit={event=>void cancel(event)}><label>取消订单的原因<input name="reason" required maxLength={500}/></label><button className="button subtle" disabled={busy}>取消此订单</button></form>}</>}</section>;
}
