'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import type {Scope} from '@kff/contracts';
import type {InboxConversation} from '../../../packages/contracts/src/inbox';
import type {conversationReception} from '@kff/core/lead-reception';
import {businessRequest,businessTime} from './business-ui';
import {modeNames,leadNames,actionNames} from './lead-ui';
type Reception=Awaited<ReturnType<typeof conversationReception>>;
export function ReceptionControls({conversation,role,onSaved}:{conversation:InboxConversation;role:Scope['role'];onSaved:()=>Promise<void>}){
  const [data,setData]=useState<Reception|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [replyBody,setReplyBody]=useState(''),[referralSelected,setReferralSelected]=useState(false),[adopted,setAdopted]=useState<{job_id:string;conversation_id:string;control_version:number}|null>(null);
  const realBrowser=conversation.channel_kind==='FACEBOOK_BROWSER_MESSENGER'&&!conversation.is_synthetic;
  const consentDefault=useRef(new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16));
  const pending=useRef<{key:string;path:string;payload:Record<string,unknown>}|null>(null);
  const load=useCallback(async()=>{setData(await businessRequest<Reception>('conversations/'+conversation.id+'/reception'));},[conversation.id]);
  useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;const tick=async()=>{try{const result=await businessRequest<Reception>('conversations/'+conversation.id+'/reception',undefined,controller.signal);setData(result);}catch(failure){if(!controller.signal.aborted)setError(failure instanceof Error?failure.message:'接待状态暂时无法读取');}finally{if(!controller.signal.aborted)timer=setTimeout(()=>void tick(),5000);}};void tick();return()=>{controller.abort();clearTimeout(timer);};},[conversation.id]);
  // Selecting AI mode and actually running reception are different facts. The control response
  // reports whether a job is behind the conversation and why not when there is none, so the operator
  // is told "AI mode is selected but not active" instead of a bare success message. Nothing here
  // changes an account switch.
  const [receptionStatus,setReceptionStatus]=useState<{active:boolean;label:string;job_id:string|null}|null>(null);
  async function perform(path:string,value:Record<string,unknown>,success:string){
    if(busy)return;setBusy(true);setError('');setNotice('');
    // The pending payload retains its original control version across refreshes after a lost response.
    const key=JSON.stringify({path,...value});if(pending.current?.key!==key)pending.current={key,path,payload:{...value,request_id:crypto.randomUUID(),expected_version:conversation.control_version}};
    try{const result=await businessRequest<{reception_status?:{active:boolean;label:string;job_id:string|null}}>(path,pending.current.payload);pending.current=null;setNotice(success);setReceptionStatus(result?.reception_status??null);await Promise.all([load(),onSaved()]);}
    catch(failure){if(failure&&typeof failure==='object'&&'status' in failure)pending.current=null;setError(failure instanceof Error?failure.message:'操作未完成，请保留原内容重试');}finally{setBusy(false);}
  }
  async function reply(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,fields=new FormData(form),referral=fields.get('refer_whatsapp')==='on';const pilot=realBrowser||(event.nativeEvent as SubmitEvent).submitter?.getAttribute('name')==='pilot';await perform('conversations/'+conversation.id+(pilot?'/pilot-reply':'/replies'),{body:String(fields.get('body')??'').trim(),refer_whatsapp:referral,delay_minutes:Number(fields.get('delay_minutes')??0),fixture_scenario:'normal',...(adopted?{draft_job_id:adopted.job_id}:{}),...(realBrowser?{contact_permission_id:fields.get('contact_permission_id')}:{})},pilot?'试验任务已准备，请在任务工作台核对并登记许可。':'人工回复已入队，确认回执后显示为已发送。');}
  async function recordConsent(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget),observed=new Date(String(fields.get('consented_at'))).getTime(),minutes=Number(fields.get('minutes'));if(!Number.isFinite(observed)||!Number.isFinite(minutes)){setError('请填写同意时间和有效期');return;}await perform('conversations/'+conversation.id+'/browser-consent',{consented_at:new Date(observed).toISOString(),expires_at:new Date(observed+minutes*60000).toISOString(),evidence_note:String(fields.get('evidence_note')??''),confirmation:fields.get('confirmed')==='on'?'CUSTOMER_CONFIRMED_THIS_CONTACT':''},'客户同意已登记。请选择这条记录，再准备回复任务。');}
  const stoppedLead=conversation.opted_out||['IGNORED','BLOCKED','HANDOFF_COMPLETE'].includes(conversation.lead_status);
  const draftInvalid=!!adopted&&(adopted.conversation_id!==conversation.id||adopted.control_version!==conversation.control_version||!data?.jobs.some(job=>job.id===adopted.job_id&&job.draft_usable));
  const draftPending=data?.jobs.some(job=>job.draft_only&&['READY','LEASED'].includes(job.state));
  const unsafe=data?.replies.some(row=>['SUBMITTING','SUBMITTED','UNKNOWN_OUTCOME'].includes(row.state));
  return <div className="lead-reception" aria-label="接待控制">
    {realBrowser&&role==='admin'&&<details><summary>登记本次客户同意</summary><form className="business-form" aria-label="客户同意记录" onSubmit={event=>void recordConsent(event)}><label>同意发生时间<input name="consented_at" type="datetime-local" required defaultValue={consentDefault.current}/></label><label>本次有效期（分钟）<input name="minutes" type="number" min={1} max={60} required defaultValue={30}/></label><label className="business-wide">同意依据<textarea name="evidence_note" required minLength={10} maxLength={1000} placeholder="记录客户同意本次联系的原话或核实依据"/></label><label className="business-wide"><input name="confirmed" type="checkbox" required/> 已核实客户明确同意本次联系</label><button className="button subtle" disabled={busy||conversation.opted_out}>保存同意记录</button></form></details>}
    <div className="conversation-context"><strong>{modeNames[conversation.handling_mode]}</strong><span>{leadNames[conversation.lead_status]}</span></div>
    {error&&<p className="alert warning" role="alert">{error}</p>}{notice&&<p role="status" className="business-success">{notice}</p>}
    {unsafe&&<p className="alert warning">有正在提交或结果未知的回复。接管可阻止后续自动发送；请先核验原提交，再发下一条。</p>}
    {receptionStatus&&<p className={receptionStatus.active?'field-hint':'alert warning'} role="note">{receptionStatus.active?'AI 模式已选择，当前已激活：'+receptionStatus.label:'AI 模式已选择，当前未激活：'+receptionStatus.label}</p>}
    {role!=='viewer'&&<><form className="business-form" aria-label="切换接待方式" onSubmit={event=>{event.preventDefault();const fields=new FormData(event.currentTarget);void perform('conversations/'+conversation.id+'/controls',{mode:String(fields.get('mode')),reason:String(fields.get('reason'))},'接待方式已更新。');}}><label>接待方式<select name="mode" defaultValue="HUMAN"><option value="HUMAN">人工接管</option><option value="PAUSED">暂停接待</option>{!realBrowser&&<option value="AI">恢复自动接待</option>}</select></label><label>切换原因<input name="reason" required maxLength={500}/></label><button className="button subtle" disabled={busy}>保存接待方式</button></form>
      <section className="reception-history" aria-label="回复建议"><strong>{data?.drafting.provider==='OPENAI_COMPATIBLE'?'AI 回复草稿':'规则回复建议'}</strong><p className="muted">根据当前来信生成建议，审核并采用后再准备回复。建议有效 20 分钟；新来信或接管后需重新生成。</p>{data?.drafting.configured===false&&<p className="alert warning">模型接口尚未配置或配置无效，请管理员配置后使用。</p>}<button type="button" className="button subtle" disabled={busy||draftPending||!data?.drafting.configured||!data.drafting.unanswered||conversation.handling_mode!=='HUMAN'||stoppedLead} onClick={()=>void perform('conversations/'+conversation.id+'/drafts',{},'建议已排队，完成后会显示在这里。')}>{draftPending?'正在生成建议…':data?.drafting.provider==='OPENAI_COMPATIBLE'?'生成 AI 草稿':'生成规则建议'}</button>{conversation.handling_mode!=='HUMAN'&&<p className="muted">请先在上方人工接管会话。</p>}{data?.jobs.filter(job=>job.draft_only).slice(0,3).map(job=><article key={job.id}><strong>{job.result?.model==='LOCAL_RULES'?'规则建议':job.result?.model==='OPENAI_COMPATIBLE'?'AI 草稿':'生成记录'} · {job.draft_usable?'待人工审核':job.result?.status==='DRAFT_READY'?'需要重新判断':job.result?.status??job.state}</strong><p>{job.result?.decision?.reply||job.result?.decision?.reason||job.error_code||'等待生成'}</p>{job.draft_usable&&<button type="button" className="button subtle" disabled={busy||!!replyBody.trim()||referralSelected} onClick={()=>{setReplyBody(job.result.decision.reply);setReferralSelected(job.result.decision.action==='REFER_WHATSAPP');setAdopted({job_id:job.id,conversation_id:conversation.id,control_version:conversation.control_version});setNotice('建议已填入下方回复框，请审核内容；尚未准备或发送任务。');}}>采用到空白回复框</button>}{job.draft_usable&&(replyBody.trim()||referralSelected)&&<small>回复框已有内容，请先审核或清空，避免覆盖你的编辑。</small>}</article>)}</section>
      {adopted&&<p className={draftInvalid?'alert warning':'muted'}>{draftInvalid?'采用的建议已失效，请清空后重新生成。':'已采用建议，发送内容仍需人工审核。'} <button type="button" className="button subtle" disabled={busy} onClick={()=>{setAdopted(null);setReplyBody('');setReferralSelected(false);}}>清空回复并取消采用</button></p>}
      <form className="business-form" aria-label="人工回复" onSubmit={event=>void reply(event)}>{realBrowser&&<><p className="muted business-wide">准备一条人工回复或 WhatsApp 邀请，之后在任务工作台审核本次发送。</p><label className="business-wide">客户同意记录<select name="contact_permission_id" required defaultValue=""><option value="">选择与最新来信对应的同意记录</option>{data?.manual_permissions.map(row=><option key={row.id} value={row.id}>{row.evidence_note} · 截至 {businessTime(row.expires_at)}</option>)}</select></label>{!data?.manual_permissions.length&&<p className="muted business-wide">尚无可选记录。请先在上方登记客户对本次联系的明确同意。</p>}</>}<label className="business-wide">回复内容<textarea name="body" value={replyBody} onChange={event=>setReplyBody(event.target.value)} maxLength={2000} rows={3} placeholder="输入回复；发送时将接管此会话"/></label><label className="business-wide"><input name="refer_whatsapp" type="checkbox" checked={referralSelected} onChange={event=>setReferralSelected(event.target.checked)} disabled={data?.destination?.state!=='ACTIVE'}/> 使用本账号的 WhatsApp 引流话术</label><p className="muted business-wide">{data?.destination?.state==='ACTIVE'?`目的地：${data.destination.name} · +${data.destination.phone}（${data.destination.account_id?'账号专用':'品牌默认'}）`:'没有可用的 WhatsApp 目的地，请先配置。'}</p><label>延迟发送（分钟，0 为立即）<input name="delay_minutes" type="number" min={0} max={1440} defaultValue={0}/></label>{!realBrowser&&<button className="button primary" disabled={busy||unsafe||draftInvalid||conversation.opted_out||['IGNORED','BLOCKED','HANDOFF_COMPLETE'].includes(conversation.lead_status)}>接管并发送回复</button>}{!conversation.is_synthetic&&role==='admin'&&<button name="pilot" className="button" disabled={busy||unsafe||draftInvalid||stoppedLead}>{realBrowser?'准备回复任务':'准备真实私信试验'}</button>}</form>
      {!realBrowser&&data?.jobs.some(row=>!row.draft_only&&row.state==='DEAD')&&<button className="button subtle" disabled={busy||unsafe} onClick={()=>void perform('conversations/'+conversation.id+'/retry-reception',{},'已为最新未回答私信重新安排接待。')}>重试最新自动接待</button>}
    </>}
    {!!data?.jobs.filter(job=>!job.draft_only).length&&<details className="reception-history"><summary>自动接待判断</summary>{data.jobs.filter(job=>!job.draft_only).map(job=><article key={job.id}><strong>{actionNames[job.state]??job.state} · {job.result?.model==='LOCAL_RULES'?'本地规则预演':job.result?.model==='OPENAI_COMPATIBLE'?'模型接口':`尝试 ${job.attempts} 次`}</strong><p>{job.result?.decision?.reason??job.result?.reason??job.error_code??'等待 Worker 处理'}</p>{job.result?.decision&&<small>{actionNames[job.result.decision.action]} · {job.result.decision.intent} · 置信度 {Math.round(job.result.decision.confidence*100)}%</small>}</article>)}</details>}
    {!!data?.replies.length&&<details className="reception-history" open><summary>回复发送进度</summary>{data.replies.map(row=><article key={row.id}><strong>{row.actor_kind==='AI'?'自动接待':'人工'} · {actionNames[row.state]??row.state}</strong><p>{row.body}</p><small>{businessTime(row.created_at)}{row.error_code?' · '+row.error_code:''}</small><Link href={'/runs?run='+row.run_id}>查看执行与核验 →</Link>{role==='admin'&&conversation.is_synthetic&&row.state==='UNKNOWN_OUTCOME'&&<button className="button subtle" disabled={busy} onClick={()=>void perform('runs/'+row.run_id+'/reconciliation',{},'原提交核验已完成，请查看最新结果。')}>核验原提交</button>}</article>)}</details>}
    {realBrowser&&data&&<details className="reception-history" aria-label="公开互动来源核对" open={data.public_interactions.length>0}><summary>同一主页身份的公开互动 · {data.public_interactions.length} 条</summary><p className="muted">仅展示本账号已核实并结束执行的公开回复，最多 20 条。身份相同便于核对历史；这次咨询是否由该评论带来，仍需人工确认。</p>{!data.public_interactions.length?<p className="muted">尚无匹配的已核实公开回复。收到私信本身不代表主动获客链已完成。</p>:data.public_interactions.map(row=><article key={row.action_id}><strong>原评论</strong><p>{row.source_body}</p><a href={row.source_url} target="_blank" rel="noreferrer">查看原评论</a><strong>已核实的公开回复</strong><p>{row.reply_body}</p><p className="muted">回复核实：{businessTime(row.verified_at)} · KFF 首次收到该会话来信：{businessTime(row.first_inbox_at)}</p><div className="button-row"><a href={row.reply_url} target="_blank" rel="noreferrer">查看公开回复</a><Link href={'/runs?run='+row.run_id}>查看执行记录</Link></div></article>)}</details>}
    {!!data?.referrals.length&&<div className="reception-history"><h3>WhatsApp 引流记录</h3><p className="muted">发送邀请与客户已联系分别记录。客户结果由销售核实后登记。</p>{data.referrals.map(row=><ReferralResult key={row.id+'/'+row.version} row={row} writable={role!=='viewer'} onSaved={async()=>{await Promise.all([load(),onSaved()]);}}/>)}</div>}
  </div>;
}
function ReferralResult({row,writable,onSaved}:{row:Reception['referrals'][number];writable:boolean;onSaved:()=>Promise<void>}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false);const request=useRef<{key:string;id:string}|null>(null);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');const fields=new FormData(event.currentTarget),payload={expected_version:row.version,result:fields.get('result'),reason:fields.get('reason')},key=JSON.stringify(payload);if(request.current?.key!==key)request.current={key,id:crypto.randomUUID()};try{await businessRequest('whatsapp-referrals/'+row.id+'/result',{...payload,request_id:request.current.id});await onSaved();}catch(failure){setError(failure instanceof Error?failure.message:'结果未保存');}finally{setBusy(false);}}
  return <article><strong>{actionNames[row.state]??row.state} · {row.actor_kind==='AI'?'自动':'人工'}引流</strong><p>{row.body}</p><small>{businessTime(row.sent_at)}</small>{writable&&row.state==='REFERRED'&&<form className="business-form" aria-label="记录 WhatsApp 客户结果" onSubmit={event=>void submit(event)}><label>客户结果<select name="result"><option value="CONFIRMED">已核实客户联系 WhatsApp</option><option value="DECLINED">客户未添加或拒绝</option></select></label><label>核实依据<input name="reason" required maxLength={500}/></label><button className="button subtle" disabled={busy}>保存引流结果</button>{error&&<p role="alert">{error}</p>}</form>}</article>;
}
