'use client';
import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import type {Workspace} from '@kff/core/service';
import type {ScheduleRule} from '../../../packages/contracts/src/schedule';
import type {SchedulePreview,ScheduleRecord,ScheduleVersion,scheduleDetail,scheduleList} from '@kff/core/schedules';
import type {ScheduleSlot} from '@kff/core/schedule-rules';
import { Field } from './field';

type Detail=Awaited<ReturnType<typeof scheduleDetail>>;
const states={ACTIVE:'时点准备中',PAUSED:'已暂停',STOPPED:'已终止',COMPLETED:'全部时点已处理'};
const reasons:Record<string,string>={NORMAL:'正常时刻',DST_EARLIER:'重复时刻 · 较早一次',DST_LATER:'重复时刻 · 较晚一次',DST_GAP_SHIFTED:'缺失时刻 · 按变化量后移',DST_GAP_SKIPPED:'缺失时刻 · 跳过',DST_REPEAT_SKIPPED:'重复时刻 · 跳过',ON_TIME:'容限内准备',DEFERRED_LATEST:'仅延后最近一次',CATCH_UP:'限量补准备',MISSED_SKIP:'错过后跳过',MISSED_COALESCED:'较早时点已合并跳过',CATCH_UP_LIMIT:'超过本次补准备上限',TOO_LATE:'已超过最迟准备期限',RULE_VERSION_SUPERSEDED:'规则版本已替换',SCHEDULE_STOPPED:'未来计划已终止'};
async function api<T>(path:string,body?:unknown):Promise<T>{const response=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error?.message??'计划操作未完成');return value;}
const localTime=(value:string|null,zone:string)=>value?new Date(value).toLocaleString('zh-CN',{timeZone:zone,hour12:false}):'—';
function Calendar({slots}:{slots:ScheduleSlot[]}){const [page,setPage]=useState(0);return <div className="schedule-calendar"><div className="table-scroll"><table aria-label="计划 UTC 日历"><thead><tr><th>原定当地时间</th><th>时区规则处理</th><th>确定的 UTC 时点</th></tr></thead><tbody>{slots.slice(page*25,page*25+25).map(slot=><tr key={slot.key}><td>{slot.local_time.replace('T',' ')}{slot.resolved_local_time&&slot.resolved_local_time!==slot.local_time&&<small>后移至 {slot.resolved_local_time.replace('T',' ')}</small>}</td><td>{reasons[slot.decision]}<small>{slot.offset??'无实际时点'}</small></td><td className="mono">{slot.scheduled_at??'跳过，不生成准备请求'}</td></tr>)}</tbody></table></div><div className="panel-footer"><span>共 {slots.length} 个规则时点 · 第 {page+1} 页</span><div className="contact-actions"><button className="text-button" disabled={!page} onClick={()=>setPage(value=>value-1)}>上一页日历</button><button className="text-button" disabled={(page+1)*25>=slots.length} onClick={()=>setPage(value=>value+1)}>下一页日历</button></div></div></div>;}
function RuleForm({initial,title,busy,onPreview,onChanged}:{initial?:ScheduleRule;title?:string;busy:boolean;onPreview:(rule:ScheduleRule,title:string,evaluate_at?:string)=>Promise<void>;onChanged:()=>void}){
  const [kind,setKind]=useState<ScheduleRule['kind']>(initial?.kind??'ONCE');const tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const get=(key:string)=>String(form.get(key)??'');const rule:ScheduleRule={timezone:get('timezone'),kind,start_date:get('start_date'),end_date:kind==='ONCE'?get('start_date'):get('end_date'),time:get('time'),weekdays:kind==='WEEKLY'?form.getAll('weekdays').map(Number):[],repeated_time:get('repeated_time') as ScheduleRule['repeated_time'],missing_time:get('missing_time') as ScheduleRule['missing_time'],missed_policy:get('missed_policy') as ScheduleRule['missed_policy'],catch_up_limit:Number(get('catch_up_limit')),spacing_seconds:Number(get('spacing_seconds')),late_tolerance_seconds:Number(get('late_tolerance_seconds')),maximum_lateness_seconds:Number(get('maximum_lateness_seconds'))};await onPreview(rule,get('title'),get('evaluate_at')?get('evaluate_at')+(get('evaluate_at').length===16?':00Z':'Z'):undefined);}
  return <form aria-label="计划规则表单" onSubmit={event=>void submit(event)} onChange={onChanged}><fieldset disabled={busy}><Field label="计划名称"><input name="title" maxLength={120} required defaultValue={title??''}/></Field><div className="form-grid"><Field label="IANA 时区"><input name="timezone" maxLength={80} required defaultValue={initial?.timezone??'Asia/Shanghai'}/></Field><Field label="重复规则"><select value={kind} onChange={event=>setKind(event.target.value as ScheduleRule['kind'])}><option value="ONCE">一次</option><option value="DAILY">每日</option><option value="WEEKLY">每周选定星期</option></select></Field><Field label="开始日期"><input name="start_date" type="date" min="2000-01-01" max="2099-12-31" required defaultValue={initial?.start_date??tomorrow}/></Field>{kind!=='ONCE'&&<Field label="结束日期"><input name="end_date" type="date" min="2000-01-01" max="2099-12-31" required defaultValue={initial?.end_date??tomorrow}/></Field>}<Field label="当地时刻"><input name="time" type="time" required defaultValue={initial?.time??'09:00'}/></Field></div>
    {kind==='WEEKLY'&&<fieldset className="collection-field-choice"><legend>选定星期</legend>{['一','二','三','四','五','六','日'].map((label,index)=><label key={label}><input type="checkbox" name="weekdays" value={index+1} defaultChecked={initial?.weekdays.includes(index+1)}/>周{label}</label>)}</fieldset>}
    <div className="form-grid"><Field label="夏令时重复时刻"><select name="repeated_time" defaultValue={initial?.repeated_time??'EARLIER'}><option value="EARLIER">仅较早一次</option><option value="LATER">仅较晚一次</option><option value="BOTH">两次分别准备</option><option value="SKIP">跳过重复时刻</option></select></Field><Field label="夏令时缺失时刻"><select name="missing_time" defaultValue={initial?.missing_time??'SKIP'}><option value="SKIP">跳过缺失时刻</option><option value="SHIFT_FORWARD">按时区变化量向后移动</option></select></Field><Field label="错过时点策略"><select name="missed_policy" defaultValue={initial?.missed_policy??'SKIP'}><option value="SKIP">跳过</option><option value="DEFER_LATEST">只延后最近一次，其余跳过</option><option value="CATCH_UP">从较早时点开始，限量补准备</option></select></Field><Field label="每次积压最多补准备数"><input name="catch_up_limit" type="number" min={1} max={10} required defaultValue={initial?.catch_up_limit??2}/></Field><Field label="准备时点间隔（秒）"><input name="spacing_seconds" type="number" min={60} max={86400} required defaultValue={initial?.spacing_seconds??60}/></Field><Field label="正常延迟容限（秒）"><input name="late_tolerance_seconds" type="number" min={0} max={3600} required defaultValue={initial?.late_tolerance_seconds??30}/></Field><Field label="最迟准备期限（秒）"><input name="maximum_lateness_seconds" type="number" min={60} max={604800} required defaultValue={initial?.maximum_lateness_seconds??3600}/></Field><Field label="模拟恢复时间（UTC，可选）"><input name="evaluate_at" type="datetime-local"/></Field></div><p className="field-hint">日期范围最多 366 天。超过补准备数或最迟期限的旧时点明确跳过；模拟恢复时间只用于预览。</p><button className="button primary" disabled={busy}>预览规则与 UTC 日历</button></fieldset></form>;
}
export function ScheduleWorkbench({data}:{data:Workspace}){
  const [records,setRecords]=useState<Awaited<ReturnType<typeof scheduleList>>>([]);const [selected,setSelected]=useState('');const [detail,setDetail]=useState<Detail|null>(null);const [revision,setRevision]=useState(0);const [editing,setEditing]=useState<{schedule:ScheduleRecord;version:ScheduleVersion}|null>(null);const [preview,setPreview]=useState<SchedulePreview|null>(null);const [draftTitle,setDraftTitle]=useState('');const [viewedVersion,setViewedVersion]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
  const requests=useRef(new Map<string,string>());const request=(value:unknown)=>{const key=JSON.stringify(value);if(!requests.current.has(key))requests.current.set(key,crypto.randomUUID());return requests.current.get(key)!;};
  const load=useCallback(async()=>{const rows=await api<Awaited<ReturnType<typeof scheduleList>>>('schedules');setRecords(rows);setSelected(value=>rows.some(row=>row.id===value)?value:rows[0]?.id??'');},[]);
  useEffect(()=>{let active=true;const update=()=>{if(active)void load().catch(failure=>{if(active)setError(failure.message);});};update();const timer=setInterval(update,3000);return()=>{active=false;clearInterval(timer);};},[load]);
  useEffect(()=>{if(!selected)return;let active=true;let loading=false;const update=async()=>{if(loading)return;loading=true;try{const value=await api<Detail>('schedules/'+selected);if(active)setDetail(value);}catch(failure){if(active)setError(failure instanceof Error?failure.message:'计划无法读取');}finally{loading=false;}};void update();const timer=setInterval(()=>void update(),2500);return()=>{active=false;clearInterval(timer);};},[selected,revision]);
  async function act(operation:()=>Promise<void>,message:string){setBusy(true);setError('');setNotice('');try{await operation();await load();setRevision(value=>value+1);setNotice(message);}catch(failure){setError(failure instanceof Error?failure.message:'计划操作未完成');}finally{setBusy(false);}}
  const current=detail?.schedule.id===selected?detail:null;const version=current?.versions.find(row=>row.id===current.schedule.current_version_id);const calendar=current?.versions.find(row=>row.id===viewedVersion)??version;const canWrite=data.scope.role!=='viewer';
  return <div className="schedule-workbench">{error&&<p role="alert" className="alert error">{error}</p>}{notice&&<p role="status" className="alert warning">{notice}</p>}<p className="alert warning">当前准备计划时点；绑定具体任务后仍需核对审核、资格和预算。准备记录不会直接执行平台动作。</p>
    {canWrite&&<section className="panel schedule-form"><details key={editing?.schedule.id??'new'} open={editing?true:undefined}><summary>{editing?'调整已暂停计划':'创建计划规则'}</summary>{editing&&<button className="text-button" onClick={()=>{setEditing(null);setPreview(null);}}>取消调整</button>}<RuleForm key={editing?.schedule.current_version_id??'new'} initial={editing?.version.definition.rule} title={editing?.schedule.title} busy={busy} onChanged={()=>setPreview(null)} onPreview={async(rule,title,evaluate_at)=>{await act(async()=>{setPreview(await api<SchedulePreview>('schedule-previews',{rule,...(evaluate_at?{evaluate_at}:{}),request_id:request({rule,evaluate_at})}));setDraftTitle(title);},'规则预览已保存，请核对日历及错过策略。');}}/></details></section>}
    {preview&&<section className="panel schedule-preview" aria-label="计划规则预览"><h3>{draftTitle} · 预览</h3><p>时区 {preview.definition.rule.timezone} · {preview.definition.slots.length} 个规则时点。保存后初始为暂停。</p><p>以 UTC {new Date(preview.evaluated_at).toISOString()} 模拟恢复：可准备 {preview.simulation.decisions.filter(row=>row.state==='READY_FOR_TASK').length} 个，跳过 {preview.simulation.decisions.filter(row=>row.state==='SKIPPED').length} 个。</p><Calendar key={'calendar:'+preview.id} slots={preview.definition.slots}/><details><summary>查看模拟错过处理明细</summary>{preview.simulation.decisions.map(row=><p key={row.slot.key}>{row.slot.local_time} · {reasons[row.reason]}{row.available_at?' · 最早 UTC '+row.available_at:''}</p>)}</details><form key={'confirm:'+preview.id} onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void act(async()=>{const value={preview_id:preview.id,preview_hash:preview.definition_hash,title:draftTitle,...(editing?{expected_version:editing.schedule.version,reason:form.get('reason')}: {})};const saved=await api<ScheduleRecord>(editing?'schedules/'+editing.schedule.id+'/versions':'schedules',{...value,request_id:request({id:editing?.schedule.id,...value})});setSelected(saved.id);setEditing(null);setPreview(null);},'计划版本已保存，当前处于暂停状态。');}}>{editing&&<Field label="调整规则原因"><input name="reason" required minLength={5} maxLength={300}/></Field>}<label className="import-confirm"><input type="checkbox" required disabled={busy}/>已核对当地时间、UTC 时点及错过策略</label><button className="button primary" disabled={busy}>确认并保存暂停计划</button></form></section>}
    <section className="panel"><div className="panel-head"><h2>计划记录</h2><button className="text-button" disabled={busy} onClick={()=>void act(load,'计划列表已刷新。')}>刷新计划</button></div><div className="table-scroll"><table aria-label="计划列表"><thead><tr><th>计划</th><th>状态</th><th>下一规则时点</th></tr></thead><tbody>{records.map(row=><tr key={row.id}><td><button className="text-button strong" onClick={()=>{setSelected(row.id);setViewedVersion('');}}>{row.title}</button><small>{row.timezone} · 规则版本 {row.version_number}</small></td><td>{states[row.state]}</td><td>{row.state==='STOPPED'?'已终止':localTime(row.next_due_at,row.timezone)}</td></tr>)}</tbody></table>{!records.length&&<p className="collection-empty">还没有保存的计划。</p>}</div></section>
    {current&&version&&<section className="panel schedule-detail" aria-label="计划详情"><div className="panel-head"><h2>{current.schedule.title}</h2><strong>{states[current.schedule.state]}</strong></div><p className="schedule-summary">待建任务 {current.counts.ready} 个，跳过 {current.counts.skipped} 个，已取消 {current.counts.canceled} 个。统计当前计划全部规则版本的已处理时点。</p><p className="field-hint">当前时区 {version.definition.rule.timezone}；已处理 {current.schedule.next_slot_index} / {version.definition.slots.length} 个规则时点。下一规则时点 {current.schedule.state==='STOPPED'?'已终止':localTime(current.schedule.next_due_at,version.definition.rule.timezone)}。</p>{current.schedule.pause_reason&&<p className="alert error">时区数据或规则校验已变化，需要重新预览和保存版本。</p>}
      {canWrite&&current.schedule.state!=='STOPPED'&&<form key={current.schedule.version} aria-label="控制计划" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);const action=(event.nativeEvent as SubmitEvent).submitter?.getAttribute('value');void act(async()=>{const input={expected_version:current.schedule.version,action,reason:form.get('reason')};await api('schedules/'+current.schedule.id+'/controls',{...input,request_id:request({id:current.schedule.id,...input})});},action==='STOP'?'未来计划已终止，未绑定任务的准备记录已取消。':action==='PAUSE'?'已暂停后续时点准备。':'已开始按保存规则准备时点。');}}><Field label="计划控制原因"><input name="reason" required minLength={5} maxLength={300} disabled={busy}/></Field><div className="contact-actions">{current.schedule.state==='PAUSED'&&<button className="button primary" value="RESUME" disabled={busy}>开始或恢复时点准备</button>}{current.schedule.state==='ACTIVE'&&<button className="button subtle" value="PAUSE" disabled={busy}>暂停时点准备</button>}<button className="button danger" value="STOP" disabled={busy}>终止未来计划</button>{current.schedule.state==='PAUSED'&&<button type="button" className="text-button" disabled={busy} onClick={()=>{setEditing({schedule:current.schedule,version});setPreview(null);}}>调整此计划规则</button>}</div></form>}
      <div className="schedule-history"><Field label="查看规则版本"><select value={calendar?.id??''} onChange={event=>setViewedVersion(event.target.value)}>{current.versions.map(row=><option key={row.id} value={row.id}>版本 {row.version_number} · {row.title}</option>)}</select></Field>{calendar&&<><p className="field-hint">{calendar.definition.rule.timezone} · {calendar.definition.timezone_data}</p><details><summary>查看本版本 UTC 日历</summary><Calendar key={calendar.id} slots={calendar.definition.slots}/><code>{calendar.definition_hash}</code></details></>}</div>
      <div className="table-scroll"><table aria-label="已处理计划时点"><thead><tr><th>原定当地时间</th><th>处理结果</th><th>最早可用时间</th></tr></thead><tbody>{current.occurrences.map(row=><tr key={row.id}><td>{row.slot.local_time.replace('T',' ')}<small>UTC {row.scheduled_at?new Date(row.scheduled_at).toISOString():'无实际时点'}</small></td><td>{row.state==='CANCELED'?'已取消':row.state==='SKIPPED'?'已跳过':'待建任务'}<small>{reasons[row.cancellation_reason??row.reason]}</small></td><td>{localTime(row.available_at,version.definition.rule.timezone)}</td></tr>)}</tbody></table>{!current.occurrences.length&&<p className="collection-empty">尚无已处理时点。</p>}</div><div className="panel-footer">最近 1000 个已处理时点 · 显示时区 {version.definition.rule.timezone} · 未据此创建平台任务</div></section>}
  </div>;
}
