'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import type {paymentWorkspace} from '@kff/core/payments';
import type {OwnedOrder} from '../../../packages/contracts/src/order';
import {displayMinor} from '../../../packages/contracts/src/order';
import type {CheckoutState} from '../../../packages/contracts/src/payment';
import {businessRequest,businessTime} from './business-ui';
import {useRequestKey} from './use-request-key';

type Payments=Awaited<ReturnType<typeof paymentWorkspace>>;
const labels:Record<CheckoutState,string>={READY:'等待创建',CREATING:'正在确认支付链接',OPEN:'等待客户付款',PENDING:'付款结果待核对',PAID:'已核实付款',EXPIRED:'支付会话已过期',FAILED:'支付未完成',NEEDS_HUMAN:'需要人工核对'};
export function StripeSettings({admin}:{admin:boolean}){
  const [data,setData]=useState<Payments|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const key=useRequestKey();
  const refresh=useCallback(async()=>setData(await businessRequest<Payments>('payments')),[]);useEffect(()=>{void refresh().catch(failure=>setError(failure.message));},[refresh]);
  async function register(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget),payload={name:fields.get('name'),stripe_account_id:fields.get('account'),mode:fields.get('mode'),credential_ref:fields.get('reference')};setBusy(true);setError('');try{await businessRequest('stripe-connections',{request_id:key.forPayload(payload),...payload});key.confirmed();await refresh();}catch(failure){setError(failure instanceof Error?failure.message:'Stripe 连接未保存');}finally{setBusy(false);}}
  return <details className="business-box stripe-settings"><summary>Stripe 支付连接 <span>{data?.connections.length??0} 个</span></summary>{error&&<p role="alert" className="alert warning">{error}</p>}{data?.connections.length===0&&<p>第一阶段使用 Stripe。配置测试连接后，可以为订单生成支付链接。</p>}{data?.connections.map(connection=><div className="stripe-connection" key={connection.id}><strong>{connection.name}</strong><p>{connection.mode==='TEST'?'测试模式':'真实收款'}{connection.is_synthetic?' · 本地合成验证':''} · {connection.outbound_enabled?'允许创建支付':'已暂停新支付'}</p><small>{connection.stripe_account_id}</small>{admin&&<ConnectionControl connection={connection} onSaved={refresh}/>}</div>)}
    {admin&&<form className="business-form" aria-label="Stripe 连接配置" onSubmit={event=>void register(event)}><h3>登记 Stripe 连接</h3><p className="business-wide muted">先在服务器私密配置中保存密钥，这里只填写引用名称。连接会核对实际商户身份。</p><label>连接名称<input name="name" required maxLength={80}/></label><label>Stripe 商户账号<input name="account" required placeholder="acct_…" pattern="acct_[A-Za-z0-9]+"/></label><label>支付模式<select name="mode" aria-label="支付模式" defaultValue="TEST"><option value="TEST">测试模式</option><option value="LIVE">真实收款（需部署启用）</option></select></label><label>服务器凭据引用<input name="reference" required placeholder="KFF_STRIPE_MAIN" pattern="KFF_STRIPE_[A-Z0-9_]{1,40}"/></label><button className="button primary" disabled={busy}>核对并保存连接</button></form>}
  </details>;
}
function ConnectionControl({connection,onSaved}:{connection:Payments['connections'][number];onSaved:()=>Promise<void>}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false);const key=useRequestKey();async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget),payload={expected_version:connection.version,outbound_enabled:!connection.outbound_enabled,reason:fields.get('reason')};setBusy(true);setError('');try{await businessRequest('stripe-connections/'+connection.id+'/controls',{request_id:key.forPayload(payload),...payload});key.confirmed();await onSaved();}catch(failure){setError(failure instanceof Error?failure.message:'状态未更新');}finally{setBusy(false);}}
  return <form aria-label={'管理支付连接 '+connection.name} className="product-control" onSubmit={event=>void save(event)}><label>调整依据<input name="reason" required maxLength={300}/></label><button className="button subtle" disabled={busy}>{connection.outbound_enabled?'暂停新支付':'恢复新支付'}</button>{error&&<p role="alert">{error}</p>}</form>;
}
export function StripeOrderPayment({order,writable,onSaved}:{order:OwnedOrder;writable:boolean;onSaved:()=>Promise<void>}){
  const [data,setData]=useState<Payments|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const key=useRequestKey(),checkKey=useRequestKey();
  const refresh=useCallback(async()=>setData(await businessRequest<Payments>('payments?order='+order.id)),[order.id]);useEffect(()=>{void refresh().catch(failure=>setError(failure.message));},[refresh]);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget),payload={connection_id:fields.get('connection'),expected_version:order.version,snapshot_hash:order.snapshot_hash,confirmation:'CREATE_STRIPE_CHECKOUT'};setBusy(true);setError('');try{await businessRequest('orders/'+order.id+'/stripe-checkouts',{request_id:key.forPayload(payload),...payload});key.confirmed();await refresh();await onSaved();}catch(failure){setError(failure instanceof Error?failure.message:'支付请求未保存');}finally{setBusy(false);}}
  async function recheck(id:string){const payload={reason:'工作人员从订单详情请求核对原 Stripe 对象'};setBusy(true);setError('');try{await businessRequest('payment-checkouts/'+id+'/recheck',{request_id:checkKey.forPayload({id,...payload}),...payload});checkKey.confirmed();await refresh();}catch(failure){setError(failure instanceof Error?failure.message:'核对请求未保存');}finally{setBusy(false);}}
  const pending=data?.checkouts.some(checkout=>!['EXPIRED','FAILED'].includes(checkout.state));
  return <section className="stripe-order-payment" aria-label="Stripe 订单支付"><div className="business-box-head"><h3>Stripe 支付</h3><button className="text-button" disabled={busy} onClick={()=>void refresh().then(onSaved).catch(failure=>setError(failure.message))}>刷新支付状态</button></div>{error&&<p role="alert" className="alert warning">{error}</p>}
    {!data?.connections.length&&<p className="muted">Stripe 已选定，等待配置测试连接。</p>}
    {data?.verified.map(payment=><div key={payment.id} className="stripe-receipt"><strong>{payment.mode==='TEST'?'测试支付已核实':'付款已核实'}</strong><p>{payment.currency} {displayMinor(payment.amount_minor,payment.minor_unit_exponent)} · {businessTime(payment.verified_at)}</p>{payment.mode==='TEST'&&<p>测试记录，不计入真实收入。</p>}</div>)}
    {data?.checkouts.map(checkout=><article className="stripe-checkout" key={checkout.id}><strong>{labels[checkout.state]}</strong><p>{data.connections.find(connection=>connection.id===checkout.connection_id)?.name} · {checkout.id.slice(0,8)}</p>{checkout.error_code&&<p className="alert warning">核对未完成：{checkout.error_code}。保留此请求处理，勿重复建单。</p>}{checkout.checkout_url&&checkout.state==='OPEN'&&<a className="button primary" href={checkout.checkout_url} target="_blank" rel="noreferrer">打开 Stripe 收银台</a>}{writable&&checkout.provider_session_id&&!['PAID','EXPIRED','FAILED'].includes(checkout.state)&&<button className="button subtle" disabled={busy} onClick={()=>void recheck(checkout.id)}>核对原支付</button>}</article>)}
    {writable&&order.state==='OPEN'&&order.payment_state==='UNVERIFIED'&&!pending&&!!data?.connections.filter(connection=>connection.outbound_enabled).length&&<form aria-label="创建 Stripe 支付" onSubmit={event=>void create(event)}><label>收款连接<select aria-label="收款连接" name="connection" required><option value="">选择 Stripe 连接</option>{data.connections.filter(connection=>connection.outbound_enabled).map(connection=><option key={connection.id} value={connection.id}>{connection.name} · {connection.mode==='TEST'?'测试模式':'真实收款'}</option>)}</select></label><p>本订单：{order.snapshot.currency} {displayMinor(order.snapshot.total_minor,order.snapshot.minor_unit_exponent)}</p><label className="order-checkbox"><input type="checkbox" required/>已核对收款连接、支付模式和订单金额</label><button className="button primary" disabled={busy}>生成 Stripe 支付链接</button></form>}
    {!!data?.events.length&&<details><summary>支付回调记录</summary>{data.events.map(event=><p key={event.id}>{event.event_type} · {event.state}{event.error_code?' · '+event.error_code:''}</p>)}</details>}
  </section>;
}
