'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import type {financialWorkspace} from '@kff/core/refunds';
import {displayMinor} from '../../../packages/contracts/src/order';
import {parseRefundAmount,type RefundState} from '../../../packages/contracts/src/refund';
import {businessRequest,businessTime} from './business-ui';
import {useRequestKey} from './use-request-key';
type Financials=Awaited<ReturnType<typeof financialWorkspace>>;
const labels:Record<RefundState,string>={READY:'等待提交',SUBMITTING:'原退款结果待核对',PENDING:'退款处理中',REQUIRES_ACTION:'退款需要补充操作',SUCCEEDED:'退款已核实',FAILED:'退款失败',CANCELED:'已取消',NEEDS_HUMAN:'需要人工核对'};
function signed(value:string,exponent:number){return (value.startsWith('-')?'-':'')+displayMinor(value.replace(/^-/,'').padStart(1,'0'),exponent);}
export function StripeRefunds({paymentId,admin,writable}:{paymentId:string;admin:boolean;writable:boolean}){
 const [data,setData]=useState<Financials|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const refundKey=useRequestKey(),syncKey=useRequestKey();
 const refresh=useCallback(async()=>setData(await businessRequest<Financials>('payments/'+paymentId+'/financials')),[paymentId]);useEffect(()=>{void refresh().catch(failure=>setError(failure.message));},[refresh]);
 async function recheck(){const payload={reason:'工作人员从订单请求核对原付款的退款与争议'};setBusy(true);setError('');try{await businessRequest('payments/'+paymentId+'/financial-recheck',{request_id:syncKey.forPayload(payload),...payload});syncKey.confirmed();await refresh();}catch(failure){setError(failure instanceof Error?failure.message:'核对请求未保存');}finally{setBusy(false);}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!data)return;const form=event.currentTarget,fields=new FormData(form);setBusy(true);setError('');try{const payload={expected_version:data.ledger.version,amount_minor:parseRefundAmount(String(fields.get('amount')),data.payment.minor_unit_exponent),confirmed_available_minor:data.available_minor,reason:fields.get('reason'),provider_reason:fields.get('provider_reason')||null,confirmation:'REFUND_CONFIRMED_AMOUNT'};await businessRequest('payments/'+paymentId+'/refunds',{request_id:refundKey.forPayload(payload),...payload});refundKey.confirmed();form.reset();await refresh();}catch(failure){setError(failure instanceof Error?failure.message:'退款申请未保存');}finally{setBusy(false);}}
 const format=(value:string)=>data?data.payment.currency+' '+signed(value,data.payment.minor_unit_exponent):'';
 return <section className="stripe-refunds" aria-label="退款与调整"><div className="business-box-head"><h3>退款与调整</h3><button className="text-button" disabled={busy} onClick={()=>void refresh().catch(failure=>setError(failure.message))}>刷新退款记录</button></div>{error&&<p role="alert" className="alert warning">{error}</p>}{!data&&!error&&<p>正在读取退款记录…</p>}{data&&<>
  {data.payment.mode==='TEST'&&<p className="refund-test-note">测试付款的退款与调整，不计真实收退款。</p>}
  <dl className="refund-summary"><div><dt>已核实退款净额</dt><dd>{format(data.refunded_minor)}</dd></div><div><dt>当前可退额度</dt><dd>{data.ledger.synced_at?format(data.available_minor):'等待核对'}</dd></div><div><dt>本地申请预占</dt><dd>{format(data.reserved_minor)}</dd></div><div><dt>退款后收款余额</dt><dd>{format(data.net_after_refunds_minor)}</dd></div></dl>
  <p className="muted">{data.ledger.synced_at?'最近核对：'+businessTime(data.ledger.synced_at):'先核对 Stripe 原付款、退款和争议，再确定可退额度。'}{data.ledger.refund_blocked?' · 当前退款资格需要处理':''}</p>
  {data.ledger.error_code&&<p role="status" className="alert warning">财务核对尚未完成：{data.ledger.error_code}。保留原申请核对。</p>}{writable&&<button className="button subtle" disabled={busy} onClick={()=>void recheck()}>核对原退款与争议</button>}
  {!data.new_refunds_enabled&&<p className="muted">新退款申请已暂停，原退款继续核对。</p>}{data.ledger.synced_at&&!data.fresh&&<p className="muted">可退额度需要重新核对后再申请退款。</p>}{admin&&data.new_refunds_enabled&&data.fresh&&!data.ledger.error_code&&!data.ledger.refund_blocked&&BigInt(data.available_minor)>0n&&<form className="refund-form" aria-label="申请退款" onSubmit={event=>void submit(event)}><h4>申请退款</h4><label>{data.payment.currency} 退款金额<input name="amount" inputMode="decimal" required placeholder={signed(data.available_minor,data.payment.minor_unit_exponent)}/></label><label>处理依据<textarea name="reason" required maxLength={500} rows={2}/></label><label>Stripe 退款原因<select name="provider_reason" defaultValue="requested_by_customer"><option value="requested_by_customer">客户要求</option><option value="duplicate">重复付款</option><option value="">其他已获准原因</option></select></label><label className="order-checkbox"><input type="checkbox" required/>已核对原付款、{data.payment.mode==='TEST'?'测试模式':'真实收款模式'}、退款金额和处理依据</label><button className="button primary" disabled={busy}>确认退款申请</button></form>}
  <div className="refund-records">{data.requests.map(request=><article key={request.id}><strong>{labels[request.state]} · {format(request.amount_minor)}</strong><p>{request.reason}</p><small>{request.id.slice(0,8)} · {businessTime(request.created_at)}</small>{request.error_code&&<p className="muted">{request.error_code}</p>}{admin&&!request.submitted_at&&!request.provider_refund_id&&['READY','NEEDS_HUMAN'].includes(request.state)&&<FinancialAction endpoint={'refunds/'+request.id+'/cancel'} label="撤销未提交申请" version={data.ledger.version} onSaved={refresh}/>}</article>)}</div>
  {data.refunds.length>0&&<details className="refund-history"><summary>Stripe 退款对象与状态（{data.refunds.length}）</summary>{data.refunds.map(refund=><p key={refund.id}><strong>{labels[refund.provider_status.toUpperCase() as RefundState]??'状态待核对'}</strong> · {format(refund.amount_minor)}<small>{refund.provider_refund_id}{refund.request_id?' · KFF 申请':' · Stripe 后台或其他入口'}{refund.failure_reason?' · '+refund.failure_reason:''}</small></p>)}</details>}
  {data.disputes.length>0&&<details className="refund-history" open><summary>付款争议（{data.disputes.length}）</summary>{data.disputes.map(dispute=><article key={dispute.id}><strong>{dispute.provider_dispute_id} · {dispute.provider_status}</strong><p>{dispute.amount_minor} {dispute.currency} 最小单位 · {dispute.reason}</p><small>{dispute.is_charge_refundable?'提供方允许退款':'提供方暂不允许退款'} · {businessTime(dispute.observed_at)}</small></article>)}<p className="muted">争议独立记录，处理结果和实际余额变动分别核对。</p></details>}
  {data.dispute_balances.length>0&&<details className="refund-history"><summary>争议余额变动</summary>{data.dispute_balances.map(entry=><p key={entry.provider_transaction_id}>{entry.provider_transaction_id}<small>{entry.currency} · 变动 {entry.amount_minor} · 费用 {entry.fee_minor} · 净额 {entry.net_minor}（该币种最小单位）</small></p>)}</details>}
  <details className="refund-history"><summary>人工账目调整（{data.adjustments.length}）</summary><p>当前调整净额：{format(data.manual_adjustments_minor)}</p><p>含人工调整的账目金额：{format(data.net_with_manual_adjustments_minor)}</p><p className="muted">用于记录有依据的账目调整；不会向 Stripe 发起转账或改变交付状态。</p>{admin&&<AdjustmentForm data={data} onSaved={refresh}/>}<div className="refund-records">{data.adjustments.map(adjustment=><article key={adjustment.id}><strong>{format(adjustment.amount_minor)} · {adjustment.reverses_id?'冲销记录':'人工调整'}</strong><p>{adjustment.reason}</p><small>依据：{adjustment.evidence_ref} · {businessTime(adjustment.created_at)}</small>{adjustment.reversed&&<p>已冲销，原记录保留。</p>}{admin&&!adjustment.reverses_id&&!adjustment.reversed&&<FinancialAction endpoint={'adjustments/'+adjustment.id+'/reverse'} label="冲销此调整" version={data.ledger.version} reverse onSaved={refresh}/>}</article>)}</div></details>
  {(data.events.length>0||data.postings.length>0)&&<details className="refund-history"><summary>回调与资金变动历史</summary>{data.events.map(event=><p key={event.id}>{event.event_type} · {event.state}<small>{event.provider_event_id}{event.error_code?' · '+event.error_code:''}</small></p>)}{data.postings.map(posting=><p key={posting.id}>{posting.kind==='REFUND'?'退款记账':'退款后续调整'} · {format(posting.amount_minor)}<small>{businessTime(posting.created_at)} · 证据 {posting.observation_id}</small></p>)}</details>}
 </>}</section>;
}
function FinancialAction({endpoint,label,version,reverse,onSaved}:{endpoint:string;label:string;version:number;reverse?:boolean;onSaved:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const key=useRequestKey();async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget),payload={expected_version:version,reason:fields.get('reason'),...(reverse?{evidence_ref:fields.get('evidence_ref'),confirmation:'REVERSE_THIS_ADJUSTMENT'}:{})};setBusy(true);setError('');try{await businessRequest(endpoint,{request_id:key.forPayload(payload),...payload});key.confirmed();await onSaved();}catch(failure){setError(failure instanceof Error?failure.message:'处理未保存');}finally{setBusy(false);}}
 return <form className="refund-form" aria-label={label} onSubmit={event=>void submit(event)}><label>处理原因<input name="reason" required maxLength={500}/></label>{reverse&&<label>冲销依据标识<input name="evidence_ref" required maxLength={300}/></label>}<button className="button subtle" disabled={busy}>{label}</button>{error&&<p role="alert">{error}</p>}</form>;
}
function AdjustmentForm({data,onSaved}:{data:Financials;onSaved:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');const key=useRequestKey();async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,fields=new FormData(form);setBusy(true);setError('');try{const payload={expected_version:data.ledger.version,amount_minor:parseRefundAmount(String(fields.get('amount')),data.payment.minor_unit_exponent),direction:fields.get('direction'),currency:data.payment.currency,reason:fields.get('reason'),evidence_ref:fields.get('evidence_ref'),dispute_id:fields.get('dispute')||null,confirmation:'RECORD_ACCOUNTING_ADJUSTMENT'};await businessRequest('payments/'+data.payment.id+'/adjustments',{request_id:key.forPayload(payload),...payload});key.confirmed();form.reset();await onSaved();}catch(failure){setError(failure instanceof Error?failure.message:'调整未保存');}finally{setBusy(false);}}
 return <form className="refund-form" aria-label="记录账目调整" onSubmit={event=>void submit(event)}><label>调整方向<select name="direction" defaultValue="DEBIT"><option value="DEBIT">扣减账目金额</option><option value="CREDIT">增加账目金额</option></select></label><label>{data.payment.currency} 调整金额<input name="amount" required inputMode="decimal"/></label><label>调整原因<textarea name="reason" required maxLength={500} rows={2}/></label><label>唯一依据标识<input name="evidence_ref" required maxLength={300}/></label><label>关联争议<select name="dispute" defaultValue=""><option value="">不关联争议</option>{data.disputes.map(dispute=><option key={dispute.id} value={dispute.id}>{dispute.provider_dispute_id}</option>)}</select></label><label className="order-checkbox"><input type="checkbox" required/>确认金额、方向和依据，记录此账目调整</label><button className="button primary" disabled={busy}>保存账目调整</button>{error&&<p role="alert">{error}</p>}</form>;
}
