'use client';
import {useState,type FormEvent} from 'react';
import type {Workspace} from '@kff/core/service';
import type {WhatsappDestination} from '../../../packages/contracts/src/lead';
import {businessRequest} from './business-ui';
import {useRequestKey} from './use-request-key';
export function WhatsappSetup({data}:{data:Workspace}){
  const [workspace,setWorkspace]=useState(data),[rows,setRows]=useState<WhatsappDestination[]>([]),[account,setAccount]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const request=useRequestKey();
  const selected=rows.find(row=>row.account_id===(account||null));
  async function load(){try{const [wa,next]=await Promise.all([businessRequest<{destinations:WhatsappDestination[]}>('whatsapp'),businessRequest<Workspace>('workspace')]);setRows(wa.destinations);setWorkspace(next);}catch(failure){setError(failure instanceof Error?failure.message:'配置暂时无法读取');}}
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget);setBusy(true);setError('');setNotice('');const payload={account_id:account||null,expected_version:selected?.version??0,name:fields.get('name'),phone:fields.get('phone'),state:fields.get('state'),template:fields.get('template'),cooldown_hours:Number(fields.get('cooldown_hours'))};try{await businessRequest('whatsapp',{...payload,request_id:request.forPayload(payload)});request.confirmed();await load();setNotice('WhatsApp 目的地和话术已保存。');}catch(failure){setError(failure instanceof Error?failure.message:'配置未保存');}finally{setBusy(false);}}
  return <details className="business-box channel-settings" onToggle={event=>{if(event.currentTarget.open)void load();}}><summary>WhatsApp 号码与引流话术</summary><p className="muted">品牌默认号码适用于未单独配置的账号。账号专用号码暂停后，该账号停止引流。</p>{error&&<p role="alert" className="alert warning">{error}</p>}{notice&&<p role="status" className="business-success">{notice}</p>}<label>号码适用范围<select value={account} onChange={event=>{setAccount(event.target.value);setNotice('');}}><option value="">本品牌默认</option>{workspace.accounts.filter(row=>row.platform==='facebook').map(row=><option key={row.id} value={row.id}>{row.display_name}</option>)}</select></label>
    <form key={account+'/'+(selected?.version??0)} className="business-form" aria-label="WhatsApp 引流配置" onSubmit={event=>void save(event)}><label>销售联系名称<input name="name" required maxLength={80} defaultValue={selected?.name??'销售团队'} disabled={data.scope.role!=='admin'}/></label><label>WhatsApp 国际号码<input name="phone" required pattern="[1-9][0-9]{6,14}" placeholder="国家区号和号码，不含加号" defaultValue={selected?.phone??''} disabled={data.scope.role!=='admin'}/></label><label>引流状态<select name="state" defaultValue={selected?.state??'ACTIVE'} disabled={data.scope.role!=='admin'}><option value="ACTIVE">启用</option><option value="PAUSED">暂停</option></select></label><label>重复引流间隔（小时）<input name="cooldown_hours" type="number" min={1} max={720} required defaultValue={selected?.cooldown_hours??24} disabled={data.scope.role!=='admin'}/></label><label className="business-wide">WhatsApp 引流话术<textarea name="template" rows={3} required maxLength={1500} defaultValue={selected?.template??'欢迎添加我们的销售 WhatsApp：{whatsapp_url}，同事会继续为你介绍。'} disabled={data.scope.role!=='admin'}/></label><small className="muted business-wide">保留 {'{whatsapp_url}'}，发送时替换为此范围的号码链接。后续销售由 WhatsApp 团队负责。</small>{data.scope.role==='admin'&&<button className="button primary" disabled={busy}>保存 WhatsApp 配置</button>}</form>
  </details>;
}
