import { templateCapabilityKey, templateManifestSchema, templateSnapshotSchema, type TemplateManifest, type TaskSnapshot } from '@kff/contracts';
import { digest, requireCondition } from '@kff/core';

export function fixedPageManifest(key: string, maxBodyLength = 5000): TemplateManifest {
  if (key === 'facebook.comment.reply.browser') return templateManifestSchema.parse({schema_version:'kff.template.v1',engine:'fixed-browser-comment-v1',capability_key:key,adapter_version:'facebook-browser-comment-v1',input:{body_required:true,max_body_length:Math.min(maxBodyLength,1000)},steps:['validate_input','verify_identity','prepare_content','submit_once','verify_original'],permission_gate:'common_execution_gate',success_evidence:'message_acceptance',automatic_write_retry:false});
  if (key === 'kff.fixture.messenger.reply.browser' || key === 'facebook.messenger.reply.browser') return templateManifestSchema.parse({ schema_version: 'kff.template.v1', engine: 'fixed-browser-message-v1', capability_key: key, adapter_version: key === 'facebook.messenger.reply.browser' ? 'facebook-browser-messenger-v1' : 'fixture-browser-messenger-v1', input: { body_required: true, max_body_length: Math.min(maxBodyLength,2000) }, steps: ['validate_input','verify_identity','prepare_content','submit_once','verify_original'], permission_gate: 'common_execution_gate', success_evidence: 'message_acceptance', automatic_write_retry: false });
  if (key === 'kff.fixture.inbox.read.browser' || key === 'facebook.inbox.read.browser') return templateManifestSchema.parse({ schema_version: 'kff.template.v1', engine: 'fixed-inbox-v1', capability_key: key, adapter_version: key === 'facebook.inbox.read.browser' ? 'facebook-inbox-browser-v1' : 'browser-inbox-v1', input: { body_required: false, max_body_length: maxBodyLength }, steps: ['validate_input','verify_identity','read_page'], permission_gate: 'common_execution_gate', success_evidence: 'inbox_page', automatic_write_retry: false });
  if (key === 'facebook.discovery.read.browser') return templateManifestSchema.parse({ schema_version: 'kff.template.v1', engine: 'fixed-discovery-v1', capability_key: key, adapter_version: 'facebook-search-browser-v1', input: { body_required: false, max_body_length: maxBodyLength }, steps: ['validate_input','verify_identity','read_page'], permission_gate: 'common_execution_gate', success_evidence: 'collection_page', automatic_write_retry: false });
  if (key === 'kff.fixture.discovery.read.browser') return templateManifestSchema.parse({ schema_version: 'kff.template.v1', engine: 'fixed-discovery-v1', capability_key: key, adapter_version: 'browser-discovery-v1', input: { body_required: false, max_body_length: maxBodyLength }, steps: ['validate_input','verify_identity','read_page'], permission_gate: 'common_execution_gate', success_evidence: 'collection_page', automatic_write_retry: false });
  const social=key.includes('.social.')||key==='social.comment.reply.api';const capability = templateCapabilityKey.parse(key),message=key.includes('.messenger.')||social,synthetic=key.startsWith('kff.fixture.'); const write = capability.includes('.publish.')||message;
  return templateManifestSchema.parse({ schema_version: 'kff.template.v1', engine: social?'fixed-social-v1':message?'fixed-message-v1':'fixed-page-v1', capability_key: capability, adapter_version: social?'social-outreach-v1':message?(synthetic?'fixture-messenger-v1':'facebook-messenger-v1'):synthetic ? 'fixture-page-v1' : key==='instagram.account.read.api'?'instagram-graph-v1':'facebook-graph-v1', input: { body_required: write, max_body_length: message?Math.min(maxBodyLength,2000):maxBodyLength }, steps: write ? ['validate_input', 'verify_identity', 'prepare_content', 'submit_once', 'verify_original'] : ['validate_input', 'verify_identity'], permission_gate: 'common_execution_gate', success_evidence: message?'message_acceptance':write ? 'published_object_identity_author_content' : 'page_identity', automatic_write_retry: false });
}
export function validateTemplateInput(manifest: TemplateManifest, body: string) {
  templateManifestSchema.parse(manifest);
  requireCondition(body.length <= manifest.input.max_body_length && (!manifest.input.body_required || body.trim().length > 0), 'TEMPLATE_INPUT_INVALID', '内容不满足所选模板的输入限制', 409);
}
export function assertTemplateSnapshot(snapshot: TaskSnapshot) {
  requireCondition(snapshot.template, 'TEMPLATE_SNAPSHOT_REQUIRED', '历史任务缺少模板版本快照，不能启动新的执行', 409);
  const template = templateSnapshotSchema.parse(snapshot.template);
  requireCondition(digest(template.manifest) === template.manifest_hash && template.manifest.capability_key === snapshot.capability_key && template.manifest.adapter_version === snapshot.adapter_version, 'VERSION_CONFLICT', '模板摘要、动作或执行器版本不一致', 409);
  validateTemplateInput(template.manifest, snapshot.body); return template;
}
