import {randomUUID} from 'node:crypto';
import Stripe from 'stripe';
import {AppError,digest} from '../../packages/core/src/index';
import {STRIPE_API_VERSION,type StripeIntent} from '../../packages/core/src/stripe-gateway';
import type {StripeFinancialGateway,StripeFinancialGatewayFactory} from '../../packages/core/src/stripe-financial-gateway';
import type {StripeFinancialPayment,StripeRefund,StripeDispute} from '../../packages/core/src/stripe-financial-contract';
export class StripeFinancialFixture implements StripeFinancialGateway {
 isSynthetic=true;payment:StripeFinancialPayment;refunds=new Map<string,StripeRefund>();disputes=new Map<string,StripeDispute>();requests=new Map<string,{hash:string;id:string}>();calls:{input:Stripe.RefundCreateParams;key:string}[]=[];pages:(string|undefined)[]=[];
 loseResponse=0;unavailable=false;omitRefunds=false;loopPages=false;nextStatus='pending';rejectCreate=false;afterCreate:(()=>Promise<void>)|null=null;
 factory:StripeFinancialGatewayFactory=async()=>this;
 constructor(public accountId:string,intent:StripeIntent){this.payment={...structuredClone(intent),latest_charge:{id:'ch_'+intent.id.slice(3),object:'charge',amount:intent.amount,amount_captured:intent.amount,amount_refunded:0,currency:intent.currency,payment_intent:intent.id,livemode:intent.livemode,paid:true,captured:true,disputed:false,status:'succeeded'}};}
 check(){if(this.unavailable)throw new AppError('STRIPE_UNAVAILABLE','Synthetic financial lookup unavailable',503);}
 async identity(){this.check();return {id:this.accountId};}
 async retrievePayment(id:string){this.check();if(id!==this.payment.id)throw new AppError('STRIPE_PAYMENT_OBJECT_MISMATCH','Synthetic unknown payment',409);const result=structuredClone(this.payment);result.latest_charge!.amount_refunded=[...this.refunds.values()].filter(row=>row.status==='succeeded').reduce((n,row)=>n+row.amount,0);return result;}
 addRefund(amount:number,status='pending',metadata:StripeRefund['metadata']={}){const row:StripeRefund={id:'re_'+randomUUID().replaceAll('-',''),object:'refund',amount,currency:this.payment.currency,payment_intent:this.payment.id,charge:this.payment.latest_charge!.id,created:Math.floor(Date.now()/1000),status,metadata,balance_transaction:null,failure_balance_transaction:null,failure_reason:null};this.refunds.set(row.id,row);return row;}
 addDispute(){const row:StripeDispute={id:'dp_'+randomUUID().replaceAll('-',''),object:'dispute',amount:this.payment.amount,currency:this.payment.currency,payment_intent:this.payment.id,charge:this.payment.latest_charge!.id,created:Math.floor(Date.now()/1000),livemode:this.payment.livemode,status:'needs_response',reason:'product_not_received',is_charge_refundable:false,balance_transactions:[]};this.payment.latest_charge!.disputed=true;this.disputes.set(row.id,row);return row;}
 async createRefund(input:Stripe.RefundCreateParams,key:string){this.check();this.calls.push({input:structuredClone(input),key});if(this.rejectCreate)throw new AppError('STRIPE_REQUEST_REJECTED','Synthetic refund rejected',409);const prior=this.requests.get(key);if(prior){if(prior.hash!==digest(input))throw new AppError('STRIPE_REQUEST_REJECTED','Synthetic idempotency mismatch',409);return structuredClone(this.refunds.get(prior.id)!);}
  if(input.payment_intent!==this.payment.id||!input.amount||input.amount+[...this.refunds.values()].filter(row=>!['failed','canceled'].includes(row.status??'unknown')).reduce((n,row)=>n+row.amount,0)>this.payment.amount)throw new AppError('STRIPE_REQUEST_REJECTED','Synthetic amount rejected',409);
  const row=this.addRefund(input.amount,this.nextStatus,input.metadata as StripeRefund['metadata']);this.requests.set(key,{hash:digest(input),id:row.id});await this.afterCreate?.();if(this.loseResponse>0){this.loseResponse--;throw new AppError('STRIPE_UNAVAILABLE','Synthetic response lost',503);}return structuredClone(row);
 }
 async retrieveRefund(id:string){this.check();const row=this.refunds.get(id);if(!row)throw new AppError('STRIPE_REQUEST_REJECTED','Synthetic unknown refund',409);return structuredClone(row);}
 async listRefunds(id:string,cursor?:string){this.check();this.pages.push(cursor);if(id!==this.payment.id)throw new Error('Unexpected fixture payment');if(this.omitRefunds)return {data:[],has_more:false};const all=[...this.refunds.values()],start=this.loopPages?0:cursor?all.findIndex(row=>row.id===cursor)+1:0;return {data:structuredClone(all.slice(start,start+100)),has_more:this.loopPages||start+100<all.length};}
 async retrieveDispute(id:string){this.check();const row=this.disputes.get(id);if(!row)throw new AppError('STRIPE_REQUEST_REJECTED','Synthetic unknown dispute',409);return structuredClone(row);}
 async listDisputes(id:string,cursor?:string){this.check();if(id!==this.payment.id)throw new Error('Unexpected fixture payment');const all=[...this.disputes.values()],start=cursor?all.findIndex(row=>row.id===cursor)+1:0;return {data:structuredClone(all.slice(start,start+100)),has_more:start+100<all.length};}
}
export function signedFinancialEvent(object:unknown,secret:string,type='refund.updated',changes:Record<string,unknown>={}){const payload={id:'evt_'+randomUUID().replaceAll('-',''),object:'event',type,created:Math.floor(Date.now()/1000),api_version:STRIPE_API_VERSION,livemode:false,data:{object},...changes};const raw=Buffer.from(JSON.stringify(payload)),signature=Stripe.webhooks.generateTestHeaderString({payload:raw.toString(),secret});return {payload,raw,signature};}
